// Mandarin Journey — course content, HSK 1 (Units 1–15)
// Words: id, cn (hanzi), py (pinyin display), pyPlain (toneless, ü→v, for typing check), en, emoji

window.WORDS = {
  // U1 Greetings
  ni:       { cn: '你',   py: 'nǐ',       pyPlain: 'ni',       en: 'you',                   emoji: '👉' },
  hao:      { cn: '好',   py: 'hǎo',      pyPlain: 'hao',      en: 'good',                  emoji: '👍' },
  nihao:    { cn: '你好', py: 'nǐ hǎo',   pyPlain: 'nihao',    en: 'hello',                 emoji: '👋' },
  wo:       { cn: '我',   py: 'wǒ',       pyPlain: 'wo',       en: 'I / me',                emoji: '🙋' },
  shi:      { cn: '是',   py: 'shì',      pyPlain: 'shi',      en: 'to be (am / is / are)', emoji: '✅' },
  laoshi:   { cn: '老师', py: 'lǎoshī',   pyPlain: 'laoshi',   en: 'teacher',               emoji: '👩‍🏫' },
  xuesheng: { cn: '学生', py: 'xuésheng', pyPlain: 'xuesheng', en: 'student',               emoji: '🧑‍🎓' },
  ma:       { cn: '吗',   py: 'ma',       pyPlain: 'ma',       en: 'question particle',     emoji: '❓' },
  // U2 Numbers
  yi:   { cn: '一', py: 'yī',  pyPlain: 'yi',  en: 'one',   emoji: '1️⃣' },
  er:   { cn: '二', py: 'èr',  pyPlain: 'er',  en: 'two',   emoji: '2️⃣' },
  san:  { cn: '三', py: 'sān', pyPlain: 'san', en: 'three', emoji: '3️⃣' },
  si:   { cn: '四', py: 'sì',  pyPlain: 'si',  en: 'four',  emoji: '4️⃣' },
  wu:   { cn: '五', py: 'wǔ',  pyPlain: 'wu',  en: 'five',  emoji: '5️⃣' },
  liu:  { cn: '六', py: 'liù', pyPlain: 'liu', en: 'six',   emoji: '6️⃣' },
  qi:   { cn: '七', py: 'qī',  pyPlain: 'qi',  en: 'seven', emoji: '7️⃣' },
  ba:   { cn: '八', py: 'bā',  pyPlain: 'ba',  en: 'eight', emoji: '8️⃣' },
  jiu:  { cn: '九', py: 'jiǔ', pyPlain: 'jiu', en: 'nine',  emoji: '9️⃣' },
  shi2: { cn: '十', py: 'shí', pyPlain: 'shi', en: 'ten',   emoji: '🔟' },
  ge:   { cn: '个', py: 'gè',  pyPlain: 'ge',  en: 'measure word (general)', emoji: '📦' },
  ji:   { cn: '几', py: 'jǐ',  pyPlain: 'ji',  en: 'how many',               emoji: '🤔' },
  // U3 Politeness
  xiexie:    { cn: '谢谢',   py: 'xièxie',      pyPlain: 'xiexie',    en: 'thank you',        emoji: '🙏' },
  bukeqi:    { cn: '不客气', py: 'bú kèqi',     pyPlain: 'bukeqi',    en: "you're welcome",   emoji: '😊' },
  zaijian:   { cn: '再见',   py: 'zàijiàn',     pyPlain: 'zaijian',   en: 'goodbye',          emoji: '👋' },
  duibuqi:   { cn: '对不起', py: 'duìbuqǐ',     pyPlain: 'duibuqi',   en: 'sorry',            emoji: '😔' },
  meiguanxi: { cn: '没关系', py: 'méi guānxi',  pyPlain: 'meiguanxi', en: "it's okay / no problem", emoji: '🤝' },
  qing:      { cn: '请',     py: 'qǐng',        pyPlain: 'qing',      en: 'please',           emoji: '🤲' },
  wei:       { cn: '喂',     py: 'wéi',         pyPlain: 'wei',       en: 'hello? (phone)',   emoji: '📞' },
  hen:       { cn: '很',     py: 'hěn',         pyPlain: 'hen',       en: 'very',             emoji: '💯' },
  gaoxing:   { cn: '高兴',   py: 'gāoxìng',     pyPlain: 'gaoxing',   en: 'happy / glad',     emoji: '😄' },
  renshi:    { cn: '认识',   py: 'rènshi',      pyPlain: 'renshi',    en: 'to know (a person)', emoji: '🤗' },
  // U4 Names & nations
  jiao:     { cn: '叫',   py: 'jiào',     pyPlain: 'jiao',     en: 'to be called',     emoji: '📛' },
  shenme:   { cn: '什么', py: 'shénme',   pyPlain: 'shenme',   en: 'what',             emoji: '❔' },
  mingzi:   { cn: '名字', py: 'míngzi',   pyPlain: 'mingzi',   en: 'name',             emoji: '🪪' },
  ne:       { cn: '呢',   py: 'ne',       pyPlain: 'ne',       en: 'and you? (particle)', emoji: '🔁' },
  shei:     { cn: '谁',   py: 'shéi',     pyPlain: 'shei',     en: 'who',              emoji: '🕵️' },
  ta:       { cn: '他',   py: 'tā',       pyPlain: 'ta',       en: 'he / him',         emoji: '👨' },
  ta2:      { cn: '她',   py: 'tā',       pyPlain: 'ta',       en: 'she / her',        emoji: '👩' },
  ren:      { cn: '人',   py: 'rén',      pyPlain: 'ren',      en: 'person',           emoji: '🧍' },
  zhongguo: { cn: '中国', py: 'Zhōngguó', pyPlain: 'zhongguo', en: 'China',            emoji: '🇨🇳' },
  meiguo:   { cn: '美国', py: 'Měiguó',   pyPlain: 'meiguo',   en: 'USA',              emoji: '🇺🇸' },
  pengyou:  { cn: '朋友', py: 'péngyou',  pyPlain: 'pengyou',  en: 'friend',           emoji: '🧑‍🤝‍🧑' },
  de:       { cn: '的',   py: 'de',       pyPlain: 'de',       en: "'s (possessive)",  emoji: '🔗' },
  // U5 Family
  baba:   { cn: '爸爸', py: 'bàba',    pyPlain: 'baba',   en: 'dad',            emoji: '👨‍🦱' },
  mama:   { cn: '妈妈', py: 'māma',    pyPlain: 'mama',   en: 'mom',            emoji: '👩‍🦰' },
  erzi:   { cn: '儿子', py: 'érzi',    pyPlain: 'erzi',   en: 'son',            emoji: '👦' },
  nver:   { cn: '女儿', py: "nǚ'ér",   pyPlain: 'nver',   en: 'daughter',       emoji: '👧' },
  men:    { cn: '们',   py: 'men',     pyPlain: 'men',    en: 'plural (we/they)', emoji: '👥' },
  jia:    { cn: '家',   py: 'jiā',     pyPlain: 'jia',    en: 'home / family',  emoji: '🏠' },
  you:    { cn: '有',   py: 'yǒu',     pyPlain: 'you',    en: 'to have',        emoji: '🤲' },
  meiyou: { cn: '没有', py: 'méiyǒu',  pyPlain: 'meiyou', en: 'to not have',    emoji: '🚫' },
  ai:     { cn: '爱',   py: 'ài',      pyPlain: 'ai',     en: 'to love',        emoji: '❤️' },
  sui:    { cn: '岁',   py: 'suì',     pyPlain: 'sui',    en: 'years old',      emoji: '🎂' },
  // U6 This & that
  zhe:     { cn: '这',   py: 'zhè',      pyPlain: 'zhe',     en: 'this',       emoji: '👇' },
  na4:     { cn: '那',   py: 'nà',       pyPlain: 'na',      en: 'that',       emoji: '👉' },
  shu:     { cn: '书',   py: 'shū',      pyPlain: 'shu',     en: 'book',       emoji: '📖' },
  zhuozi:  { cn: '桌子', py: 'zhuōzi',   pyPlain: 'zhuozi',  en: 'table',      emoji: '🪑' },
  yizi:    { cn: '椅子', py: 'yǐzi',     pyPlain: 'yizi',    en: 'chair',      emoji: '💺' },
  beizi:   { cn: '杯子', py: 'bēizi',    pyPlain: 'beizi',   en: 'cup',        emoji: '🥤' },
  dianshi: { cn: '电视', py: 'diànshì',  pyPlain: 'dianshi', en: 'TV',         emoji: '📺' },
  diannao: { cn: '电脑', py: 'diànnǎo',  pyPlain: 'diannao', en: 'computer',   emoji: '💻' },
  mao:     { cn: '猫',   py: 'māo',      pyPlain: 'mao',     en: 'cat',        emoji: '🐱' },
  gou:     { cn: '狗',   py: 'gǒu',      pyPlain: 'gou',     en: 'dog',        emoji: '🐶' },
  he2:     { cn: '和',   py: 'hé',       pyPlain: 'he',      en: 'and',        emoji: '➕' },
  // U7 Food & drink
  chi:     { cn: '吃',   py: 'chī',      pyPlain: 'chi',     en: 'to eat',     emoji: '🍽️' },
  he:      { cn: '喝',   py: 'hē',       pyPlain: 'he',      en: 'to drink',   emoji: '🥛' },
  mifan:   { cn: '米饭', py: 'mǐfàn',    pyPlain: 'mifan',   en: 'rice (cooked)', emoji: '🍚' },
  cai:     { cn: '菜',   py: 'cài',      pyPlain: 'cai',     en: 'dish / vegetable', emoji: '🥬' },
  cha:     { cn: '茶',   py: 'chá',      pyPlain: 'cha',     en: 'tea',        emoji: '🍵' },
  shui:    { cn: '水',   py: 'shuǐ',     pyPlain: 'shui',    en: 'water',      emoji: '💧' },
  shuiguo: { cn: '水果', py: 'shuǐguǒ',  pyPlain: 'shuiguo', en: 'fruit',      emoji: '🍇' },
  pingguo: { cn: '苹果', py: 'píngguǒ',  pyPlain: 'pingguo', en: 'apple',      emoji: '🍎' },
  xiang:   { cn: '想',   py: 'xiǎng',    pyPlain: 'xiang',   en: 'would like to', emoji: '💭' },
  yao:     { cn: '要',   py: 'yào',      pyPlain: 'yao',     en: 'to want',    emoji: '🙌' },
  // U8 Dates
  jintian:  { cn: '今天', py: 'jīntiān',  pyPlain: 'jintian',  en: 'today',        emoji: '📅' },
  mingtian: { cn: '明天', py: 'míngtiān', pyPlain: 'mingtian', en: 'tomorrow',     emoji: '⏭️' },
  zuotian:  { cn: '昨天', py: 'zuótiān',  pyPlain: 'zuotian',  en: 'yesterday',    emoji: '⏮️' },
  nian:     { cn: '年',   py: 'nián',     pyPlain: 'nian',     en: 'year',         emoji: '🗓️' },
  yue:      { cn: '月',   py: 'yuè',      pyPlain: 'yue',      en: 'month / moon', emoji: '🌙' },
  hao4:     { cn: '号',   py: 'hào',      pyPlain: 'hao',      en: 'date (of month)', emoji: '🔢' },
  xingqi:   { cn: '星期', py: 'xīngqī',   pyPlain: 'xingqi',   en: 'week',         emoji: '📆' },
  tian:     { cn: '天',   py: 'tiān',     pyPlain: 'tian',     en: 'day / sky',    emoji: '☁️' },
  xianzai:  { cn: '现在', py: 'xiànzài',  pyPlain: 'xianzai',  en: 'now',          emoji: '⏱️' },
  shihou:   { cn: '时候', py: 'shíhou',   pyPlain: 'shihou',   en: 'time / moment', emoji: '🕰️' },
  // U9 Clock & routine
  dian:     { cn: '点',   py: 'diǎn',      pyPlain: 'dian',     en: "o'clock",      emoji: '🕒' },
  fenzhong: { cn: '分钟', py: 'fēnzhōng',  pyPlain: 'fenzhong', en: 'minute',       emoji: '⏲️' },
  shangwu:  { cn: '上午', py: 'shàngwǔ',   pyPlain: 'shangwu',  en: 'morning (a.m.)', emoji: '🌅' },
  zhongwu:  { cn: '中午', py: 'zhōngwǔ',   pyPlain: 'zhongwu',  en: 'noon',         emoji: '☀️' },
  xiawu:    { cn: '下午', py: 'xiàwǔ',     pyPlain: 'xiawu',    en: 'afternoon',    emoji: '🌇' },
  wanshang: { cn: '晚上', py: 'wǎnshang',  pyPlain: 'wanshang', en: 'evening',      emoji: '🌃' },
  shuijiao: { cn: '睡觉', py: 'shuìjiào',  pyPlain: 'shuijiao', en: 'to sleep',     emoji: '😴' },
  dianying: { cn: '电影', py: 'diànyǐng',  pyPlain: 'dianying', en: 'movie',        emoji: '🎬' },
  kan:      { cn: '看',   py: 'kàn',       pyPlain: 'kan',      en: 'to look / watch', emoji: '👀' },
  // U10 Places
  zai:       { cn: '在',   py: 'zài',       pyPlain: 'zai',       en: 'to be at / in',  emoji: '📍' },
  nar:       { cn: '哪儿', py: 'nǎr',       pyPlain: 'nar',       en: 'where',          emoji: '🧭' },
  zher:      { cn: '这儿', py: 'zhèr',      pyPlain: 'zher',      en: 'here',           emoji: '⬇️' },
  nar4:      { cn: '那儿', py: 'nàr',       pyPlain: 'nar',       en: 'there',          emoji: '↗️' },
  xuexiao:   { cn: '学校', py: 'xuéxiào',   pyPlain: 'xuexiao',   en: 'school',         emoji: '🏫' },
  yiyuan:    { cn: '医院', py: 'yīyuàn',    pyPlain: 'yiyuan',    en: 'hospital',       emoji: '🏥' },
  shangdian: { cn: '商店', py: 'shāngdiàn', pyPlain: 'shangdian', en: 'shop / store',   emoji: '🏪' },
  fandian:   { cn: '饭店', py: 'fàndiàn',   pyPlain: 'fandian',   en: 'restaurant / hotel', emoji: '🍴' },
  beijing:   { cn: '北京', py: 'Běijīng',   pyPlain: 'beijing',   en: 'Beijing',        emoji: '🏯' },
  li:        { cn: '里',   py: 'lǐ',        pyPlain: 'li',        en: 'inside',         emoji: '📥' },
  // U11 Doing verbs
  qu:      { cn: '去',   py: 'qù',      pyPlain: 'qu',      en: 'to go',      emoji: '🚶' },
  lai:     { cn: '来',   py: 'lái',     pyPlain: 'lai',     en: 'to come',    emoji: '🫴' },
  hui2:    { cn: '回',   py: 'huí',     pyPlain: 'hui',     en: 'to return',  emoji: '↩️' },
  zuo4:    { cn: '做',   py: 'zuò',     pyPlain: 'zuo',     en: 'to do / make', emoji: '🛠️' },
  gongzuo: { cn: '工作', py: 'gōngzuò', pyPlain: 'gongzuo', en: 'to work / job', emoji: '💼' },
  ting:    { cn: '听',   py: 'tīng',    pyPlain: 'ting',    en: 'to listen',  emoji: '👂' },
  shuo:    { cn: '说',   py: 'shuō',    pyPlain: 'shuo',    en: 'to speak / say', emoji: '🗣️' },
  du:      { cn: '读',   py: 'dú',      pyPlain: 'du',      en: 'to read',    emoji: '📚' },
  xie:     { cn: '写',   py: 'xiě',     pyPlain: 'xie',     en: 'to write',   emoji: '✍️' },
  // U12 Weather & feelings
  tianqi:    { cn: '天气',   py: 'tiānqì',     pyPlain: 'tianqi',    en: 'weather',       emoji: '🌤️' },
  xiayu:     { cn: '下雨',   py: 'xià yǔ',     pyPlain: 'xiayu',     en: 'to rain',       emoji: '🌧️' },
  re:        { cn: '热',     py: 'rè',         pyPlain: 're',        en: 'hot',           emoji: '🥵' },
  leng:      { cn: '冷',     py: 'lěng',       pyPlain: 'leng',      en: 'cold',          emoji: '🥶' },
  bu:        { cn: '不',     py: 'bù',         pyPlain: 'bu',        en: 'not / no',      emoji: '🙅' },
  ye:        { cn: '也',     py: 'yě',         pyPlain: 'ye',        en: 'also',          emoji: '🟰' },
  dou:       { cn: '都',     py: 'dōu',        pyPlain: 'dou',       en: 'all / both',    emoji: '🫶' },
  zenmeyang: { cn: '怎么样', py: 'zěnmeyàng',  pyPlain: 'zenmeyang', en: 'how is it?',    emoji: '🤷' },
  xihuan:    { cn: '喜欢',   py: 'xǐhuan',     pyPlain: 'xihuan',    en: 'to like',       emoji: '😍' },
  // U13 Shopping
  mai:     { cn: '买',   py: 'mǎi',     pyPlain: 'mai',     en: 'to buy',        emoji: '🛒' },
  qian:    { cn: '钱',   py: 'qián',    pyPlain: 'qian',    en: 'money',         emoji: '💵' },
  duoshao: { cn: '多少', py: 'duōshao', pyPlain: 'duoshao', en: 'how much / many', emoji: '🧮' },
  kuai:    { cn: '块',   py: 'kuài',    pyPlain: 'kuai',    en: 'kuai (yuan)',   emoji: '🪙' },
  dongxi:  { cn: '东西', py: 'dōngxi',  pyPlain: 'dongxi',  en: 'thing / stuff', emoji: '🎁' },
  yifu:    { cn: '衣服', py: 'yīfu',    pyPlain: 'yifu',    en: 'clothes',       emoji: '👕' },
  tai:     { cn: '太',   py: 'tài',     pyPlain: 'tai',     en: 'too (much)',    emoji: '😵' },
  da:      { cn: '大',   py: 'dà',      pyPlain: 'da',      en: 'big',           emoji: '🐘' },
  xiao:    { cn: '小',   py: 'xiǎo',    pyPlain: 'xiao',    en: 'small',         emoji: '🐭' },
  le:      { cn: '了',   py: 'le',      pyPlain: 'le',      en: 'done! (particle)', emoji: '✔️' },
  // U14 Getting around
  che:        { cn: '车',     py: 'chē',        pyPlain: 'che',        en: 'car / vehicle', emoji: '🚗' },
  chuzuche:   { cn: '出租车', py: 'chūzūchē',   pyPlain: 'chuzuche',   en: 'taxi',          emoji: '🚕' },
  feiji:      { cn: '飞机',   py: 'fēijī',      pyPlain: 'feiji',      en: 'airplane',      emoji: '✈️' },
  huochezhan: { cn: '火车站', py: 'huǒchēzhàn', pyPlain: 'huochezhan', en: 'train station', emoji: '🚉' },
  zuo_sit:    { cn: '坐',     py: 'zuò',        pyPlain: 'zuo',        en: 'to sit / take (transport)', emoji: '🧘' },
  kai:        { cn: '开',     py: 'kāi',        pyPlain: 'kai',        en: 'to drive / open', emoji: '🔑' },
  zenme:      { cn: '怎么',   py: 'zěnme',      pyPlain: 'zenme',      en: 'how',           emoji: '🛤️' },
  // U15 Can do it!
  hui4:      { cn: '会',   py: 'huì',       pyPlain: 'hui',      en: 'can (learned skill)', emoji: '🎯' },
  neng:      { cn: '能',   py: 'néng',      pyPlain: 'neng',     en: 'can / be able to',    emoji: '💪' },
  hanyu:     { cn: '汉语', py: 'Hànyǔ',     pyPlain: 'hanyu',    en: 'Chinese (language)',  emoji: '🈶' },
  dianhua:   { cn: '电话', py: 'diànhuà',   pyPlain: 'dianhua',  en: 'telephone',           emoji: '☎️' },
  da3:       { cn: '打',   py: 'dǎ',        pyPlain: 'da',       en: 'to hit / make (a call)', emoji: '🤙' },
  kanjian:   { cn: '看见', py: 'kànjiàn',   pyPlain: 'kanjian',  en: 'to see',              emoji: '👁️' },
  xiansheng: { cn: '先生', py: 'xiānsheng', pyPlain: 'xiansheng', en: 'Mr. / sir',          emoji: '🤵' },
  xiaojie:   { cn: '小姐', py: 'xiǎojiě',   pyPlain: 'xiaojie',  en: 'Miss / young lady',   emoji: '👱‍♀️' },
  yisheng:   { cn: '医生', py: 'yīshēng',   pyPlain: 'yisheng',  en: 'doctor',              emoji: '🧑‍⚕️' },
};

window.LESSON_TYPES = [
  { key: 'vocab',      name: 'New Words',  icon: '🈶' },
  { key: 'hanzi',      name: 'Hanzi',      icon: '✍️' },
  { key: 'grammar',    name: 'Grammar',    icon: '🧩' },
  { key: 'listening',  name: 'Listening',  icon: '👂' },
  { key: 'speaking',   name: 'Speaking',   icon: '🗣️' },
  { key: 'checkpoint', name: 'Checkpoint', icon: '🏁' },
];

window.UNITS = [
  {
    id: 'u1', title: 'Greetings', icon: '👋', hsk: 1,
    words: ['ni', 'hao', 'nihao', 'wo', 'shi', 'laoshi', 'xuesheng', 'ma'],
    hanzi: ['你', '好', '我', '是'],
    grammar: {
      name: '是 sentences & 吗 questions',
      intro: 'The most useful pattern in Chinese: <b>A 是 B</b> means "A is B". No verb changes, ever! To turn any statement into a yes/no question, just add <b>吗 ma</b> at the end.',
      examples: [
        { cn: '我是学生。', py: 'Wǒ shì xuésheng.', en: 'I am a student.' },
        { cn: '你是老师吗？', py: 'Nǐ shì lǎoshī ma?', en: 'Are you a teacher?' },
      ],
      fillBlanks: [
        { before: '我', after: '学生。', answer: '是', choices: ['是', '吗', '好'], en: 'I am a student.' },
        { before: '你是老师', after: '？', answer: '吗', choices: ['吗', '是', '我'], en: 'Are you a teacher?' },
        { before: '', after: '是学生。', answer: '我', choices: ['我', '吗', '好'], en: 'I am a student.' },
      ],
      tiles: [
        { parts: ['我', '是', '老师'], en: 'I am a teacher.' },
        { parts: ['你', '是', '学生', '吗'], en: 'Are you a student?' },
      ],
    },
    sentences: [
      { cn: '你好！', py: 'Nǐ hǎo!', en: 'Hello!' },
      { cn: '我是学生。', py: 'Wǒ shì xuésheng.', en: 'I am a student.' },
      { cn: '你是老师吗？', py: 'Nǐ shì lǎoshī ma?', en: 'Are you a teacher?' },
      { cn: '我是老师。', py: 'Wǒ shì lǎoshī.', en: 'I am a teacher.' },
    ],
  },
  {
    id: 'u2', title: 'Numbers 1–10', icon: '🔢', hsk: 1,
    words: ['yi', 'er', 'san', 'si', 'wu', 'liu', 'qi', 'ba', 'jiu', 'shi2', 'ge', 'ji'],
    hanzi: ['一', '二', '三', '十'],
    grammar: {
      name: 'Counting things: 个 and 几',
      intro: 'To count things in Chinese you need a <b>measure word</b> between the number and the noun. The all-purpose one is <b>个 gè</b>: 三个学生 = "three students". To ask "how many?", use <b>几 jǐ</b> in the number\'s place: 几个学生? = "how many students?"',
      examples: [
        { cn: '三个学生。', py: 'Sān gè xuésheng.', en: 'Three students.' },
        { cn: '几个老师？', py: 'Jǐ gè lǎoshī?', en: 'How many teachers?' },
      ],
      fillBlanks: [
        { before: '三', after: '学生。', answer: '个', choices: ['个', '几', '十'], en: 'Three students.' },
        { before: '', after: '个老师？', answer: '几', choices: ['几', '个', '一'], en: 'How many teachers?' },
        { before: '我是一', after: '学生。', answer: '个', choices: ['个', '几', '吗'], en: 'I am a student.' },
      ],
      tiles: [
        { parts: ['几', '个', '学生'], en: 'How many students?' },
        { parts: ['十', '个', '老师'], en: 'Ten teachers.' },
      ],
    },
    sentences: [
      { cn: '一、二、三！', py: 'Yī, èr, sān!', en: 'One, two, three!' },
      { cn: '三个学生。', py: 'Sān gè xuésheng.', en: 'Three students.' },
      { cn: '几个老师？', py: 'Jǐ gè lǎoshī?', en: 'How many teachers?' },
      { cn: '十个学生。', py: 'Shí gè xuésheng.', en: 'Ten students.' },
    ],
  },
  {
    id: 'u3', title: 'Politeness', icon: '🙏', hsk: 1,
    words: ['xiexie', 'bukeqi', 'zaijian', 'duibuqi', 'meiguanxi', 'qing', 'wei', 'hen', 'gaoxing', 'renshi'],
    hanzi: ['谢', '再', '见', '请'],
    grammar: {
      name: 'Polite magic words',
      intro: 'Say <b>谢谢</b> to thank someone — the reply is <b>不客气</b>. If you bump into someone: <b>对不起</b>, and they answer <b>没关系</b>. When you meet someone new, use the golden formula: <b>很高兴认识你</b> — "very glad to know you".',
      examples: [
        { cn: '谢谢你！', py: 'Xièxie nǐ!', en: 'Thank you!' },
        { cn: '很高兴认识你。', py: 'Hěn gāoxìng rènshi nǐ.', en: 'Nice to meet you.' },
      ],
      fillBlanks: [
        { before: '', after: '客气。', answer: '不', choices: ['不', '很', '请'], en: "You're welcome." },
        { before: '再', after: '！', answer: '见', choices: ['见', '好', '谢'], en: 'Goodbye!' },
        { before: '很高兴', after: '你。', answer: '认识', choices: ['认识', '再见', '谢谢'], en: 'Nice to meet you.' },
      ],
      tiles: [
        { parts: ['很', '高兴', '认识', '你'], en: 'Nice to meet you.' },
        { parts: ['你', '好', '吗'], en: 'How are you?' },
      ],
    },
    sentences: [
      { cn: '谢谢你！', py: 'Xièxie nǐ!', en: 'Thank you!' },
      { cn: '不客气。', py: 'Bú kèqi.', en: "You're welcome." },
      { cn: '很高兴认识你！', py: 'Hěn gāoxìng rènshi nǐ!', en: 'Nice to meet you!' },
      { cn: '再见！', py: 'Zàijiàn!', en: 'Goodbye!' },
    ],
  },
  {
    id: 'u4', title: 'Names & Nations', icon: '🪪', hsk: 1,
    words: ['jiao', 'shenme', 'mingzi', 'ne', 'shei', 'ta', 'ta2', 'ren', 'zhongguo', 'meiguo', 'pengyou', 'de'],
    hanzi: ['叫', '名', '中', '国'],
    grammar: {
      name: '什么 questions & 的 (my / your)',
      intro: 'Question words stay in place in Chinese — no reordering! <b>你叫什么名字？</b> is literally "you called what name?". And <b>的 de</b> makes possessives: 我的 = my, 你的 = your, 我的朋友 = my friend.',
      examples: [
        { cn: '你叫什么名字？', py: 'Nǐ jiào shénme míngzi?', en: "What's your name?" },
        { cn: '他是我的朋友。', py: 'Tā shì wǒ de péngyou.', en: 'He is my friend.' },
      ],
      fillBlanks: [
        { before: '你叫什么名', after: '？', answer: '字', choices: ['字', '叫', '呢'], en: "What's your name?" },
        { before: '他是我', after: '朋友。', answer: '的', choices: ['的', '吗', '呢'], en: 'He is my friend.' },
        { before: '你是美国人', after: '？', answer: '吗', choices: ['吗', '呢', '的'], en: 'Are you American?' },
      ],
      tiles: [
        { parts: ['你', '叫', '什么', '名字'], en: "What's your name?" },
        { parts: ['她', '是', '我', '的', '朋友'], en: 'She is my friend.' },
      ],
    },
    sentences: [
      { cn: '你叫什么名字？', py: 'Nǐ jiào shénme míngzi?', en: "What's your name?" },
      { cn: '我叫小明。', py: 'Wǒ jiào Xiǎomíng.', en: 'My name is Xiaoming.' },
      { cn: '你是中国人吗？', py: 'Nǐ shì Zhōngguó rén ma?', en: 'Are you Chinese?' },
      { cn: '他是我的朋友。', py: 'Tā shì wǒ de péngyou.', en: 'He is my friend.' },
    ],
  },
  {
    id: 'u5', title: 'Family', icon: '👨‍👩‍👧', hsk: 1,
    words: ['baba', 'mama', 'erzi', 'nver', 'men', 'jia', 'you', 'meiyou', 'ai', 'sui'],
    hanzi: ['有', '家', '爱', '岁'],
    grammar: {
      name: '有 — to have (and 没有 — to not have)',
      intro: '<b>有 yǒu</b> means "to have". Its negative is special: always <b>没有 méiyǒu</b>, never 不有! Ask age with <b>几岁</b>: 你儿子几岁? = "How old is your son?"',
      examples: [
        { cn: '我有一个儿子。', py: 'Wǒ yǒu yí gè érzi.', en: 'I have a son.' },
        { cn: '我没有女儿。', py: "Wǒ méiyǒu nǚ'ér.", en: "I don't have a daughter." },
      ],
      fillBlanks: [
        { before: '我', after: '一个儿子。', answer: '有', choices: ['有', '是', '爱'], en: 'I have a son.' },
        { before: '我没', after: '女儿。', answer: '有', choices: ['有', '是', '们'], en: "I don't have a daughter." },
        { before: '你女儿几', after: '？', answer: '岁', choices: ['岁', '个', '家'], en: 'How old is your daughter?' },
      ],
      tiles: [
        { parts: ['我', '有', '一', '个', '儿子'], en: 'I have a son.' },
        { parts: ['我', '爱', '我', '的', '家'], en: 'I love my family.' },
      ],
    },
    sentences: [
      { cn: '我有一个儿子。', py: 'Wǒ yǒu yí gè érzi.', en: 'I have a son.' },
      { cn: '你有没有女儿？', py: "Nǐ yǒu méiyǒu nǚ'ér?", en: 'Do you have a daughter?' },
      { cn: '我爱我的家。', py: 'Wǒ ài wǒ de jiā.', en: 'I love my family.' },
      { cn: '你儿子几岁？', py: 'Nǐ érzi jǐ suì?', en: 'How old is your son?' },
    ],
  },
  {
    id: 'u6', title: 'This & That', icon: '🐱', hsk: 1,
    words: ['zhe', 'na4', 'shu', 'zhuozi', 'yizi', 'beizi', 'dianshi', 'diannao', 'mao', 'gou', 'he2'],
    hanzi: ['这', '那', '书', '猫'],
    grammar: {
      name: '这 this & 那 that',
      intro: 'Point at things! <b>这是…</b> = "this is…", <b>那是…</b> = "that is…". Ask about anything with <b>那是什么？</b> "what is that?" Join things with <b>和 hé</b> = "and" (only for nouns, not sentences).',
      examples: [
        { cn: '这是我的书。', py: 'Zhè shì wǒ de shū.', en: 'This is my book.' },
        { cn: '那是什么？', py: 'Nà shì shénme?', en: 'What is that?' },
      ],
      fillBlanks: [
        { before: '', after: '是我的书。', answer: '这', choices: ['这', '吗', '个'], en: 'This is my book.' },
        { before: '那是', after: '？', answer: '什么', choices: ['什么', '谁', '吗'], en: 'What is that?' },
        { before: '我有一个', after: '。', answer: '杯子', choices: ['杯子', '和', '这'], en: 'I have a cup.' },
      ],
      tiles: [
        { parts: ['这', '是', '我', '的', '书'], en: 'This is my book.' },
        { parts: ['那', '是', '什么'], en: 'What is that?' },
      ],
    },
    sentences: [
      { cn: '这是我的书。', py: 'Zhè shì wǒ de shū.', en: 'This is my book.' },
      { cn: '那是什么？', py: 'Nà shì shénme?', en: 'What is that?' },
      { cn: '那是我的电脑。', py: 'Nà shì wǒ de diànnǎo.', en: 'That is my computer.' },
      { cn: '我家有猫和狗。', py: 'Wǒ jiā yǒu māo hé gǒu.', en: 'My family has a cat and a dog.' },
    ],
  },
  {
    id: 'u7', title: 'Food & Drink', icon: '🍜', hsk: 1,
    words: ['chi', 'he', 'mifan', 'cai', 'cha', 'shui', 'shuiguo', 'pingguo', 'xiang', 'yao'],
    hanzi: ['吃', '喝', '水', '果'],
    grammar: {
      name: '想 & 要 — wanting things',
      intro: '<b>想 xiǎng</b> + verb = "would like to" (soft). <b>要 yào</b> + verb or noun = "want" (decided!). 我想喝茶 = I\'d like to drink tea. 我要米饭 = I want rice.',
      examples: [
        { cn: '我想喝茶。', py: 'Wǒ xiǎng hē chá.', en: 'I would like to drink tea.' },
        { cn: '你要吃什么？', py: 'Nǐ yào chī shénme?', en: 'What do you want to eat?' },
      ],
      fillBlanks: [
        { before: '我', after: '喝水。', answer: '想', choices: ['想', '是', '几'], en: 'I would like to drink water.' },
        { before: '你', after: '吃什么？', answer: '要', choices: ['要', '有', '个'], en: 'What do you want to eat?' },
        { before: '我要吃米', after: '。', answer: '饭', choices: ['饭', '菜', '茶'], en: 'I want to eat rice.' },
      ],
      tiles: [
        { parts: ['我', '想', '喝', '茶'], en: 'I would like to drink tea.' },
        { parts: ['你', '要', '吃', '什么'], en: 'What do you want to eat?' },
      ],
    },
    sentences: [
      { cn: '我想喝茶。', py: 'Wǒ xiǎng hē chá.', en: 'I would like to drink tea.' },
      { cn: '你要吃什么？', py: 'Nǐ yào chī shénme?', en: 'What do you want to eat?' },
      { cn: '我要吃米饭。', py: 'Wǒ yào chī mǐfàn.', en: 'I want to eat rice.' },
      { cn: '苹果是水果。', py: 'Píngguǒ shì shuǐguǒ.', en: 'An apple is a fruit.' },
    ],
  },
  {
    id: 'u8', title: 'Dates', icon: '📅', hsk: 1,
    words: ['jintian', 'mingtian', 'zuotian', 'nian', 'yue', 'hao4', 'xingqi', 'tian', 'xianzai', 'shihou'],
    hanzi: ['天', '今', '年', '月'],
    grammar: {
      name: 'Dates: 月, 号, 星期',
      intro: 'Chinese dates go big → small: year 年, month 月, date 号. May 10th = 五月十号. Weekdays are numbered: 星期一 = Monday, 星期二 = Tuesday… Ask with <b>几</b>: 今天几号? 星期几?',
      examples: [
        { cn: '今天五月十号。', py: 'Jīntiān wǔ yuè shí hào.', en: 'Today is May 10th.' },
        { cn: '明天是星期一。', py: 'Míngtiān shì xīngqīyī.', en: 'Tomorrow is Monday.' },
      ],
      fillBlanks: [
        { before: '今天几', after: '？', answer: '号', choices: ['号', '月', '年'], en: "What's the date today?" },
        { before: '明天是星期', after: '。', answer: '一', choices: ['一', '号', '月'], en: 'Tomorrow is Monday.' },
        { before: '现在是几', after: '？', answer: '月', choices: ['月', '个', '天'], en: 'What month is it now?' },
      ],
      tiles: [
        { parts: ['今天', '五', '月', '十', '号'], en: 'Today is May 10th.' },
        { parts: ['明天', '是', '星期', '一'], en: 'Tomorrow is Monday.' },
      ],
    },
    sentences: [
      { cn: '今天几号？', py: 'Jīntiān jǐ hào?', en: "What's the date today?" },
      { cn: '今天五月十号。', py: 'Jīntiān wǔ yuè shí hào.', en: 'Today is May 10th.' },
      { cn: '明天是星期一。', py: 'Míngtiān shì xīngqīyī.', en: 'Tomorrow is Monday.' },
      { cn: '现在是几月？', py: 'Xiànzài shì jǐ yuè?', en: 'What month is it now?' },
    ],
  },
  {
    id: 'u9', title: 'Clock & Routine', icon: '🕐', hsk: 1,
    words: ['dian', 'fenzhong', 'shangwu', 'zhongwu', 'xiawu', 'wanshang', 'shuijiao', 'dianying', 'kan'],
    hanzi: ['点', '分', '午', '晚'],
    grammar: {
      name: 'Telling time with 点',
      intro: '<b>三点</b> = 3 o\'clock. Ask <b>几点？</b> = "what time?" Time words come BEFORE the verb: 我晚上看电影 = "I in-the-evening watch movies" — never at the end like English!',
      examples: [
        { cn: '现在几点？', py: 'Xiànzài jǐ diǎn?', en: 'What time is it now?' },
        { cn: '我晚上看电影。', py: 'Wǒ wǎnshang kàn diànyǐng.', en: 'I watch a movie in the evening.' },
      ],
      fillBlanks: [
        { before: '现在几', after: '？', answer: '点', choices: ['点', '号', '月'], en: 'What time is it now?' },
        { before: '我晚上看', after: '。', answer: '电影', choices: ['电影', '睡觉', '上午'], en: 'I watch a movie in the evening.' },
        { before: '你几点', after: '觉？', answer: '睡', choices: ['睡', '看', '点'], en: 'What time do you go to sleep?' },
      ],
      tiles: [
        { parts: ['现在', '三', '点'], en: "It's three o'clock now." },
        { parts: ['我', '晚上', '看', '电影'], en: 'I watch a movie in the evening.' },
      ],
    },
    sentences: [
      { cn: '现在几点？', py: 'Xiànzài jǐ diǎn?', en: 'What time is it now?' },
      { cn: '现在三点。', py: 'Xiànzài sān diǎn.', en: "It's three o'clock." },
      { cn: '我晚上看电影。', py: 'Wǒ wǎnshang kàn diànyǐng.', en: 'I watch a movie in the evening.' },
      { cn: '你几点睡觉？', py: 'Nǐ jǐ diǎn shuìjiào?', en: 'What time do you go to sleep?' },
    ],
  },
  {
    id: 'u10', title: 'Places', icon: '📍', hsk: 1,
    words: ['zai', 'nar', 'zher', 'nar4', 'xuexiao', 'yiyuan', 'shangdian', 'fandian', 'beijing', 'li'],
    hanzi: ['在', '哪', '里', '学'],
    grammar: {
      name: '在 — being somewhere',
      intro: '<b>在 zài</b> = "to be at/in". 我在学校 = I\'m at school. Ask "where" with <b>哪儿 nǎr</b>: 你在哪儿? Add <b>里</b> for "inside": 家里 = at home (in the house).',
      examples: [
        { cn: '我在学校。', py: 'Wǒ zài xuéxiào.', en: "I'm at school." },
        { cn: '医院在哪儿？', py: 'Yīyuàn zài nǎr?', en: 'Where is the hospital?' },
      ],
      fillBlanks: [
        { before: '你', after: '哪儿？', answer: '在', choices: ['在', '是', '有'], en: 'Where are you?' },
        { before: '我在学', after: '。', answer: '校', choices: ['校', '生', '家'], en: "I'm at school." },
        { before: '妈妈在家', after: '。', answer: '里', choices: ['里', '儿', '个'], en: 'Mom is at home.' },
      ],
      tiles: [
        { parts: ['你', '在', '哪儿'], en: 'Where are you?' },
        { parts: ['我', '在', '学校', '里'], en: "I'm inside the school." },
      ],
    },
    sentences: [
      { cn: '你在哪儿？', py: 'Nǐ zài nǎr?', en: 'Where are you?' },
      { cn: '我在学校。', py: 'Wǒ zài xuéxiào.', en: "I'm at school." },
      { cn: '医院在哪儿？', py: 'Yīyuàn zài nǎr?', en: 'Where is the hospital?' },
      { cn: '妈妈在家里。', py: 'Māma zài jiā li.', en: 'Mom is at home.' },
    ],
  },
  {
    id: 'u11', title: 'Doing Verbs', icon: '💪', hsk: 1,
    words: ['qu', 'lai', 'hui2', 'zuo4', 'gongzuo', 'ting', 'shuo', 'du', 'xie'],
    hanzi: ['去', '来', '回', '写'],
    grammar: {
      name: 'Verb + place, verb + object',
      intro: 'Movement verbs take the place right after: <b>去学校</b> = go to school, <b>回家</b> = return home, <b>来我家</b> = come to my home. No "to" needed — the verb does all the work.',
      examples: [
        { cn: '我去学校。', py: 'Wǒ qù xuéxiào.', en: 'I go to school.' },
        { cn: '你说什么？', py: 'Nǐ shuō shénme?', en: 'What are you saying?' },
      ],
      fillBlanks: [
        { before: '我', after: '学校。', answer: '去', choices: ['去', '来', '写'], en: 'I go to school.' },
        { before: '他', after: '家。', answer: '回', choices: ['回', '听', '说'], en: 'He returns home.' },
        { before: '你', after: '什么？', answer: '说', choices: ['说', '吃', '喝'], en: 'What are you saying?' },
      ],
      tiles: [
        { parts: ['我', '去', '学校'], en: 'I go to school.' },
        { parts: ['爸爸', '在', '工作'], en: 'Dad is at work.' },
      ],
    },
    sentences: [
      { cn: '我去学校。', py: 'Wǒ qù xuéxiào.', en: 'I go to school.' },
      { cn: '他回家。', py: 'Tā huí jiā.', en: 'He goes back home.' },
      { cn: '爸爸在工作。', py: 'Bàba zài gōngzuò.', en: 'Dad is working.' },
      { cn: '你说什么？', py: 'Nǐ shuō shénme?', en: 'What are you saying?' },
    ],
  },
  {
    id: 'u12', title: 'Weather & Feelings', icon: '☀️', hsk: 1,
    words: ['tianqi', 'xiayu', 're', 'leng', 'bu', 'ye', 'dou', 'zenmeyang', 'xihuan'],
    hanzi: ['不', '也', '热', '冷'],
    grammar: {
      name: '很 + adjective, 不 + anything',
      intro: 'Adjectives don\'t need 是! Say <b>今天很热</b> ("today very hot") — the 很 glues it together. Negate almost anything with <b>不 bù</b>: 我不喜欢下雨 = I don\'t like rain. <b>都</b> = all, <b>也</b> = also.',
      examples: [
        { cn: '今天很热。', py: 'Jīntiān hěn rè.', en: "It's very hot today." },
        { cn: '我不喜欢下雨。', py: 'Wǒ bù xǐhuan xià yǔ.', en: "I don't like rain." },
      ],
      fillBlanks: [
        { before: '今天', after: '热。', answer: '很', choices: ['很', '不', '都'], en: "It's very hot today." },
        { before: '我', after: '喜欢下雨。', answer: '不', choices: ['不', '很', '也'], en: "I don't like rain." },
        { before: '我们', after: '很好。', answer: '都', choices: ['都', '不', '吗'], en: 'We are all fine.' },
      ],
      tiles: [
        { parts: ['今天', '天气', '怎么样'], en: "How's the weather today?" },
        { parts: ['我', '不', '喜欢', '下雨'], en: "I don't like rain." },
      ],
    },
    sentences: [
      { cn: '今天天气怎么样？', py: 'Jīntiān tiānqì zěnmeyàng?', en: "How's the weather today?" },
      { cn: '今天很热。', py: 'Jīntiān hěn rè.', en: "It's very hot today." },
      { cn: '我不喜欢下雨。', py: 'Wǒ bù xǐhuan xià yǔ.', en: "I don't like rain." },
      { cn: '我们都很好。', py: 'Wǒmen dōu hěn hǎo.', en: 'We are all fine.' },
    ],
  },
  {
    id: 'u13', title: 'Shopping', icon: '🛍️', hsk: 1,
    words: ['mai', 'qian', 'duoshao', 'kuai', 'dongxi', 'yifu', 'tai', 'da', 'xiao', 'le'],
    hanzi: ['买', '钱', '大', '小'],
    grammar: {
      name: '多少钱? & 太…了!',
      intro: 'Ask prices with <b>多少钱</b> = "how much money?" Answer in <b>块</b> (spoken word for yuan). And exclaim with the sandwich <b>太…了</b>: 太大了! = "too big!" 太好了! = "great!"',
      examples: [
        { cn: '这个多少钱？', py: 'Zhège duōshao qián?', en: 'How much is this?' },
        { cn: '这个太大了！', py: 'Zhège tài dà le!', en: 'This is too big!' },
      ],
      fillBlanks: [
        { before: '这个多少', after: '？', answer: '钱', choices: ['钱', '块', '买'], en: 'How much is this?' },
        { before: '这个太', after: '了！', answer: '大', choices: ['大', '小', '块'], en: 'This is too big!' },
        { before: '我要', after: '衣服。', answer: '买', choices: ['买', '看', '吃'], en: 'I want to buy clothes.' },
      ],
      tiles: [
        { parts: ['这个', '多少', '钱'], en: 'How much is this?' },
        { parts: ['我', '要', '买', '衣服'], en: 'I want to buy clothes.' },
      ],
    },
    sentences: [
      { cn: '这个多少钱？', py: 'Zhège duōshao qián?', en: 'How much is this?' },
      { cn: '十块钱。', py: 'Shí kuài qián.', en: 'Ten kuai.' },
      { cn: '这个太大了！', py: 'Zhège tài dà le!', en: 'This is too big!' },
      { cn: '我要买衣服。', py: 'Wǒ yào mǎi yīfu.', en: 'I want to buy clothes.' },
    ],
  },
  {
    id: 'u14', title: 'Getting Around', icon: '🚕', hsk: 1,
    words: ['che', 'chuzuche', 'feiji', 'huochezhan', 'zuo_sit', 'kai', 'zenme'],
    hanzi: ['车', '坐', '开', '飞'],
    grammar: {
      name: '坐 & 开 — how you travel',
      intro: 'You <b>坐</b> (sit/ride) transport someone else drives, and <b>开</b> (drive) your own. The travel method goes before 去: <b>我坐飞机去北京</b> = "I by-plane go to Beijing". Ask how with <b>怎么</b>.',
      examples: [
        { cn: '我坐飞机去北京。', py: 'Wǒ zuò fēijī qù Běijīng.', en: 'I fly to Beijing.' },
        { cn: '你怎么去学校？', py: 'Nǐ zěnme qù xuéxiào?', en: 'How do you get to school?' },
      ],
      fillBlanks: [
        { before: '我', after: '出租车去学校。', answer: '坐', choices: ['坐', '吃', '买'], en: 'I take a taxi to school.' },
        { before: '你怎么', after: '学校？', answer: '去', choices: ['去', '吃', '喝'], en: 'How do you get to school?' },
        { before: '我坐飞机去北', after: '。', answer: '京', choices: ['京', '月', '车'], en: 'I fly to Beijing.' },
      ],
      tiles: [
        { parts: ['我', '坐', '出租车', '去', '学校'], en: 'I take a taxi to school.' },
        { parts: ['爸爸', '开', '车'], en: 'Dad drives.' },
      ],
    },
    sentences: [
      { cn: '我坐出租车去饭店。', py: 'Wǒ zuò chūzūchē qù fàndiàn.', en: 'I take a taxi to the restaurant.' },
      { cn: '你怎么去学校？', py: 'Nǐ zěnme qù xuéxiào?', en: 'How do you get to school?' },
      { cn: '我坐飞机去北京。', py: 'Wǒ zuò fēijī qù Běijīng.', en: 'I fly to Beijing.' },
      { cn: '爸爸开车。', py: 'Bàba kāi chē.', en: 'Dad drives.' },
    ],
  },
  {
    id: 'u15', title: 'Can Do It!', icon: '🎓', hsk: 1,
    words: ['hui4', 'neng', 'hanyu', 'dianhua', 'da3', 'kanjian', 'xiansheng', 'xiaojie', 'yisheng'],
    hanzi: ['会', '能', '电', '话'],
    grammar: {
      name: '会 & 能 — I can!',
      intro: '<b>会 huì</b> = can, because you learned it (languages, skills): 我会说汉语. <b>能 néng</b> = can, because it\'s possible right now: 你能来吗? = "Can you come?" You finished HSK 1 — 太好了!',
      examples: [
        { cn: '我会说汉语。', py: 'Wǒ huì shuō Hànyǔ.', en: 'I can speak Chinese.' },
        { cn: '你能来我家吗？', py: 'Nǐ néng lái wǒ jiā ma?', en: 'Can you come to my home?' },
      ],
      fillBlanks: [
        { before: '我', after: '说汉语。', answer: '会', choices: ['会', '吗', '有'], en: 'I can speak Chinese (I learned it).' },
        { before: '你', after: '来我家吗？', answer: '能', choices: ['能', '是', '吗'], en: 'Can you come to my home?' },
        { before: '他是医', after: '。', answer: '生', choices: ['生', '院', '校'], en: 'He is a doctor.' },
      ],
      tiles: [
        { parts: ['我', '会', '说', '汉语'], en: 'I can speak Chinese.' },
        { parts: ['你', '能', '来', '吗'], en: 'Can you come?' },
      ],
    },
    sentences: [
      { cn: '我会说汉语。', py: 'Wǒ huì shuō Hànyǔ.', en: 'I can speak Chinese.' },
      { cn: '你能来我家吗？', py: 'Nǐ néng lái wǒ jiā ma?', en: 'Can you come to my home?' },
      { cn: '王先生打电话。', py: 'Wáng xiānsheng dǎ diànhuà.', en: 'Mr. Wang is making a phone call.' },
      { cn: '我看见王医生了。', py: 'Wǒ kànjiàn Wáng yīshēng le.', en: 'I saw Dr. Wang.' },
    ],
  },
];
