// Mandarin Journey — HSK 3 word-expansion stage (auto-generated units)
// Source: drkameleon/complete-hsk-vocabulary (old-HSK 3 exclusive list), frequency-ordered.

Object.assign(window.WORDS, {
  h3_31_0: {"cn": "啊", "py": "ā", "pyPlain": "a", "en": "interjection of surprise; Ah!"},
  h3_31_1: {"cn": "把", "py": "bǎ", "pyPlain": "ba", "en": "to hold; to grasp; to hold a baby in position to help it…"},
  h3_31_2: {"cn": "被", "py": "bèi", "pyPlain": "bei", "en": "quilt; to cover (with)"},
  h3_31_3: {"cn": "自己", "py": "zì jǐ", "pyPlain": "ziji", "en": "oneself; one's own"},
  h3_31_4: {"cn": "用", "py": "yòng", "pyPlain": "yong", "en": "to use; to employ"},
  h3_31_5: {"cn": "如果", "py": "rú guǒ", "pyPlain": "ruguo", "en": "if; in case"},
  h3_31_6: {"cn": "又", "py": "yòu", "pyPlain": "you", "en": "(once) again; also"},
  h3_31_7: {"cn": "只", "py": "zhǐ", "pyPlain": "zhi", "en": "only; merely"},
  h3_31_8: {"cn": "更", "py": "gēng", "pyPlain": "geng", "en": "to change or replace; to experience"},
  h3_31_9: {"cn": "需要", "py": "xū yào", "pyPlain": "xuyao", "en": "to need; to want; to demand; to require; needs"},
  h3_31_10: {"cn": "地", "py": "de", "pyPlain": "de", "en": "-ly; structural particle: used before a verb or…"},
  h3_31_11: {"cn": "才", "py": "cái", "pyPlain": "cai", "en": "ability; talent; sb of a certain type"},
  h3_32_0: {"cn": "跟", "py": "gēn", "pyPlain": "gen", "en": "heel; to follow closely"},
  h3_32_1: {"cn": "像", "py": "xiàng", "pyPlain": "xiang", "en": "to resemble; to be like"},
  h3_32_2: {"cn": "还是", "py": "hái shi", "pyPlain": "haishi", "en": "still (as before); had better"},
  h3_32_3: {"cn": "认为", "py": "rèn wéi", "pyPlain": "renwei", "en": "to believe; to think; to consider; to feel"},
  h3_32_4: {"cn": "应该", "py": "yīng gāi", "pyPlain": "yinggai", "en": "ought to; should"},
  h3_32_5: {"cn": "带", "py": "dài", "pyPlain": "dai", "en": "band; belt"},
  h3_32_6: {"cn": "位", "py": "wèi", "pyPlain": "wei", "en": "position; location"},
  h3_32_7: {"cn": "种", "py": "zhǒng", "pyPlain": "zhong", "en": "seed; species"},
  h3_32_8: {"cn": "发现", "py": "fā xiàn", "pyPlain": "faxian", "en": "to notice; to become aware of; to discover; to find; to…"},
  h3_32_9: {"cn": "一定", "py": "yī dìng", "pyPlain": "yiding", "en": "surely; certainly"},
  h3_32_10: {"cn": "一直", "py": "yī zhí", "pyPlain": "yizhi", "en": "straight (in a straight line); continuously; always; all…"},
  h3_32_11: {"cn": "为了", "py": "wèi le", "pyPlain": "weile", "en": "for; for the purpose of; in order to"},
  h3_33_0: {"cn": "一样", "py": "yī yàng", "pyPlain": "yiyang", "en": "same; like"},
  h3_33_1: {"cn": "世界", "py": "shì jiè", "pyPlain": "shijie", "en": "world"},
  h3_33_2: {"cn": "而且", "py": "ér qiě", "pyPlain": "erqie", "en": "(not only ...) but also; moreover"},
  h3_33_3: {"cn": "重要", "py": "zhòng yào", "pyPlain": "zhongyao", "en": "important; significant"},
  h3_33_4: {"cn": "必须", "py": "bì xū", "pyPlain": "bixu", "en": "to have to; must"},
  h3_33_5: {"cn": "地方", "py": "dì fāng", "pyPlain": "difang", "en": "region; regional (away from the central administration)"},
  h3_33_6: {"cn": "老", "py": "lǎo", "pyPlain": "lao", "en": "prefix used before the surname of a person or a numeral…"},
  h3_33_7: {"cn": "其他", "py": "qí tā", "pyPlain": "qita", "en": "other; (sth or sb) else"},
  h3_33_8: {"cn": "比赛", "py": "bǐ sài", "pyPlain": "bisai", "en": "competition (sports etc); match"},
  h3_33_9: {"cn": "然后", "py": "rán hòu", "pyPlain": "ranhou", "en": "then; after that; afterwards"},
  h3_33_10: {"cn": "担心", "py": "dān xīn", "pyPlain": "danxin", "en": "anxious; worried"},
  h3_33_11: {"cn": "条", "py": "tiáo", "pyPlain": "tiao", "en": "strip; item"},
  h3_34_0: {"cn": "放", "py": "fàng", "pyPlain": "fang", "en": "to put; to place"},
  h3_34_1: {"cn": "拿", "py": "ná", "pyPlain": "na", "en": "old variant of 拿"},
  h3_34_2: {"cn": "先", "py": "xiān", "pyPlain": "xian", "en": "early; prior"},
  h3_34_3: {"cn": "关系", "py": "guān xi", "pyPlain": "guanxi", "en": "relation; relationship"},
  h3_34_4: {"cn": "出现", "py": "chū xiàn", "pyPlain": "chuxian", "en": "to appear; to arise"},
  h3_34_5: {"cn": "了解", "py": "liǎo jiě", "pyPlain": "liaojie", "en": "to understand; to realize"},
  h3_34_6: {"cn": "过去", "py": "guò qù", "pyPlain": "guoqu", "en": "(in the) past; former"},
  h3_34_7: {"cn": "参加", "py": "cān jiā", "pyPlain": "canjia", "en": "to participate; to take part"},
  h3_34_8: {"cn": "国家", "py": "guó jiā", "pyPlain": "guojia", "en": "country; nation; state"},
  h3_34_9: {"cn": "决定", "py": "jué dìng", "pyPlain": "jueding", "en": "to decide (to do something); to resolve"},
  h3_34_10: {"cn": "分", "py": "fēn", "pyPlain": "fen", "en": "to divide; to separate; to distribute; to allocate"},
  h3_34_11: {"cn": "选择", "py": "xuǎn zé", "pyPlain": "xuanze", "en": "to select; to pick"},
  h3_35_0: {"cn": "或者", "py": "huò zhě", "pyPlain": "huozhe", "en": "or; possibly; maybe; perhaps"},
  h3_35_1: {"cn": "机会", "py": "jī huì", "pyPlain": "jihui", "en": "opportunity; chance"},
  h3_35_2: {"cn": "别人", "py": "bié ren", "pyPlain": "bieren", "en": "other people; others; other person"},
  h3_35_3: {"cn": "站", "py": "zhàn", "pyPlain": "zhan", "en": "station; to stand"},
  h3_35_4: {"cn": "使", "py": "shǐ", "pyPlain": "shi", "en": "to make; to cause"},
  h3_35_5: {"cn": "其实", "py": "qí shí", "pyPlain": "qishi", "en": "actually; in fact; really"},
  h3_35_6: {"cn": "以后", "py": "yǐ hòu", "pyPlain": "yihou", "en": "after; later"},
  h3_35_7: {"cn": "要求", "py": "yāo qiú", "pyPlain": "yaoqiu", "en": "to request; to require"},
  h3_35_8: {"cn": "信", "py": "xìn", "pyPlain": "xin", "en": "letter; mail"},
  h3_35_9: {"cn": "当然", "py": "dāng rán", "pyPlain": "dangran", "en": "only natural; as it should be"},
  h3_35_10: {"cn": "接", "py": "jiē", "pyPlain": "jie", "en": "to receive; to answer (the phone)"},
  h3_35_11: {"cn": "相信", "py": "xiāng xìn", "pyPlain": "xiangxin", "en": "to be convinced (that sth is true); to believe; to…"},
  h3_36_0: {"cn": "花", "py": "Huā", "pyPlain": "hua", "en": "surname Hua"},
  h3_36_1: {"cn": "虽然", "py": "suī rán", "pyPlain": "suiran", "en": "although; even though (often used correlatively with 是…"},
  h3_36_2: {"cn": "解决", "py": "jiě jué", "pyPlain": "jiejue", "en": "to solve; to resolve; to settle (a problem); to…"},
  h3_36_3: {"cn": "关于", "py": "guān yú", "pyPlain": "guanyu", "en": "pertaining to; concerning"},
  h3_36_4: {"cn": "完成", "py": "wán chéng", "pyPlain": "wancheng", "en": "to complete; to accomplish"},
  h3_36_5: {"cn": "结束", "py": "jié shù", "pyPlain": "jieshu", "en": "termination; to finish"},
  h3_36_6: {"cn": "努力", "py": "nǔ lì", "pyPlain": "nuli", "en": "to make an effort; to try hard; to strive; hard-working;…"},
  h3_36_7: {"cn": "以前", "py": "yǐ qián", "pyPlain": "yiqian", "en": "before; formerly"},
  h3_36_8: {"cn": "办法", "py": "bàn fǎ", "pyPlain": "banfa", "en": "means; method"},
  h3_36_9: {"cn": "特别", "py": "tè bié", "pyPlain": "tebie", "en": "unusual; special; very; especially; particularly"},
  h3_36_10: {"cn": "难", "py": "nán", "pyPlain": "nan", "en": "difficult (to...); problem"},
  h3_36_11: {"cn": "注意", "py": "zhù yì", "pyPlain": "zhuyi", "en": "to take note of; to pay attention to"},
  h3_37_0: {"cn": "讲", "py": "jiǎng", "pyPlain": "jiang", "en": "to speak; to explain"},
  h3_37_1: {"cn": "离开", "py": "lí kāi", "pyPlain": "likai", "en": "to depart; to leave"},
  h3_37_2: {"cn": "万", "py": "mò", "pyPlain": "mo", "en": "used in 俟"},
  h3_37_3: {"cn": "以为", "py": "yǐ wéi", "pyPlain": "yiwei", "en": "to think (i.e. to take it to be true that ...) (Usually…"},
  h3_37_4: {"cn": "越", "py": "Yuè", "pyPlain": "yue", "en": "generic word for peoples or states of south China or…"},
  h3_37_5: {"cn": "城市", "py": "chéng shì", "pyPlain": "chengshi", "en": "city; town"},
  h3_37_6: {"cn": "影响", "py": "yǐng xiǎng", "pyPlain": "yingxiang", "en": "influence; effect"},
  h3_37_7: {"cn": "游戏", "py": "yóu xì", "pyPlain": "youxi", "en": "game; to play"},
  h3_37_8: {"cn": "马", "py": "Mǎ", "pyPlain": "ma", "en": "abbr. for Malaysia 马来西亚"},
  h3_37_9: {"cn": "比较", "py": "bǐ jiào", "pyPlain": "bijiao", "en": "to compare; to contrast"},
  h3_37_10: {"cn": "最近", "py": "zuì jìn", "pyPlain": "zuijin", "en": "recently; soon"},
  h3_37_11: {"cn": "换", "py": "huàn", "pyPlain": "huan", "en": "to exchange; to change (clothes etc)"},
  h3_38_0: {"cn": "终于", "py": "zhōng yú", "pyPlain": "zhongyu", "en": "at last; in the end"},
  h3_38_1: {"cn": "脸", "py": "liǎn", "pyPlain": "lian", "en": "face"},
  h3_38_2: {"cn": "口", "py": "kǒu", "pyPlain": "kou", "en": "mouth; classifier for things with mouths (people,…"},
  h3_38_3: {"cn": "除了", "py": "chú le", "pyPlain": "chule", "en": "besides; apart from (... also...)"},
  h3_38_4: {"cn": "总是", "py": "zǒng shì", "pyPlain": "zongshi", "en": "always"},
  h3_38_5: {"cn": "双", "py": "Shuāng", "pyPlain": "shuang", "en": "surname Shuang"},
  h3_38_6: {"cn": "突然", "py": "tū rán", "pyPlain": "turan", "en": "sudden; abrupt; unexpected"},
  h3_38_7: {"cn": "段", "py": "Duàn", "pyPlain": "duan", "en": "surname Duan"},
  h3_38_8: {"cn": "检查", "py": "jiǎn chá", "pyPlain": "jiancha", "en": "inspection; to examine"},
  h3_38_9: {"cn": "米", "py": "Mǐ", "pyPlain": "mi", "en": "surname Mi"},
  h3_38_10: {"cn": "容易", "py": "róng yì", "pyPlain": "rongyi", "en": "easy; straightforward; likely; liable to; apt to"},
  h3_38_11: {"cn": "明白", "py": "míng bai", "pyPlain": "mingbai", "en": "clear; obvious"},
  h3_39_0: {"cn": "根据", "py": "gēn jù", "pyPlain": "genju", "en": "according to; based on"},
  h3_39_1: {"cn": "记得", "py": "jì de", "pyPlain": "jide", "en": "to remember"},
  h3_39_2: {"cn": "辆", "py": "liàng", "pyPlain": "liang", "en": "classifier for vehicles"},
  h3_39_3: {"cn": "简单", "py": "jiǎn dān", "pyPlain": "jiandan", "en": "simple; not complicated"},
  h3_39_4: {"cn": "半", "py": "bàn", "pyPlain": "ban", "en": "half; semi-"},
  h3_39_5: {"cn": "愿意", "py": "yuàn yì", "pyPlain": "yuanyi", "en": "to wish; to want"},
  h3_39_6: {"cn": "音乐", "py": "yīn yuè", "pyPlain": "yinyue", "en": "music"},
  h3_39_7: {"cn": "包", "py": "Bāo", "pyPlain": "bao", "en": "surname Bao"},
  h3_39_8: {"cn": "楼", "py": "Lóu", "pyPlain": "lou", "en": "surname Lou"},
  h3_39_9: {"cn": "清楚", "py": "qīng chu", "pyPlain": "qingchu", "en": "clear; distinct"},
  h3_39_10: {"cn": "照片", "py": "zhào piàn", "pyPlain": "zhaopian", "en": "photograph; picture"},
  h3_39_11: {"cn": "银行", "py": "yín háng", "pyPlain": "yinhang", "en": "bank"},
  h3_40_0: {"cn": "故事", "py": "gù shì", "pyPlain": "gushi", "en": "old practice"},
  h3_40_1: {"cn": "一般", "py": "yī bān", "pyPlain": "yiban", "en": "same; ordinary"},
  h3_40_2: {"cn": "可爱", "py": "kě ài", "pyPlain": "keai", "en": "adorable; cute"},
  h3_40_3: {"cn": "新闻", "py": "xīn wén", "pyPlain": "xinwen", "en": "news"},
  h3_40_4: {"cn": "声音", "py": "shēng yīn", "pyPlain": "shengyin", "en": "voice; sound"},
  h3_40_5: {"cn": "马上", "py": "mǎ shàng", "pyPlain": "mashang", "en": "at once; right away"},
  h3_40_6: {"cn": "表示", "py": "biǎo shì", "pyPlain": "biaoshi", "en": "to express; to show"},
  h3_40_7: {"cn": "经过", "py": "jīng guò", "pyPlain": "jingguo", "en": "to pass; to go through"},
  h3_40_8: {"cn": "历史", "py": "lì shǐ", "pyPlain": "lishi", "en": "history"},
  h3_40_9: {"cn": "哭", "py": "kū", "pyPlain": "ku", "en": "to cry; to weep"},
  h3_40_10: {"cn": "敢", "py": "gǎn", "pyPlain": "gan", "en": "to dare; daring"},
  h3_40_11: {"cn": "会议", "py": "huì yì", "pyPlain": "huiyi", "en": "meeting; conference"},
  h3_41_0: {"cn": "经常", "py": "jīng cháng", "pyPlain": "jingchang", "en": "frequently; constantly; regularly; often; day-to-day;…"},
  h3_41_1: {"cn": "低", "py": "dī", "pyPlain": "di", "en": "low; beneath"},
  h3_41_2: {"cn": "节目", "py": "jié mù", "pyPlain": "jiemu", "en": "program; item (on a program)"},
  h3_41_3: {"cn": "健康", "py": "jiàn kāng", "pyPlain": "jiankang", "en": "health; healthy"},
  h3_41_4: {"cn": "作用", "py": "zuò yòng", "pyPlain": "zuoyong", "en": "to act on; to affect"},
  h3_41_5: {"cn": "西", "py": "Xī", "pyPlain": "xi", "en": "the West; abbr. for Spain 牙"},
  h3_41_6: {"cn": "差", "py": "chā", "pyPlain": "cha", "en": "difference; discrepancy; (math.) difference (amount…"},
  h3_41_7: {"cn": "结婚", "py": "jié hūn", "pyPlain": "jiehun", "en": "to marry; to get married"},
  h3_41_8: {"cn": "短", "py": "duǎn", "pyPlain": "duan", "en": "short; brief"},
  h3_41_9: {"cn": "同意", "py": "tóng yì", "pyPlain": "tongyi", "en": "to agree; to consent"},
  h3_41_10: {"cn": "教", "py": "Jiào", "pyPlain": "jiao", "en": "surname Jiao"},
  h3_41_11: {"cn": "几乎", "py": "jī hū", "pyPlain": "jihu", "en": "almost; nearly; practically"},
  h3_42_0: {"cn": "附近", "py": "fù jìn", "pyPlain": "fujin", "en": "nearby; neighboring; (in the) vicinity (of); neighborhood"},
  h3_42_1: {"cn": "认真", "py": "rèn zhēn", "pyPlain": "renzhen", "en": "conscientious; earnest"},
  h3_42_2: {"cn": "脚", "py": "jiǎo", "pyPlain": "jiao", "en": "foot; leg (of an animal or an object)"},
  h3_42_3: {"cn": "主要", "py": "zhǔ yào", "pyPlain": "zhuyao", "en": "main; principal"},
  h3_42_4: {"cn": "遇到", "py": "yù dào", "pyPlain": "yudao", "en": "to meet; to run into; to come across"},
  h3_42_5: {"cn": "年轻", "py": "nián qīng", "pyPlain": "nianqing", "en": "young"},
  h3_42_6: {"cn": "久", "py": "jiǔ", "pyPlain": "jiu", "en": "(long) time; (long) duration of time"},
  h3_42_7: {"cn": "画", "py": "huà", "pyPlain": "hua", "en": "to draw; to paint; picture; painting"},
  h3_42_8: {"cn": "表演", "py": "biǎo yǎn", "pyPlain": "biaoyan", "en": "play; show"},
  h3_42_9: {"cn": "关", "py": "Guān", "pyPlain": "guan", "en": "surname Guan"},
  h3_42_10: {"cn": "刚才", "py": "gāng cái", "pyPlain": "gangcai", "en": "just now; a moment ago"},
  h3_42_11: {"cn": "办公室", "py": "bàn gōng shì", "pyPlain": "bangongshi", "en": "office; business premises"},
  h3_43_0: {"cn": "环境", "py": "huán jìng", "pyPlain": "huanjing", "en": "environment; circumstances"},
  h3_43_1: {"cn": "关心", "py": "guān xīn", "pyPlain": "guanxin", "en": "to be concerned about; to care about"},
  h3_43_2: {"cn": "祝", "py": "Zhù", "pyPlain": "zhu", "en": "surname Zhu"},
  h3_43_3: {"cn": "层", "py": "céng", "pyPlain": "ceng", "en": "to pile on top of one another; layer; stratum"},
  h3_43_4: {"cn": "腿", "py": "tuǐ", "pyPlain": "tui", "en": "leg"},
  h3_43_5: {"cn": "班", "py": "Bān", "pyPlain": "ban", "en": "surname Ban"},
  h3_43_6: {"cn": "坏", "py": "huài", "pyPlain": "huai", "en": "bad; spoiled"},
  h3_43_7: {"cn": "一边", "py": "yī biān", "pyPlain": "yibian", "en": "one side; either side"},
  h3_43_8: {"cn": "鞋", "py": "xié", "pyPlain": "xie", "en": "shoe"},
  h3_43_9: {"cn": "习惯", "py": "xí guàn", "pyPlain": "xiguan", "en": "habit; custom"},
  h3_43_10: {"cn": "变化", "py": "biàn huà", "pyPlain": "bianhua", "en": "(intransitive) to change; to vary; change; variation"},
  h3_43_11: {"cn": "周末", "py": "zhōu mò", "pyPlain": "zhoumo", "en": "weekend"},
  h3_44_0: {"cn": "忘记", "py": "wàng jì", "pyPlain": "wangji", "en": "to forget"},
  h3_44_1: {"cn": "打算", "py": "dǎ suàn", "pyPlain": "dasuan", "en": "to plan; to intend"},
  h3_44_2: {"cn": "极", "py": "jí", "pyPlain": "ji", "en": "extremely; pole (geography, physics)"},
  h3_44_3: {"cn": "小心", "py": "xiǎo xīn", "pyPlain": "xiaoxin", "en": "to be careful; to take care"},
  h3_44_4: {"cn": "举行", "py": "jǔ xíng", "pyPlain": "juxing", "en": "to hold (a meeting, ceremony etc)"},
  h3_44_5: {"cn": "动物", "py": "dòng wù", "pyPlain": "dongwu", "en": "animal"},
  h3_44_6: {"cn": "饿", "py": "è", "pyPlain": "e", "en": "to be hungry; hungry"},
  h3_44_7: {"cn": "树", "py": "shù", "pyPlain": "shu", "en": "tree; to cultivate"},
  h3_44_8: {"cn": "水平", "py": "shuǐ píng", "pyPlain": "shuiping", "en": "level (of achievement etc); standard"},
  h3_44_9: {"cn": "借", "py": "jiè", "pyPlain": "jie", "en": "to lend; to borrow"},
  h3_44_10: {"cn": "东", "py": "Dōng", "pyPlain": "dong", "en": "surname Dong"},
  h3_44_11: {"cn": "头发", "py": "tóu fa", "pyPlain": "toufa", "en": "hair (on the head)"},
  h3_45_0: {"cn": "害怕", "py": "hài pà", "pyPlain": "haipa", "en": "to be afraid; to be scared"},
  h3_45_1: {"cn": "鸟", "py": "diǎo", "pyPlain": "diao", "en": "penis"},
  h3_45_2: {"cn": "蓝", "py": "Lán", "pyPlain": "lan", "en": "surname Lan"},
  h3_45_3: {"cn": "照顾", "py": "zhào gu", "pyPlain": "zhaogu", "en": "to take care of; to show consideration"},
  h3_45_4: {"cn": "文化", "py": "wén huà", "pyPlain": "wenhua", "en": "culture; civilization"},
  h3_45_5: {"cn": "疼", "py": "téng", "pyPlain": "teng", "en": "(it) hurts; sore; to love dearly"},
  h3_45_6: {"cn": "奇怪", "py": "qí guài", "pyPlain": "qiguai", "en": "strange; odd"},
  h3_45_7: {"cn": "礼物", "py": "lǐ wù", "pyPlain": "liwu", "en": "gift; present"},
  h3_45_8: {"cn": "南", "py": "Nán", "pyPlain": "nan", "en": "surname Nan"},
  h3_45_9: {"cn": "提高", "py": "tí gāo", "pyPlain": "tigao", "en": "to raise; to increase"},
  h3_45_10: {"cn": "满意", "py": "mǎn yì", "pyPlain": "manyi", "en": "satisfied; pleased"},
  h3_45_11: {"cn": "旧", "py": "jiù", "pyPlain": "jiu", "en": "old; opposite: new 新"},
  h3_46_0: {"cn": "司机", "py": "sī jī", "pyPlain": "siji", "en": "chauffeur; driver"},
  h3_46_1: {"cn": "黄", "py": "Huáng", "pyPlain": "huang", "en": "surname Huang or Hwang"},
  h3_46_2: {"cn": "经理", "py": "jīng lǐ", "pyPlain": "jingli", "en": "manager; director"},
  h3_46_3: {"cn": "兴趣", "py": "xìng qù", "pyPlain": "xingqu", "en": "interest (desire to know about sth); interest (thing in…"},
  h3_46_4: {"cn": "帮忙", "py": "bāng máng", "pyPlain": "bangmang", "en": "to help; to lend a hand"},
  h3_46_5: {"cn": "电子", "py": "diàn zǐ", "pyPlain": "dianzi", "en": "electronic; electron (particle physics)"},
  h3_46_6: {"cn": "见面", "py": "jiàn miàn", "pyPlain": "jianmian", "en": "to meet; to see each other"},
  h3_46_7: {"cn": "成绩", "py": "chéng jì", "pyPlain": "chengji", "en": "achievement; performance records"},
  h3_46_8: {"cn": "中间", "py": "zhōng jiān", "pyPlain": "zhongjian", "en": "the middle; the inside; in the middle; within; between;…"},
  h3_46_9: {"cn": "聪明", "py": "cōng ming", "pyPlain": "congming", "en": "intelligent; clever"},
  h3_46_10: {"cn": "多么", "py": "duō me", "pyPlain": "duome", "en": "how (wonderful etc); what (a great idea etc)"},
  h3_46_11: {"cn": "灯", "py": "dēng", "pyPlain": "deng", "en": "lamp; light"},
  h3_47_0: {"cn": "太阳", "py": "tài yang", "pyPlain": "taiyang", "en": "sun; abbr. for 太阳穴"},
  h3_47_1: {"cn": "方便", "py": "fāng biàn", "pyPlain": "fangbian", "en": "convenient; suitable"},
  h3_47_2: {"cn": "糖", "py": "táng", "pyPlain": "tang", "en": "sugar; sweets"},
  h3_47_3: {"cn": "相同", "py": "xiāng tóng", "pyPlain": "xiangtong", "en": "identical; same"},
  h3_47_4: {"cn": "生气", "py": "shēng qì", "pyPlain": "shengqi", "en": "to get angry; to take offense"},
  h3_47_5: {"cn": "公园", "py": "gōng yuán", "pyPlain": "gongyuan", "en": "park (for public recreation)"},
  h3_47_6: {"cn": "热情", "py": "rè qíng", "pyPlain": "reqing", "en": "cordial; enthusiastic"},
  h3_47_7: {"cn": "一会儿", "py": "yī huì r", "pyPlain": "yihuir", "en": "a moment; a while"},
  h3_47_8: {"cn": "骑", "py": "jì", "pyPlain": "ji", "en": "(Tw) saddle horse; mounted soldier"},
  h3_47_9: {"cn": "河", "py": "hé", "pyPlain": "he", "en": "river"},
  h3_47_10: {"cn": "搬", "py": "bān", "pyPlain": "ban", "en": "to move (i.e. relocate oneself); to move (sth relatively…"},
  h3_47_11: {"cn": "同事", "py": "tóng shì", "pyPlain": "tongshi", "en": "colleague; co-worker"},
  h3_48_0: {"cn": "舒服", "py": "shū fu", "pyPlain": "shufu", "en": "comfortable; feeling well"},
  h3_48_1: {"cn": "体育", "py": "tǐ yù", "pyPlain": "tiyu", "en": "sports; physical education"},
  h3_48_2: {"cn": "角", "py": "Jué", "pyPlain": "jue", "en": "surname Jue"},
  h3_48_3: {"cn": "胖", "py": "pán", "pyPlain": "pan", "en": "healthy; at ease"},
  h3_48_4: {"cn": "干净", "py": "gān jìng", "pyPlain": "ganjing", "en": "clean; neat"},
  h3_48_5: {"cn": "放心", "py": "fàng xīn", "pyPlain": "fangxin", "en": "to feel relieved; to feel reassured"},
  h3_48_6: {"cn": "草", "py": "cǎo", "pyPlain": "cao", "en": "variant of 草"},
  h3_48_7: {"cn": "甜", "py": "tián", "pyPlain": "tian", "en": "sweet"},
  h3_48_8: {"cn": "安静", "py": "ān jìng", "pyPlain": "anjing", "en": "quiet; peaceful"},
  h3_48_9: {"cn": "作业", "py": "zuò yè", "pyPlain": "zuoye", "en": "school assignment; homework"},
  h3_48_10: {"cn": "瘦", "py": "shòu", "pyPlain": "shou", "en": "thin; to lose weight"},
  h3_48_11: {"cn": "绿", "py": "lǜ", "pyPlain": "lv", "en": "green; (slang) (derived from 绿帽子) to cheat on (one's…"},
  h3_49_0: {"cn": "啤酒", "py": "pí jiǔ", "pyPlain": "pijiu", "en": "beer (loanword)"},
  h3_49_1: {"cn": "蛋糕", "py": "dàn gāo", "pyPlain": "dangao", "en": "cake"},
  h3_49_2: {"cn": "新鲜", "py": "xīn xiān", "pyPlain": "xinxian", "en": "fresh (experience, food etc); freshness"},
  h3_49_3: {"cn": "难过", "py": "nán guò", "pyPlain": "nanguo", "en": "to feel sad; to feel unwell"},
  h3_49_4: {"cn": "客人", "py": "kè rén", "pyPlain": "keren", "en": "visitor; guest"},
  h3_49_5: {"cn": "奶奶", "py": "nǎi nai", "pyPlain": "nainai", "en": "(informal) grandma (paternal grandmother); (respectful)…"},
  h3_49_6: {"cn": "碗", "py": "wǎn", "pyPlain": "wan", "en": "variant of 碗"},
  h3_49_7: {"cn": "数学", "py": "shù xué", "pyPlain": "shuxue", "en": "mathematics; mathematical"},
  h3_49_8: {"cn": "地铁", "py": "dì tiě", "pyPlain": "ditie", "en": "underground railway; subway; subway train"},
  h3_49_9: {"cn": "刷", "py": "shuā", "pyPlain": "shua", "en": "to brush; to paint"},
  h3_49_10: {"cn": "厨房", "py": "chú fáng", "pyPlain": "chufang", "en": "kitchen"},
  h3_49_11: {"cn": "练习", "py": "liàn xí", "pyPlain": "lianxi", "en": "to practice; exercise"},
  h3_50_0: {"cn": "爷爷", "py": "yé ye", "pyPlain": "yeye", "en": "(coll.) father's father; paternal grandfather"},
  h3_50_1: {"cn": "云", "py": "yún", "pyPlain": "yun", "en": "(classical) to say"},
  h3_50_2: {"cn": "邻居", "py": "lín jū", "pyPlain": "linju", "en": "neighbor; next door"},
  h3_50_3: {"cn": "校长", "py": "xiào zhǎng", "pyPlain": "xiaozhang", "en": "(college, university) president; headmaster"},
  h3_50_4: {"cn": "花园", "py": "huā yuán", "pyPlain": "huayuan", "en": "garden"},
  h3_50_5: {"cn": "耳朵", "py": "ěr duo", "pyPlain": "erduo", "en": "ear; handle (on a cup)"},
  h3_50_6: {"cn": "节日", "py": "jié rì", "pyPlain": "jieri", "en": "holiday; festival"},
  h3_50_7: {"cn": "鼻子", "py": "bí zi", "pyPlain": "bizi", "en": "nose"},
  h3_50_8: {"cn": "叔叔", "py": "shū shu", "pyPlain": "shushu", "en": "father's younger brother; uncle"},
  h3_50_9: {"cn": "洗澡", "py": "xǐ zǎo", "pyPlain": "xizao", "en": "to bathe; to take a shower"},
  h3_50_10: {"cn": "地图", "py": "dì tú", "pyPlain": "ditu", "en": "map"},
  h3_50_11: {"cn": "帽子", "py": "mào zi", "pyPlain": "maozi", "en": "hat; cap"},
  h3_51_0: {"cn": "街道", "py": "jiē dào", "pyPlain": "jiedao", "en": "street; subdistrict"},
  h3_51_1: {"cn": "感冒", "py": "gǎn mào", "pyPlain": "ganmao", "en": "to catch cold; (common) cold"},
  h3_51_2: {"cn": "迟到", "py": "chí dào", "pyPlain": "chidao", "en": "to arrive late"},
  h3_51_3: {"cn": "刻", "py": "kè", "pyPlain": "ke", "en": "quarter (hour); moment"},
  h3_51_4: {"cn": "锻炼", "py": "duàn liàn", "pyPlain": "duanlian", "en": "to toughen; to temper"},
  h3_51_5: {"cn": "裤子", "py": "kù zi", "pyPlain": "kuzi", "en": "pants"},
  h3_51_6: {"cn": "夏", "py": "Xià", "pyPlain": "xia", "en": "the Xia or Hsia dynasty c. 2000 BC; Xia of the Sixteen…"},
  h3_51_7: {"cn": "图书馆", "py": "tú shū guǎn", "pyPlain": "tushuguan", "en": "library"},
  h3_51_8: {"cn": "电梯", "py": "diàn tī", "pyPlain": "dianti", "en": "elevator; escalator"},
  h3_51_9: {"cn": "刮", "py": "guā", "pyPlain": "gua", "en": "to scrape; to blow"},
  h3_51_10: {"cn": "矮", "py": "ǎi", "pyPlain": "ai", "en": "low; short (in length)"},
  h3_51_11: {"cn": "眼镜", "py": "yǎn jìng", "pyPlain": "yanjing", "en": "spectacles; eyeglasses"},
  h3_52_0: {"cn": "上网", "py": "shàng wǎng", "pyPlain": "shangwang", "en": "to go online; to connect to the Internet"},
  h3_52_1: {"cn": "春", "py": "chūn", "pyPlain": "chun", "en": "old variant of 春"},
  h3_52_2: {"cn": "面包", "py": "miàn bāo", "pyPlain": "mianbao", "en": "bread"},
  h3_52_3: {"cn": "冰箱", "py": "bīng xiāng", "pyPlain": "bingxiang", "en": "icebox; freezer cabinet"},
  h3_52_4: {"cn": "阿姨", "py": "ā yí", "pyPlain": "ayi", "en": "maternal aunt; step-mother"},
  h3_52_5: {"cn": "超市", "py": "chāo shì", "pyPlain": "chaoshi", "en": "supermarket (abbr. for 超级市场)"},
  h3_52_6: {"cn": "着急", "py": "zháo jí", "pyPlain": "zhaoji", "en": "to worry; to feel anxious; to feel a sense of urgency;…"},
  h3_52_7: {"cn": "季节", "py": "jì jié", "pyPlain": "jijie", "en": "time; season"},
  h3_52_8: {"cn": "饱", "py": "bǎo", "pyPlain": "bao", "en": "to eat till full; satisfied"},
  h3_52_9: {"cn": "空调", "py": "kōng tiáo", "pyPlain": "kongtiao", "en": "air conditioning; air conditioner (including units that…"},
  h3_52_10: {"cn": "一共", "py": "yī gòng", "pyPlain": "yigong", "en": "altogether"},
  h3_52_11: {"cn": "月亮", "py": "yuè liang", "pyPlain": "yueliang", "en": "the moon"},
  h3_53_0: {"cn": "北方", "py": "běi fāng", "pyPlain": "beifang", "en": "north; the northern part a country"},
  h3_53_1: {"cn": "爱好", "py": "ài hào", "pyPlain": "aihao", "en": "to like; to be fond of; to take pleasure in; to be keen…"},
  h3_53_2: {"cn": "衬衫", "py": "chèn shān", "pyPlain": "chenshan", "en": "shirt; blouse"},
  h3_53_3: {"cn": "冬", "py": "dōng", "pyPlain": "dong", "en": "winter"},
  h3_53_4: {"cn": "裙子", "py": "qún zi", "pyPlain": "qunzi", "en": "skirt"},
  h3_53_5: {"cn": "香蕉", "py": "xiāng jiāo", "pyPlain": "xiangjiao", "en": "banana"},
  h3_53_6: {"cn": "秋", "py": "Qiū", "pyPlain": "qiu", "en": "surname Qiu"},
  h3_53_7: {"cn": "发烧", "py": "fā shāo", "pyPlain": "fashao", "en": "to have a high temperature (from illness); to have a fever"},
  h3_53_8: {"cn": "伞", "py": "sǎn", "pyPlain": "san", "en": "umbrella; parasol"},
  h3_53_9: {"cn": "有名", "py": "yǒu míng", "pyPlain": "youming", "en": "famous; well-known"},
  h3_53_10: {"cn": "打扫", "py": "dǎ sǎo", "pyPlain": "dasao", "en": "to clean; to sweep"},
  h3_53_11: {"cn": "葡萄", "py": "pú tao", "pyPlain": "putao", "en": "grape"},
  h3_54_0: {"cn": "复习", "py": "fù xí", "pyPlain": "fuxi", "en": "to review; revision"},
  h3_54_1: {"cn": "熊猫", "py": "xióng māo", "pyPlain": "xiongmao", "en": "panda"},
  h3_54_2: {"cn": "护照", "py": "hù zhào", "pyPlain": "huzhao", "en": "passport"},
  h3_54_3: {"cn": "菜单", "py": "cài dān", "pyPlain": "caidan", "en": "menu"},
  h3_54_4: {"cn": "年级", "py": "nián jí", "pyPlain": "nianji", "en": "grade; year (in school, college etc)"},
  h3_54_5: {"cn": "果汁", "py": "guǒ zhī", "pyPlain": "guozhi", "en": "fruit juice"},
  h3_54_6: {"cn": "盘子", "py": "pán zi", "pyPlain": "panzi", "en": "tray; plate"},
  h3_54_7: {"cn": "铅笔", "py": "qiān bǐ", "pyPlain": "qianbi", "en": "(lead) pencil"},
  h3_54_8: {"cn": "渴", "py": "kě", "pyPlain": "ke", "en": "thirsty"},
  h3_54_9: {"cn": "洗手间", "py": "xǐ shǒu jiān", "pyPlain": "xishoujian", "en": "toilet; lavatory"},
  h3_54_10: {"cn": "词语", "py": "cí yǔ", "pyPlain": "ciyu", "en": "word (general term including monosyllables through to…"},
  h3_54_11: {"cn": "句子", "py": "jù zi", "pyPlain": "juzi", "en": "sentence"},
  h3_55_0: {"cn": "照相机", "py": "zhào xiàng jī", "pyPlain": "zhaoxiangji", "en": "camera"},
  h3_55_1: {"cn": "筷子", "py": "kuài zi", "pyPlain": "kuaizi", "en": "chopsticks"},
  h3_55_2: {"cn": "字典", "py": "zì diǎn", "pyPlain": "zidian", "en": "Chinese character dictionary (containing entries for…"},
  h3_55_3: {"cn": "普通话", "py": "pǔ tōng huà", "pyPlain": "putonghua", "en": "Mandarin (common language); Putonghua (common speech of…"},
  h3_55_4: {"cn": "爬山", "py": "pá shān", "pyPlain": "pashan", "en": "to climb a mountain; to mountaineer"},
  h3_55_5: {"cn": "黑板", "py": "hēi bǎn", "pyPlain": "heiban", "en": "blackboard"},
  h3_55_6: {"cn": "行李箱", "py": "xíng li xiāng", "pyPlain": "xinglixiang", "en": "suitcase; baggage compartment"}
});

window.UNITS.push(
  { id: "u31", title: "HSK 3 \u00b7 Set 1", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_31_0", "h3_31_1", "h3_31_2", "h3_31_3", "h3_31_4", "h3_31_5", "h3_31_6", "h3_31_7", "h3_31_8", "h3_31_9", "h3_31_10", "h3_31_11"],
    hanzi: ["啊", "把", "被", "自"] },
  { id: "u32", title: "HSK 3 \u00b7 Set 2", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_32_0", "h3_32_1", "h3_32_2", "h3_32_3", "h3_32_4", "h3_32_5", "h3_32_6", "h3_32_7", "h3_32_8", "h3_32_9", "h3_32_10", "h3_32_11"],
    hanzi: ["跟", "像", "还", "认"] },
  { id: "u33", title: "HSK 3 \u00b7 Set 3", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_33_0", "h3_33_1", "h3_33_2", "h3_33_3", "h3_33_4", "h3_33_5", "h3_33_6", "h3_33_7", "h3_33_8", "h3_33_9", "h3_33_10", "h3_33_11"],
    hanzi: ["样", "世", "界", "而"] },
  { id: "u34", title: "HSK 3 \u00b7 Set 4", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_34_0", "h3_34_1", "h3_34_2", "h3_34_3", "h3_34_4", "h3_34_5", "h3_34_6", "h3_34_7", "h3_34_8", "h3_34_9", "h3_34_10", "h3_34_11"],
    hanzi: ["放", "拿", "先", "关"] },
  { id: "u35", title: "HSK 3 \u00b7 Set 5", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_35_0", "h3_35_1", "h3_35_2", "h3_35_3", "h3_35_4", "h3_35_5", "h3_35_6", "h3_35_7", "h3_35_8", "h3_35_9", "h3_35_10", "h3_35_11"],
    hanzi: ["或", "者", "机", "人"] },
  { id: "u36", title: "HSK 3 \u00b7 Set 6", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_36_0", "h3_36_1", "h3_36_2", "h3_36_3", "h3_36_4", "h3_36_5", "h3_36_6", "h3_36_7", "h3_36_8", "h3_36_9", "h3_36_10", "h3_36_11"],
    hanzi: ["花", "虽", "然", "解"] },
  { id: "u37", title: "HSK 3 \u00b7 Set 7", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_37_0", "h3_37_1", "h3_37_2", "h3_37_3", "h3_37_4", "h3_37_5", "h3_37_6", "h3_37_7", "h3_37_8", "h3_37_9", "h3_37_10", "h3_37_11"],
    hanzi: ["讲", "离", "万", "以"] },
  { id: "u38", title: "HSK 3 \u00b7 Set 8", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_38_0", "h3_38_1", "h3_38_2", "h3_38_3", "h3_38_4", "h3_38_5", "h3_38_6", "h3_38_7", "h3_38_8", "h3_38_9", "h3_38_10", "h3_38_11"],
    hanzi: ["终", "于", "脸", "口"] },
  { id: "u39", title: "HSK 3 \u00b7 Set 9", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_39_0", "h3_39_1", "h3_39_2", "h3_39_3", "h3_39_4", "h3_39_5", "h3_39_6", "h3_39_7", "h3_39_8", "h3_39_9", "h3_39_10", "h3_39_11"],
    hanzi: ["根", "据", "记", "得"] },
  { id: "u40", title: "HSK 3 \u00b7 Set 10", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_40_0", "h3_40_1", "h3_40_2", "h3_40_3", "h3_40_4", "h3_40_5", "h3_40_6", "h3_40_7", "h3_40_8", "h3_40_9", "h3_40_10", "h3_40_11"],
    hanzi: ["故", "般", "可", "新"] },
  { id: "u41", title: "HSK 3 \u00b7 Set 11", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_41_0", "h3_41_1", "h3_41_2", "h3_41_3", "h3_41_4", "h3_41_5", "h3_41_6", "h3_41_7", "h3_41_8", "h3_41_9", "h3_41_10", "h3_41_11"],
    hanzi: ["经", "常", "低", "节"] },
  { id: "u42", title: "HSK 3 \u00b7 Set 12", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_42_0", "h3_42_1", "h3_42_2", "h3_42_3", "h3_42_4", "h3_42_5", "h3_42_6", "h3_42_7", "h3_42_8", "h3_42_9", "h3_42_10", "h3_42_11"],
    hanzi: ["附", "真", "脚", "主"] },
  { id: "u43", title: "HSK 3 \u00b7 Set 13", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_43_0", "h3_43_1", "h3_43_2", "h3_43_3", "h3_43_4", "h3_43_5", "h3_43_6", "h3_43_7", "h3_43_8", "h3_43_9", "h3_43_10", "h3_43_11"],
    hanzi: ["环", "境", "心", "祝"] },
  { id: "u44", title: "HSK 3 \u00b7 Set 14", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_44_0", "h3_44_1", "h3_44_2", "h3_44_3", "h3_44_4", "h3_44_5", "h3_44_6", "h3_44_7", "h3_44_8", "h3_44_9", "h3_44_10", "h3_44_11"],
    hanzi: ["忘", "打", "算", "极"] },
  { id: "u45", title: "HSK 3 \u00b7 Set 15", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_45_0", "h3_45_1", "h3_45_2", "h3_45_3", "h3_45_4", "h3_45_5", "h3_45_6", "h3_45_7", "h3_45_8", "h3_45_9", "h3_45_10", "h3_45_11"],
    hanzi: ["害", "怕", "鸟", "蓝"] },
  { id: "u46", title: "HSK 3 \u00b7 Set 16", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_46_0", "h3_46_1", "h3_46_2", "h3_46_3", "h3_46_4", "h3_46_5", "h3_46_6", "h3_46_7", "h3_46_8", "h3_46_9", "h3_46_10", "h3_46_11"],
    hanzi: ["司", "黄", "理", "兴"] },
  { id: "u47", title: "HSK 3 \u00b7 Set 17", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_47_0", "h3_47_1", "h3_47_2", "h3_47_3", "h3_47_4", "h3_47_5", "h3_47_6", "h3_47_7", "h3_47_8", "h3_47_9", "h3_47_10", "h3_47_11"],
    hanzi: ["太", "阳", "方", "便"] },
  { id: "u48", title: "HSK 3 \u00b7 Set 18", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_48_0", "h3_48_1", "h3_48_2", "h3_48_3", "h3_48_4", "h3_48_5", "h3_48_6", "h3_48_7", "h3_48_8", "h3_48_9", "h3_48_10", "h3_48_11"],
    hanzi: ["舒", "服", "体", "育"] },
  { id: "u49", title: "HSK 3 \u00b7 Set 19", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_49_0", "h3_49_1", "h3_49_2", "h3_49_3", "h3_49_4", "h3_49_5", "h3_49_6", "h3_49_7", "h3_49_8", "h3_49_9", "h3_49_10", "h3_49_11"],
    hanzi: ["啤", "酒", "糕", "鲜"] },
  { id: "u50", title: "HSK 3 \u00b7 Set 20", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_50_0", "h3_50_1", "h3_50_2", "h3_50_3", "h3_50_4", "h3_50_5", "h3_50_6", "h3_50_7", "h3_50_8", "h3_50_9", "h3_50_10", "h3_50_11"],
    hanzi: ["爷", "云", "邻", "居"] },
  { id: "u51", title: "HSK 3 \u00b7 Set 21", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_51_0", "h3_51_1", "h3_51_2", "h3_51_3", "h3_51_4", "h3_51_5", "h3_51_6", "h3_51_7", "h3_51_8", "h3_51_9", "h3_51_10", "h3_51_11"],
    hanzi: ["街", "道", "感", "冒"] },
  { id: "u52", title: "HSK 3 \u00b7 Set 22", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_52_0", "h3_52_1", "h3_52_2", "h3_52_3", "h3_52_4", "h3_52_5", "h3_52_6", "h3_52_7", "h3_52_8", "h3_52_9", "h3_52_10", "h3_52_11"],
    hanzi: ["上", "网", "春", "面"] },
  { id: "u53", title: "HSK 3 \u00b7 Set 23", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_53_0", "h3_53_1", "h3_53_2", "h3_53_3", "h3_53_4", "h3_53_5", "h3_53_6", "h3_53_7", "h3_53_8", "h3_53_9", "h3_53_10", "h3_53_11"],
    hanzi: ["北", "衬", "衫", "冬"] },
  { id: "u54", title: "HSK 3 \u00b7 Set 24", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_54_0", "h3_54_1", "h3_54_2", "h3_54_3", "h3_54_4", "h3_54_5", "h3_54_6", "h3_54_7", "h3_54_8", "h3_54_9", "h3_54_10", "h3_54_11"],
    hanzi: ["复", "习", "熊", "护"] },
  { id: "u55", title: "HSK 3 \u00b7 Set 25", icon: "\ud83d\udcd7", hsk: 3, auto: true,
    words: ["h3_55_0", "h3_55_1", "h3_55_2", "h3_55_3", "h3_55_4", "h3_55_5", "h3_55_6"],
    hanzi: ["照", "相", "筷", "子"] }
);
