// Mandarin Journey — HSK 4 word-expansion stage (auto-generated units)
// Source: drkameleon/complete-hsk-vocabulary (old-HSK 4 exclusive list), frequency-ordered.

Object.assign(window.WORDS, {
  h4_56_0: {"cn": "过", "py": "Guō", "pyPlain": "guo", "en": "surname Guo"},
  h4_56_1: {"cn": "而", "py": "ér", "pyPlain": "er", "en": "and; as well as"},
  h4_56_2: {"cn": "与", "py": "yú", "pyPlain": "yu", "en": "variant of 欤"},
  h4_56_3: {"cn": "当", "py": "dāng", "pyPlain": "dang", "en": "(onom.) dong; ding dong (bell)"},
  h4_56_4: {"cn": "之", "py": "zhī", "pyPlain": "zhi", "en": "(possessive particle, literary equivalent of 的); him"},
  h4_56_5: {"cn": "以", "py": "yǐ", "pyPlain": "yi", "en": "old variant of 以"},
  h4_56_6: {"cn": "起来", "py": "qǐ lai", "pyPlain": "qilai", "en": "to stand up; to get up"},
  h4_56_7: {"cn": "死", "py": "sǐ", "pyPlain": "si", "en": "to die; impassable"},
  h4_56_8: {"cn": "却", "py": "què", "pyPlain": "que", "en": "old variant of 却"},
  h4_56_9: {"cn": "生活", "py": "shēng huó", "pyPlain": "shenghuo", "en": "to live; life"},
  h4_56_10: {"cn": "发生", "py": "fā shēng", "pyPlain": "fasheng", "en": "to happen; to occur; to take place; to break out"},
  h4_56_11: {"cn": "不过", "py": "bù guò", "pyPlain": "buguo", "en": "only; merely"},
  h4_57_0: {"cn": "所有", "py": "suǒ yǒu", "pyPlain": "suoyou", "en": "all; to have; to possess; to own"},
  h4_57_1: {"cn": "情况", "py": "qíng kuàng", "pyPlain": "qingkuang", "en": "circumstances; state of affairs; situation"},
  h4_57_2: {"cn": "最后", "py": "zuì hòu", "pyPlain": "zuihou", "en": "final; last"},
  h4_57_3: {"cn": "成为", "py": "chéng wéi", "pyPlain": "chengwei", "en": "to become; to turn into"},
  h4_57_4: {"cn": "行", "py": "háng", "pyPlain": "hang", "en": "row; line"},
  h4_57_5: {"cn": "感觉", "py": "gǎn jué", "pyPlain": "ganjue", "en": "feeling; impression; sensation; to feel; to perceive"},
  h4_57_6: {"cn": "继续", "py": "jì xù", "pyPlain": "jixu", "en": "to continue; to proceed with"},
  h4_57_7: {"cn": "场", "py": "cháng", "pyPlain": "chang", "en": "threshing floor; classifier for events and happenings:…"},
  h4_57_8: {"cn": "进行", "py": "jìn xíng", "pyPlain": "jinxing", "en": "to advance; to conduct"},
  h4_57_9: {"cn": "内", "py": "nèi", "pyPlain": "nei", "en": "inside; inner"},
  h4_57_10: {"cn": "通过", "py": "tōng guò", "pyPlain": "tongguo", "en": "to pass through; to get through; to adopt (a…"},
  h4_57_11: {"cn": "无", "py": "wú", "pyPlain": "wu", "en": "not to have; no"},
  h4_58_0: {"cn": "一切", "py": "yī qiè", "pyPlain": "yiqie", "en": "everything; every"},
  h4_58_1: {"cn": "由", "py": "yóu", "pyPlain": "you", "en": "to follow; from"},
  h4_58_2: {"cn": "任何", "py": "rèn hé", "pyPlain": "renhe", "en": "any; whatever"},
  h4_58_3: {"cn": "安全", "py": "ān quán", "pyPlain": "anquan", "en": "safe; secure; safety; security"},
  h4_58_4: {"cn": "结果", "py": "jiē guǒ", "pyPlain": "jieguo", "en": "to bear fruit"},
  h4_58_5: {"cn": "完全", "py": "wán quán", "pyPlain": "wanquan", "en": "complete; whole; totally; entirely"},
  h4_58_6: {"cn": "发", "py": "fā", "pyPlain": "fa", "en": "to send out; to show (one's feeling)"},
  h4_58_7: {"cn": "计划", "py": "jì huà", "pyPlain": "jihua", "en": "plan; project"},
  h4_58_8: {"cn": "可是", "py": "kě shì", "pyPlain": "keshi", "en": "but; however; (used for emphasis) indeed"},
  h4_58_9: {"cn": "连", "py": "Lián", "pyPlain": "lian", "en": "surname Lian"},
  h4_58_10: {"cn": "呀", "py": "ya", "pyPlain": "ya", "en": "(particle equivalent to 啊 after a vowel, expressing…"},
  h4_58_11: {"cn": "原因", "py": "yuán yīn", "pyPlain": "yuanyin", "en": "cause; origin"},
  h4_59_0: {"cn": "消息", "py": "xiāo xi", "pyPlain": "xiaoxi", "en": "news; information"},
  h4_59_1: {"cn": "只要", "py": "zhǐ yào", "pyPlain": "zhiyao", "en": "if only; so long as"},
  h4_59_2: {"cn": "干", "py": "gān", "pyPlain": "gan", "en": "old variant of 干"},
  h4_59_3: {"cn": "接受", "py": "jiē shòu", "pyPlain": "jieshou", "en": "to accept; to receive"},
  h4_59_4: {"cn": "其中", "py": "qí zhōng", "pyPlain": "qizhong", "en": "among; in"},
  h4_59_5: {"cn": "成功", "py": "Chéng gōng", "pyPlain": "chenggong", "en": "Chenggong or Chengkung town in Taitung County 台东县,…"},
  h4_59_6: {"cn": "甚至", "py": "shèn zhì", "pyPlain": "shenzhi", "en": "even; so much so that"},
  h4_59_7: {"cn": "拉", "py": "lā", "pyPlain": "la", "en": "to pull; to play (a bowed instrument)"},
  h4_59_8: {"cn": "肯定", "py": "kěn dìng", "pyPlain": "kending", "en": "to be certain; to be positive"},
  h4_59_9: {"cn": "当时", "py": "dāng shí", "pyPlain": "dangshi", "en": "then; at that time"},
  h4_59_10: {"cn": "调查", "py": "diào chá", "pyPlain": "diaocha", "en": "investigation; inquiry"},
  h4_59_11: {"cn": "部分", "py": "bù fen", "pyPlain": "bufen", "en": "part; share"},
  h4_60_0: {"cn": "能力", "py": "néng lì", "pyPlain": "nengli", "en": "capability; ability"},
  h4_60_1: {"cn": "保护", "py": "bǎo hù", "pyPlain": "baohu", "en": "to protect; to defend"},
  h4_60_2: {"cn": "真正", "py": "zhēn zhèng", "pyPlain": "zhenzheng", "en": "genuine; real; true; really; indeed"},
  h4_60_3: {"cn": "支持", "py": "zhī chí", "pyPlain": "zhichi", "en": "to be in favor of; to support"},
  h4_60_4: {"cn": "掉", "py": "diào", "pyPlain": "diao", "en": "to fall; to drop"},
  h4_60_5: {"cn": "改变", "py": "gǎi biàn", "pyPlain": "gaibian", "en": "to change; to alter"},
  h4_60_6: {"cn": "方法", "py": "fāng fǎ", "pyPlain": "fangfa", "en": "method; way"},
  h4_60_7: {"cn": "保证", "py": "bǎo zhèng", "pyPlain": "baozheng", "en": "guarantee; to guarantee"},
  h4_60_8: {"cn": "直接", "py": "zhí jiē", "pyPlain": "zhijie", "en": "direct (opposite: indirect 间接); immediate"},
  h4_60_9: {"cn": "组织", "py": "zǔ zhī", "pyPlain": "zuzhi", "en": "to organize; organization"},
  h4_60_10: {"cn": "永远", "py": "yǒng yuǎn", "pyPlain": "yongyuan", "en": "forever; eternal"},
  h4_60_11: {"cn": "方面", "py": "fāng miàn", "pyPlain": "fangmian", "en": "respect; aspect"},
  h4_61_0: {"cn": "也许", "py": "yě xǔ", "pyPlain": "yexu", "en": "perhaps; maybe"},
  h4_61_1: {"cn": "活动", "py": "huó dòng", "pyPlain": "huodong", "en": "to exercise; to move about"},
  h4_61_2: {"cn": "考虑", "py": "kǎo lǜ", "pyPlain": "kaolv", "en": "to think over; to consider"},
  h4_61_3: {"cn": "份", "py": "fèn", "pyPlain": "fen", "en": "classifier for gifts, newspaper, magazine, papers,…"},
  h4_61_4: {"cn": "提供", "py": "tí gōng", "pyPlain": "tigong", "en": "to offer; to supply"},
  h4_61_5: {"cn": "指", "py": "zhǐ", "pyPlain": "zhi", "en": "finger; to point at or to"},
  h4_61_6: {"cn": "精神", "py": "jīng shén", "pyPlain": "jingshen", "en": "spirit; mind"},
  h4_61_7: {"cn": "使用", "py": "shǐ yòng", "pyPlain": "shiyong", "en": "to use; to employ"},
  h4_61_8: {"cn": "代表", "py": "dài biǎo", "pyPlain": "daibiao", "en": "representative; delegate"},
  h4_61_9: {"cn": "任务", "py": "rèn wu", "pyPlain": "renwu", "en": "mission; assignment; task; duty; role"},
  h4_61_10: {"cn": "联系", "py": "lián xì", "pyPlain": "lianxi", "en": "variant of 联系"},
  h4_61_11: {"cn": "因此", "py": "yīn cǐ", "pyPlain": "yinci", "en": "thus; consequently; as a result"},
  h4_62_0: {"cn": "台", "py": "Tái", "pyPlain": "tai", "en": "Taiwan (abbr.)"},
  h4_62_1: {"cn": "算", "py": "suàn", "pyPlain": "suan", "en": "to regard as; to figure"},
  h4_62_2: {"cn": "获得", "py": "huò dé", "pyPlain": "huode", "en": "to obtain; to receive; to get"},
  h4_62_3: {"cn": "留", "py": "liú", "pyPlain": "liu", "en": "old variant of 留"},
  h4_62_4: {"cn": "生命", "py": "shēng mìng", "pyPlain": "shengming", "en": "life (as the characteristic of living beings); living…"},
  h4_62_5: {"cn": "交", "py": "jiāo", "pyPlain": "jiao", "en": "to hand over; to deliver"},
  h4_62_6: {"cn": "全部", "py": "quán bù", "pyPlain": "quanbu", "en": "whole; all"},
  h4_62_7: {"cn": "刚刚", "py": "gāng gang", "pyPlain": "ganggang", "en": "just recently; just a moment ago"},
  h4_62_8: {"cn": "正常", "py": "zhèng cháng", "pyPlain": "zhengchang", "en": "regular; normal"},
  h4_62_9: {"cn": "另外", "py": "lìng wài", "pyPlain": "lingwai", "en": "additional; in addition"},
  h4_62_10: {"cn": "血", "py": "xuè", "pyPlain": "xue", "en": "blood; colloquial pr."},
  h4_62_11: {"cn": "挺", "py": "tǐng", "pyPlain": "ting", "en": "straight; erect"},
  h4_63_0: {"cn": "好像", "py": "hǎo xiàng", "pyPlain": "haoxiang", "en": "as if; to seem like"},
  h4_63_1: {"cn": "到底", "py": "dào dǐ", "pyPlain": "daodi", "en": "finally; in the end"},
  h4_63_2: {"cn": "感谢", "py": "gǎn xiè", "pyPlain": "ganxie", "en": "(express) thanks; gratitude"},
  h4_63_3: {"cn": "坚持", "py": "jiān chí", "pyPlain": "jianchi", "en": "to persevere with; to persist in"},
  h4_63_4: {"cn": "座", "py": "zuò", "pyPlain": "zuo", "en": "seat; base"},
  h4_63_5: {"cn": "技术", "py": "jì shù", "pyPlain": "jishu", "en": "technology; technique; skill"},
  h4_63_6: {"cn": "往", "py": "wǎng", "pyPlain": "wang", "en": "to go (in a direction); to"},
  h4_63_7: {"cn": "严重", "py": "yán zhòng", "pyPlain": "yanzhong", "en": "grave; serious"},
  h4_63_8: {"cn": "包括", "py": "bāo kuò", "pyPlain": "baokuo", "en": "to comprise; to include"},
  h4_63_9: {"cn": "原来", "py": "yuán lái", "pyPlain": "yuanlai", "en": "original; former"},
  h4_63_10: {"cn": "光", "py": "guāng", "pyPlain": "guang", "en": "light; ray; bright; shiny"},
  h4_63_11: {"cn": "法律", "py": "fǎ lǜ", "pyPlain": "falv", "en": "law"},
  h4_64_0: {"cn": "父亲", "py": "fù qīn", "pyPlain": "fuqin", "en": "father; also pr."},
  h4_64_1: {"cn": "并且", "py": "bìng qiě", "pyPlain": "bingqie", "en": "and; besides"},
  h4_64_2: {"cn": "收", "py": "shōu", "pyPlain": "shou", "en": "to receive; to accept"},
  h4_64_3: {"cn": "社会", "py": "shè huì", "pyPlain": "shehui", "en": "society"},
  h4_64_4: {"cn": "证明", "py": "zhèng míng", "pyPlain": "zhengming", "en": "proof; certificate"},
  h4_64_5: {"cn": "记者", "py": "jì zhě", "pyPlain": "jizhe", "en": "reporter; journalist"},
  h4_64_6: {"cn": "底", "py": "de", "pyPlain": "de", "en": "(equivalent to 的 as possessive particle)"},
  h4_64_7: {"cn": "确实", "py": "què shí", "pyPlain": "queshi", "en": "indeed; really"},
  h4_64_8: {"cn": "不管", "py": "bù guǎn", "pyPlain": "buguan", "en": "not to be concerned; regardless of"},
  h4_64_9: {"cn": "受到", "py": "shòu dào", "pyPlain": "shoudao", "en": "to receive (praise, an education, punishment etc); to be…"},
  h4_64_10: {"cn": "发展", "py": "fā zhǎn", "pyPlain": "fazhan", "en": "development; growth"},
  h4_64_11: {"cn": "谈", "py": "Tán", "pyPlain": "tan", "en": "surname Tan"},
  h4_65_0: {"cn": "至少", "py": "zhì shǎo", "pyPlain": "zhishao", "en": "at least; (to say the) least"},
  h4_65_1: {"cn": "解释", "py": "jiě shì", "pyPlain": "jieshi", "en": "explanation; to explain"},
  h4_65_2: {"cn": "负责", "py": "fù zé", "pyPlain": "fuze", "en": "to be in charge of; to take responsibility for"},
  h4_65_3: {"cn": "首先", "py": "shǒu xiān", "pyPlain": "shouxian", "en": "first (of all); in the first place"},
  h4_65_4: {"cn": "理解", "py": "lǐ jiě", "pyPlain": "lijie", "en": "to comprehend; to understand"},
  h4_65_5: {"cn": "报道", "py": "bào dào", "pyPlain": "baodao", "en": "to report (news); report"},
  h4_65_6: {"cn": "安排", "py": "ān pái", "pyPlain": "anpai", "en": "to arrange; to plan"},
  h4_65_7: {"cn": "梦", "py": "mèng", "pyPlain": "meng", "en": "dream; (bound form) to dream"},
  h4_65_8: {"cn": "重新", "py": "chóng xīn", "pyPlain": "chongxin", "en": "again; once more; re-"},
  h4_65_9: {"cn": "幸福", "py": "xìng fú", "pyPlain": "xingfu", "en": "happiness; happy"},
  h4_65_10: {"cn": "自然", "py": "zì rán", "pyPlain": "ziran", "en": "nature; natural"},
  h4_65_11: {"cn": "责任", "py": "zé rèn", "pyPlain": "zeren", "en": "responsibility; blame"},
  h4_66_0: {"cn": "试", "py": "shì", "pyPlain": "shi", "en": "to test; to try"},
  h4_66_1: {"cn": "弄", "py": "lòng", "pyPlain": "long", "en": "lane; alley"},
  h4_66_2: {"cn": "赢", "py": "yíng", "pyPlain": "ying", "en": "to beat; to win"},
  h4_66_3: {"cn": "满", "py": "Mǎn", "pyPlain": "man", "en": "Manchu ethnic group"},
  h4_66_4: {"cn": "说明", "py": "shuō míng", "pyPlain": "shuoming", "en": "to explain; to illustrate"},
  h4_66_5: {"cn": "许多", "py": "xǔ duō", "pyPlain": "xuduo", "en": "many; a lot of"},
  h4_66_6: {"cn": "压力", "py": "yā lì", "pyPlain": "yali", "en": "pressure"},
  h4_66_7: {"cn": "由于", "py": "yóu yú", "pyPlain": "youyu", "en": "due to; as a result of"},
  h4_66_8: {"cn": "母亲", "py": "mǔ qīn", "pyPlain": "muqin", "en": "mother; also pr."},
  h4_66_9: {"cn": "放弃", "py": "fàng qì", "pyPlain": "fangqi", "en": "to renounce; to abandon; to give up"},
  h4_66_10: {"cn": "意见", "py": "yì jiàn", "pyPlain": "yijian", "en": "idea; opinion"},
  h4_66_11: {"cn": "过程", "py": "guò chéng", "pyPlain": "guocheng", "en": "course of events; process"},
  h4_67_0: {"cn": "即使", "py": "jí shǐ", "pyPlain": "jishi", "en": "even if; even though"},
  h4_67_1: {"cn": "尽管", "py": "jǐn guǎn", "pyPlain": "jinguan", "en": "despite; although"},
  h4_67_2: {"cn": "深", "py": "shēn", "pyPlain": "shen", "en": "old variant of 深"},
  h4_67_3: {"cn": "各", "py": "gè", "pyPlain": "ge", "en": "each; every"},
  h4_67_4: {"cn": "仍然", "py": "réng rán", "pyPlain": "rengran", "en": "still; as before; yet"},
  h4_67_5: {"cn": "值得", "py": "zhí de", "pyPlain": "zhide", "en": "to be worth; to deserve"},
  h4_67_6: {"cn": "经历", "py": "jīng lì", "pyPlain": "jingli", "en": "experience; to experience"},
  h4_67_7: {"cn": "讨论", "py": "tǎo lùn", "pyPlain": "taolun", "en": "to discuss; to talk over"},
  h4_67_8: {"cn": "超过", "py": "chāo guò", "pyPlain": "chaoguo", "en": "to surpass; to exceed"},
  h4_67_9: {"cn": "假", "py": "gēi", "pyPlain": "gei", "en": "used in 掰"},
  h4_67_10: {"cn": "后来", "py": "hòu lái", "pyPlain": "houlai", "en": "afterwards; later; newly arrived"},
  h4_67_11: {"cn": "嘴", "py": "zuǐ", "pyPlain": "zui", "en": "mouth; beak"},
  h4_68_0: {"cn": "地址", "py": "dì zhǐ", "pyPlain": "dizhi", "en": "address"},
  h4_68_1: {"cn": "无论", "py": "wú lùn", "pyPlain": "wulun", "en": "no matter what or how; regardless of whether..."},
  h4_68_2: {"cn": "紧张", "py": "jǐn zhāng", "pyPlain": "jinzhang", "en": "nervous; keyed up"},
  h4_68_3: {"cn": "省", "py": "shěng", "pyPlain": "sheng", "en": "to save; to economize; to be frugal; to omit; to delete;…"},
  h4_68_4: {"cn": "十分", "py": "shí fēn", "pyPlain": "shifen", "en": "very; completely"},
  h4_68_5: {"cn": "陪", "py": "péi", "pyPlain": "pei", "en": "to accompany; to keep sb company"},
  h4_68_6: {"cn": "挂", "py": "guà", "pyPlain": "gua", "en": "to hang or suspend (from a hook etc); to hang up (the phone)"},
  h4_68_7: {"cn": "本来", "py": "běn lái", "pyPlain": "benlai", "en": "original; originally"},
  h4_68_8: {"cn": "条件", "py": "tiáo jiàn", "pyPlain": "tiaojian", "en": "condition; circumstance; term; factor; requirement;…"},
  h4_68_9: {"cn": "广告", "py": "guǎng gào", "pyPlain": "guanggao", "en": "to advertise; a commercial"},
  h4_68_10: {"cn": "警察", "py": "jǐng chá", "pyPlain": "jingcha", "en": "police; police officer"},
  h4_68_11: {"cn": "关键", "py": "guān jiàn", "pyPlain": "guanjian", "en": "crucial point; crux"},
  h4_69_0: {"cn": "样子", "py": "yàng zi", "pyPlain": "yangzi", "en": "appearance; manner"},
  h4_69_1: {"cn": "困难", "py": "kùn nan", "pyPlain": "kunnan", "en": "difficult; challenging"},
  h4_69_2: {"cn": "专业", "py": "zhuān yè", "pyPlain": "zhuanye", "en": "specialty; specialized field"},
  h4_69_3: {"cn": "难道", "py": "nán dào", "pyPlain": "nandao", "en": "don't tell me ...; could it be that...?"},
  h4_69_4: {"cn": "规定", "py": "guī dìng", "pyPlain": "guiding", "en": "to stipulate; to specify; to prescribe; to fix (a…"},
  h4_69_5: {"cn": "于是", "py": "yú shì", "pyPlain": "yushi", "en": "thereupon; as a result; consequently; thus; hence"},
  h4_69_6: {"cn": "正确", "py": "zhèng què", "pyPlain": "zhengque", "en": "correct; sound; right; proper"},
  h4_69_7: {"cn": "爱情", "py": "ài qíng", "pyPlain": "aiqing", "en": "romance; love (romantic)"},
  h4_69_8: {"cn": "群", "py": "qún", "pyPlain": "qun", "en": "variant of 群"},
  h4_69_9: {"cn": "够", "py": "gòu", "pyPlain": "gou", "en": "enough (sufficient); enough (too much)"},
  h4_69_10: {"cn": "火", "py": "Huǒ", "pyPlain": "huo", "en": "surname Huo"},
  h4_69_11: {"cn": "方向", "py": "fāng xiàng", "pyPlain": "fangxiang", "en": "direction; orientation"},
  h4_70_0: {"cn": "市场", "py": "shì chǎng", "pyPlain": "shichang", "en": "marketplace; market (also in abstract)"},
  h4_70_1: {"cn": "教育", "py": "jiào yù", "pyPlain": "jiaoyu", "en": "to educate; to teach"},
  h4_70_2: {"cn": "取", "py": "qǔ", "pyPlain": "qu", "en": "to take; to get"},
  h4_70_3: {"cn": "危险", "py": "wēi xiǎn", "pyPlain": "weixian", "en": "danger; dangerous"},
  h4_70_4: {"cn": "管理", "py": "guǎn lǐ", "pyPlain": "guanli", "en": "to supervise; to manage"},
  h4_70_5: {"cn": "乱", "py": "luàn", "pyPlain": "luan", "en": "in confusion or disorder; in a confused state of mind"},
  h4_70_6: {"cn": "适合", "py": "shì hé", "pyPlain": "shihe", "en": "to fit; to suit"},
  h4_70_7: {"cn": "正式", "py": "zhèng shì", "pyPlain": "zhengshi", "en": "formal; official"},
  h4_70_8: {"cn": "引起", "py": "yǐn qǐ", "pyPlain": "yinqi", "en": "to give rise to; to lead to; to cause; to arouse"},
  h4_70_9: {"cn": "从来", "py": "cóng lái", "pyPlain": "conglai", "en": "always; at all times"},
  h4_70_10: {"cn": "抱", "py": "bào", "pyPlain": "bao", "en": "to hold; to carry (in one's arms)"},
  h4_70_11: {"cn": "律师", "py": "lǜ shī", "pyPlain": "lvshi", "en": "lawyer"},
  h4_71_0: {"cn": "内容", "py": "nèi róng", "pyPlain": "neirong", "en": "content; substance"},
  h4_71_1: {"cn": "通知", "py": "tōng zhī", "pyPlain": "tongzhi", "en": "to notify; to inform"},
  h4_71_2: {"cn": "感情", "py": "gǎn qíng", "pyPlain": "ganqing", "en": "emotion; sentiment"},
  h4_71_3: {"cn": "观众", "py": "guān zhòng", "pyPlain": "guanzhong", "en": "spectators; audience"},
  h4_71_4: {"cn": "目的", "py": "mù dì", "pyPlain": "mudi", "en": "purpose; aim; goal; target; objective"},
  h4_71_5: {"cn": "国际", "py": "guó jì", "pyPlain": "guoji", "en": "international"},
  h4_71_6: {"cn": "美丽", "py": "měi lì", "pyPlain": "meili", "en": "beautiful"},
  h4_71_7: {"cn": "经验", "py": "jīng yàn", "pyPlain": "jingyan", "en": "experience; to experience"},
  h4_71_8: {"cn": "破", "py": "pò", "pyPlain": "po", "en": "broken; damaged"},
  h4_71_9: {"cn": "推", "py": "tuī", "pyPlain": "tui", "en": "to push; to cut"},
  h4_71_10: {"cn": "刀", "py": "Dāo", "pyPlain": "dao", "en": "surname Dao"},
  h4_71_11: {"cn": "科学", "py": "kē xué", "pyPlain": "kexue", "en": "science; scientific knowledge"},
  h4_72_0: {"cn": "心情", "py": "xīn qíng", "pyPlain": "xinqing", "en": "mood; frame of mind"},
  h4_72_1: {"cn": "标准", "py": "biāo zhǔn", "pyPlain": "biaozhun", "en": "standard; norm; criterion; (adjective) standard"},
  h4_72_2: {"cn": "职业", "py": "zhí yè", "pyPlain": "zhiye", "en": "occupation; profession; vocation; professional"},
  h4_72_3: {"cn": "精彩", "py": "jīng cǎi", "pyPlain": "jingcai", "en": "wonderful; marvelous"},
  h4_72_4: {"cn": "范围", "py": "fàn wéi", "pyPlain": "fanwei", "en": "range; scope"},
  h4_72_5: {"cn": "速度", "py": "sù dù", "pyPlain": "sudu", "en": "speed; rate"},
  h4_72_6: {"cn": "实在", "py": "shí zài", "pyPlain": "shizai", "en": "really; actually"},
  h4_72_7: {"cn": "效果", "py": "xiào guǒ", "pyPlain": "xiaoguo", "en": "result; effect"},
  h4_72_8: {"cn": "遍", "py": "biàn", "pyPlain": "bian", "en": "variant of 遍"},
  h4_72_9: {"cn": "经济", "py": "jīng jì", "pyPlain": "jingji", "en": "economy; economic"},
  h4_72_10: {"cn": "按照", "py": "àn zhào", "pyPlain": "anzhao", "en": "according to; in accordance with"},
  h4_72_11: {"cn": "反对", "py": "fǎn duì", "pyPlain": "fandui", "en": "to oppose; to be against; to object to"},
  h4_73_0: {"cn": "竟然", "py": "jìng rán", "pyPlain": "jingran", "en": "unexpectedly; to one's surprise"},
  h4_73_1: {"cn": "重点", "py": "chóng diǎn", "pyPlain": "chongdian", "en": "to recount (e.g. results of election); to re-evaluate"},
  h4_73_2: {"cn": "倍", "py": "bèi", "pyPlain": "bei", "en": "(two, three etc) -fold; times (multiplier)"},
  h4_73_3: {"cn": "醒", "py": "xǐng", "pyPlain": "xing", "en": "to wake up; to be awake"},
  h4_73_4: {"cn": "讨厌", "py": "tǎo yàn", "pyPlain": "taoyan", "en": "to dislike; to loathe"},
  h4_73_5: {"cn": "输", "py": "shū", "pyPlain": "shu", "en": "to lose; to be beaten; (bound form) to transport"},
  h4_73_6: {"cn": "咱们", "py": "zán men", "pyPlain": "zanmen", "en": "we or us (including both the speaker and the person(s)…"},
  h4_73_7: {"cn": "否则", "py": "fǒu zé", "pyPlain": "fouze", "en": "otherwise; if not; or (else)"},
  h4_73_8: {"cn": "免费", "py": "miǎn fèi", "pyPlain": "mianfei", "en": "free (of charge)"},
  h4_73_9: {"cn": "动作", "py": "dòng zuò", "pyPlain": "dongzuo", "en": "movement; motion; action; to act; to move"},
  h4_73_10: {"cn": "俩", "py": "liǎ", "pyPlain": "lia", "en": "two (colloquial equivalent of 两个); both"},
  h4_73_11: {"cn": "增加", "py": "zēng jiā", "pyPlain": "zengjia", "en": "to raise; to increase"},
  h4_74_0: {"cn": "著名", "py": "zhù míng", "pyPlain": "zhuming", "en": "famous; noted"},
  h4_74_1: {"cn": "拒绝", "py": "jù jué", "pyPlain": "jujue", "en": "to refuse; to decline; to reject"},
  h4_74_2: {"cn": "帅", "py": "Shuài", "pyPlain": "shuai", "en": "surname Shuai"},
  h4_74_3: {"cn": "不仅", "py": "bù jǐn", "pyPlain": "bujin", "en": "not just; not limited to; (as a correlative conjunction)…"},
  h4_74_4: {"cn": "顺利", "py": "shùn lì", "pyPlain": "shunli", "en": "smoothly; without a hitch"},
  h4_74_5: {"cn": "艺术", "py": "yì shù", "pyPlain": "yishu", "en": "art"},
  h4_74_6: {"cn": "麻烦", "py": "má fan", "pyPlain": "mafan", "en": "trouble; inconvenience; inconvenient; troublesome; annoying"},
  h4_74_7: {"cn": "申请", "py": "shēn qǐng", "pyPlain": "shenqing", "en": "to apply for sth; application form"},
  h4_74_8: {"cn": "演出", "py": "yǎn chū", "pyPlain": "yanchu", "en": "to act (in a play); to perform"},
  h4_74_9: {"cn": "猪", "py": "zhū", "pyPlain": "zhu", "en": "hog; pig"},
  h4_74_10: {"cn": "竞争", "py": "jìng zhēng", "pyPlain": "jingzheng", "en": "to compete; competition"},
  h4_74_11: {"cn": "估计", "py": "gū jì", "pyPlain": "guji", "en": "to estimate; to reckon"},
  h4_75_0: {"cn": "失败", "py": "shī bài", "pyPlain": "shibai", "en": "to be defeated; to lose"},
  h4_75_1: {"cn": "世纪", "py": "shì jì", "pyPlain": "shiji", "en": "century"},
  h4_75_2: {"cn": "制造", "py": "zhì zào", "pyPlain": "zhizao", "en": "to manufacture; to make"},
  h4_75_3: {"cn": "不得不", "py": "bù dé bù", "pyPlain": "budebu", "en": "have no choice or option but to; cannot but"},
  h4_75_4: {"cn": "当地", "py": "dāng dì", "pyPlain": "dangdi", "en": "local"},
  h4_75_5: {"cn": "大概", "py": "dà gài", "pyPlain": "dagai", "en": "roughly; probably"},
  h4_75_6: {"cn": "允许", "py": "yǔn xǔ", "pyPlain": "yunxu", "en": "to permit; to allow"},
  h4_75_7: {"cn": "教授", "py": "jiào shòu", "pyPlain": "jiaoshou", "en": "professor; to instruct"},
  h4_75_8: {"cn": "顿", "py": "dùn", "pyPlain": "dun", "en": "to stop; to pause"},
  h4_75_9: {"cn": "吸引", "py": "xī yǐn", "pyPlain": "xiyin", "en": "to attract; to appeal to; to fascinate"},
  h4_75_10: {"cn": "共同", "py": "gòng tóng", "pyPlain": "gongtong", "en": "common; joint"},
  h4_75_11: {"cn": "杂志", "py": "zá zhì", "pyPlain": "zazhi", "en": "magazine"},
  h4_76_0: {"cn": "既然", "py": "jì rán", "pyPlain": "jiran", "en": "since; as"},
  h4_76_1: {"cn": "停止", "py": "tíng zhǐ", "pyPlain": "tingzhi", "en": "to stop; to halt; to cease"},
  h4_76_2: {"cn": "提醒", "py": "tí xǐng", "pyPlain": "tixing", "en": "to remind; to call attention to"},
  h4_76_3: {"cn": "演员", "py": "yǎn yuán", "pyPlain": "yanyuan", "en": "actor or actress; performer"},
  h4_76_4: {"cn": "态度", "py": "tài du", "pyPlain": "taidu", "en": "manner; bearing"},
  h4_76_5: {"cn": "周围", "py": "zhōu wéi", "pyPlain": "zhouwei", "en": "environs; surroundings; periphery"},
  h4_76_6: {"cn": "丢", "py": "diū", "pyPlain": "diu", "en": "to lose; to put aside"},
  h4_76_7: {"cn": "复杂", "py": "fù zá", "pyPlain": "fuza", "en": "complicated; complex"},
  h4_76_8: {"cn": "表达", "py": "biǎo dá", "pyPlain": "biaoda", "en": "to express; to convey"},
  h4_76_9: {"cn": "数字", "py": "shù zì", "pyPlain": "shuzi", "en": "numeral; digit"},
  h4_76_10: {"cn": "邀请", "py": "yāo qǐng", "pyPlain": "yaoqing", "en": "to invite; invitation"},
  h4_76_11: {"cn": "交通", "py": "jiāo tōng", "pyPlain": "jiaotong", "en": "to be connected; traffic"},
  h4_77_0: {"cn": "优秀", "py": "yōu xiù", "pyPlain": "youxiu", "en": "outstanding; excellent"},
  h4_77_1: {"cn": "亮", "py": "liàng", "pyPlain": "liang", "en": "bright; clear"},
  h4_77_2: {"cn": "篇", "py": "piān", "pyPlain": "pian", "en": "sheet; piece of writing"},
  h4_77_3: {"cn": "儿童", "py": "ér tóng", "pyPlain": "ertong", "en": "child"},
  h4_77_4: {"cn": "最好", "py": "zuì hǎo", "pyPlain": "zuihao", "en": "best; (you) had better (do what we suggest)"},
  h4_77_5: {"cn": "味道", "py": "wèi dao", "pyPlain": "weidao", "en": "flavor; taste; (fig.) feeling (of ...); sense (of ...);…"},
  h4_77_6: {"cn": "断", "py": "duàn", "pyPlain": "duan", "en": "to break; to snap"},
  h4_77_7: {"cn": "千万", "py": "qiān wàn", "pyPlain": "qianwan", "en": "ten million; countless"},
  h4_77_8: {"cn": "出发", "py": "chū fā", "pyPlain": "chufa", "en": "to set off; to start (on a journey)"},
  h4_77_9: {"cn": "距离", "py": "jù lí", "pyPlain": "juli", "en": "distance; to be apart from"},
  h4_77_10: {"cn": "轻松", "py": "qīng sōng", "pyPlain": "qingsong", "en": "light; gentle"},
  h4_77_11: {"cn": "墙", "py": "qiáng", "pyPlain": "qiang", "en": "variant of 墙, wall"},
  h4_78_0: {"cn": "毕业", "py": "bì yè", "pyPlain": "biye", "en": "graduation; to graduate"},
  h4_78_1: {"cn": "怀疑", "py": "huái yí", "pyPlain": "huaiyi", "en": "to doubt (sth); to be skeptical of"},
  h4_78_2: {"cn": "修", "py": "Xiū", "pyPlain": "xiu", "en": "surname Xiu"},
  h4_78_3: {"cn": "价格", "py": "jià gé", "pyPlain": "jiage", "en": "price"},
  h4_78_4: {"cn": "戴", "py": "Dài", "pyPlain": "dai", "en": "surname Dai"},
  h4_78_5: {"cn": "究竟", "py": "jiū jìng", "pyPlain": "jiujing", "en": "to go to the bottom of a matter; after all"},
  h4_78_6: {"cn": "轻", "py": "qīng", "pyPlain": "qing", "en": "light; easy"},
  h4_78_7: {"cn": "然而", "py": "rán ér", "pyPlain": "raner", "en": "however; yet; but"},
  h4_78_8: {"cn": "交流", "py": "jiāo liú", "pyPlain": "jiaoliu", "en": "to exchange; exchange"},
  h4_78_9: {"cn": "兴奋", "py": "xīng fèn", "pyPlain": "xingfen", "en": "excited; excitement"},
  h4_78_10: {"cn": "困", "py": "kùn", "pyPlain": "kun", "en": "to trap; to surround"},
  h4_78_11: {"cn": "符合", "py": "fú hé", "pyPlain": "fuhe", "en": "in keeping with; in accordance with"},
  h4_79_0: {"cn": "躺", "py": "tǎng", "pyPlain": "tang", "en": "to recline; to lie down"},
  h4_79_1: {"cn": "答案", "py": "dá àn", "pyPlain": "daan", "en": "answer; solution"},
  h4_79_2: {"cn": "皮肤", "py": "pí fū", "pyPlain": "pifu", "en": "skin"},
  h4_79_3: {"cn": "浪费", "py": "làng fèi", "pyPlain": "langfei", "en": "to waste; to squander"},
  h4_79_4: {"cn": "厉害", "py": "lì hai", "pyPlain": "lihai", "en": "(used to describe sb or sth that makes a very strong…"},
  h4_79_5: {"cn": "尊重", "py": "zūn zhòng", "pyPlain": "zunzhong", "en": "to esteem; to respect"},
  h4_79_6: {"cn": "激动", "py": "jī dòng", "pyPlain": "jidong", "en": "to move emotionally; to stir up (emotions)"},
  h4_79_7: {"cn": "骗", "py": "piàn", "pyPlain": "pian", "en": "to cheat; to swindle"},
  h4_79_8: {"cn": "可怜", "py": "kě lián", "pyPlain": "kelian", "en": "pitiful; pathetic"},
  h4_79_9: {"cn": "语言", "py": "yǔ yán", "pyPlain": "yuyan", "en": "language"},
  h4_79_10: {"cn": "擦", "py": "cā", "pyPlain": "ca", "en": "to rub; to scratch; to towel; to wipe with a towel"},
  h4_79_11: {"cn": "香", "py": "xiāng", "pyPlain": "xiang", "en": "fragrant; sweet smelling"},
  h4_80_0: {"cn": "成熟", "py": "chéng shú", "pyPlain": "chengshu", "en": "mature; ripe; to mature; to ripen"},
  h4_80_1: {"cn": "无聊", "py": "wú liáo", "pyPlain": "wuliao", "en": "bored; boring"},
  h4_80_2: {"cn": "文章", "py": "wén zhāng", "pyPlain": "wenzhang", "en": "article; essay"},
  h4_80_3: {"cn": "信任", "py": "xìn rèn", "pyPlain": "xinren", "en": "to trust; to have confidence in"},
  h4_80_4: {"cn": "网站", "py": "wǎng zhàn", "pyPlain": "wangzhan", "en": "website; network station"},
  h4_80_5: {"cn": "地球", "py": "dì qiú", "pyPlain": "diqiu", "en": "the earth"},
  h4_80_6: {"cn": "实际", "py": "shí jì", "pyPlain": "shiji", "en": "reality; practice"},
  h4_80_7: {"cn": "年龄", "py": "nián líng", "pyPlain": "nianling", "en": "(a person's) age"},
  h4_80_8: {"cn": "差不多", "py": "chà bu duō", "pyPlain": "chabuduo", "en": "almost; nearly"},
  h4_80_9: {"cn": "可惜", "py": "kě xī", "pyPlain": "kexi", "en": "it is a pity; what a pity"},
  h4_80_10: {"cn": "阳光", "py": "yáng guāng", "pyPlain": "yangguang", "en": "sunshine; (of personality) upbeat; energetic"},
  h4_80_11: {"cn": "回忆", "py": "huí yì", "pyPlain": "huiyi", "en": "to recall; memories"},
  h4_81_0: {"cn": "空气", "py": "kōng qì", "pyPlain": "kongqi", "en": "air; atmosphere"},
  h4_81_1: {"cn": "材料", "py": "cái liào", "pyPlain": "cailiao", "en": "(raw) material; data"},
  h4_81_2: {"cn": "熟悉", "py": "shú xī", "pyPlain": "shuxi", "en": "to be familiar with; to know well"},
  h4_81_3: {"cn": "随便", "py": "suí biàn", "pyPlain": "suibian", "en": "as one wishes; as one pleases"},
  h4_81_4: {"cn": "撞", "py": "zhuàng", "pyPlain": "zhuang", "en": "to knock against; to bump into"},
  h4_81_5: {"cn": "互相", "py": "hù xiāng", "pyPlain": "huxiang", "en": "each other; mutually"},
  h4_81_6: {"cn": "合适", "py": "hé shì", "pyPlain": "heshi", "en": "suitable; fitting"},
  h4_81_7: {"cn": "失望", "py": "shī wàng", "pyPlain": "shiwang", "en": "disappointed; to lose hope"},
  h4_81_8: {"cn": "印象", "py": "yìn xiàng", "pyPlain": "yinxiang", "en": "impression (sth that stays in one's mind); a memory"},
  h4_81_9: {"cn": "号码", "py": "hào mǎ", "pyPlain": "haoma", "en": "number"},
  h4_81_10: {"cn": "出生", "py": "chū shēng", "pyPlain": "chusheng", "en": "to be born"},
  h4_81_11: {"cn": "桥", "py": "qiáo", "pyPlain": "qiao", "en": "bridge"},
  h4_82_0: {"cn": "基础", "py": "jī chǔ", "pyPlain": "jichu", "en": "base; foundation; basis; basic; fundamental"},
  h4_82_1: {"cn": "适应", "py": "shì yìng", "pyPlain": "shiying", "en": "to adapt; to fit"},
  h4_82_2: {"cn": "赚", "py": "zhuàn", "pyPlain": "zhuan", "en": "to earn; to make a profit"},
  h4_82_3: {"cn": "猜", "py": "cāi", "pyPlain": "cai", "en": "to guess"},
  h4_82_4: {"cn": "到处", "py": "dào chù", "pyPlain": "daochu", "en": "everywhere"},
  h4_82_5: {"cn": "食品", "py": "shí pǐn", "pyPlain": "shipin", "en": "foodstuff; food; provisions"},
  h4_82_6: {"cn": "大约", "py": "dà yuē", "pyPlain": "dayue", "en": "approximately; probably"},
  h4_82_7: {"cn": "提前", "py": "tí qián", "pyPlain": "tiqian", "en": "to shift to an earlier date; to do sth ahead of time"},
  h4_82_8: {"cn": "暂时", "py": "zàn shí", "pyPlain": "zanshi", "en": "temporary; provisional"},
  h4_82_9: {"cn": "积极", "py": "jī jí", "pyPlain": "jiji", "en": "active; energetic"},
  h4_82_10: {"cn": "高级", "py": "gāo jí", "pyPlain": "gaoji", "en": "high level; high grade"},
  h4_82_11: {"cn": "汤", "py": "Tāng", "pyPlain": "tang", "en": "surname Tang"},
  h4_83_0: {"cn": "响", "py": "xiǎng", "pyPlain": "xiang", "en": "echo; sound"},
  h4_83_1: {"cn": "收入", "py": "shōu rù", "pyPlain": "shouru", "en": "to take in; income"},
  h4_83_2: {"cn": "恐怕", "py": "kǒng pà", "pyPlain": "kongpa", "en": "fear; to dread"},
  h4_83_3: {"cn": "仔细", "py": "zǐ xì", "pyPlain": "zixi", "en": "careful; attentive; cautious; to be careful; to look out"},
  h4_83_4: {"cn": "严格", "py": "yán gé", "pyPlain": "yange", "en": "strict; stringent"},
  h4_83_5: {"cn": "及时", "py": "jí shí", "pyPlain": "jishi", "en": "timely; at the right time; promptly; without delay"},
  h4_83_6: {"cn": "知识", "py": "zhī shi", "pyPlain": "zhishi", "en": "knowledge; intellectual"},
  h4_83_7: {"cn": "专门", "py": "zhuān mén", "pyPlain": "zhuanmen", "en": "specialist; specialized"},
  h4_83_8: {"cn": "工具", "py": "gōng jù", "pyPlain": "gongju", "en": "tool; instrument"},
  h4_83_9: {"cn": "脱", "py": "tuō", "pyPlain": "tuo", "en": "to shed; to take off"},
  h4_83_10: {"cn": "苦", "py": "kǔ", "pyPlain": "ku", "en": "bitter; hardship"},
  h4_83_11: {"cn": "租", "py": "zū", "pyPlain": "zu", "en": "to hire; to rent"},
  h4_84_0: {"cn": "尤其", "py": "yóu qí", "pyPlain": "youqi", "en": "especially; particularly"},
  h4_84_1: {"cn": "页", "py": "xié", "pyPlain": "xie", "en": "head"},
  h4_84_2: {"cn": "扔", "py": "rēng", "pyPlain": "reng", "en": "to throw; to throw away"},
  h4_84_3: {"cn": "信心", "py": "xìn xīn", "pyPlain": "xinxin", "en": "confidence; faith (in sb or sth)"},
  h4_84_4: {"cn": "博士", "py": "bó shì", "pyPlain": "boshi", "en": "doctor; court academician (in feudal China)"},
  h4_84_5: {"cn": "故意", "py": "gù yì", "pyPlain": "guyi", "en": "deliberately; on purpose"},
  h4_84_6: {"cn": "看法", "py": "kàn fǎ", "pyPlain": "kanfa", "en": "way of looking at a thing; view"},
  h4_84_7: {"cn": "浪漫", "py": "làng màn", "pyPlain": "langman", "en": "romantic"},
  h4_84_8: {"cn": "减少", "py": "jiǎn shǎo", "pyPlain": "jianshao", "en": "to lessen; to decrease; to reduce; to lower"},
  h4_84_9: {"cn": "辛苦", "py": "xīn kǔ", "pyPlain": "xinku", "en": "exhausting; hard"},
  h4_84_10: {"cn": "剩", "py": "shèng", "pyPlain": "sheng", "en": "to remain; to be left"},
  h4_84_11: {"cn": "正好", "py": "zhèng hǎo", "pyPlain": "zhenghao", "en": "just (in time); just right"},
  h4_85_0: {"cn": "主动", "py": "zhǔ dòng", "pyPlain": "zhudong", "en": "to take the initiative; to do sth of one's own accord"},
  h4_85_1: {"cn": "硬", "py": "yìng", "pyPlain": "ying", "en": "hard; stiff; solid; (fig.) strong; firm"},
  h4_85_2: {"cn": "限制", "py": "xiàn zhì", "pyPlain": "xianzhi", "en": "to restrict; to limit"},
  h4_85_3: {"cn": "判断", "py": "pàn duàn", "pyPlain": "panduan", "en": "to judge; to determine"},
  h4_85_4: {"cn": "现代", "py": "Xiàn dài", "pyPlain": "xiandai", "en": "Hyundai, South Korean company"},
  h4_85_5: {"cn": "弹", "py": "dàn", "pyPlain": "dan", "en": "crossball; bullet"},
  h4_85_6: {"cn": "有趣", "py": "yǒu qù", "pyPlain": "youqu", "en": "interesting; fascinating"},
  h4_85_7: {"cn": "公里", "py": "gōng lǐ", "pyPlain": "gongli", "en": "kilometer"},
  h4_85_8: {"cn": "工资", "py": "gōng zī", "pyPlain": "gongzi", "en": "wages; pay"},
  h4_85_9: {"cn": "好处", "py": "hǎo chǔ", "pyPlain": "haochu", "en": "easy to get along with"},
  h4_85_10: {"cn": "伤心", "py": "shāng xīn", "pyPlain": "shangxin", "en": "to grieve; to be broken-hearted"},
  h4_85_11: {"cn": "区别", "py": "qū bié", "pyPlain": "qubie", "en": "difference; to distinguish"},
  h4_86_0: {"cn": "暗", "py": "àn", "pyPlain": "an", "en": "variant of 暗"},
  h4_86_1: {"cn": "将来", "py": "jiāng lái", "pyPlain": "jianglai", "en": "in the future; future"},
  h4_86_2: {"cn": "聊天", "py": "liáo tiān", "pyPlain": "liaotian", "en": "to chat; to gossip"},
  h4_86_3: {"cn": "小说", "py": "xiǎo shuō", "pyPlain": "xiaoshuo", "en": "novel; fiction"},
  h4_86_4: {"cn": "鼓励", "py": "gǔ lì", "pyPlain": "guli", "en": "to encourage"},
  h4_86_5: {"cn": "理想", "py": "lǐ xiǎng", "pyPlain": "lixiang", "en": "an ideal; a dream"},
  h4_86_6: {"cn": "后悔", "py": "hòu huǐ", "pyPlain": "houhui", "en": "to regret; to feel remorse"},
  h4_86_7: {"cn": "举办", "py": "jǔ bàn", "pyPlain": "juban", "en": "to conduct; to hold"},
  h4_86_8: {"cn": "感动", "py": "gǎn dòng", "pyPlain": "gandong", "en": "to move (sb); to touch (sb emotionally)"},
  h4_86_9: {"cn": "顾客", "py": "gù kè", "pyPlain": "guke", "en": "customer; client"},
  h4_86_10: {"cn": "组成", "py": "zǔ chéng", "pyPlain": "zucheng", "en": "to form; to make up"},
  h4_86_11: {"cn": "流行", "py": "liú xíng", "pyPlain": "liuxing", "en": "(of a contagious disease etc) to spread; to propagate"},
  h4_87_0: {"cn": "整理", "py": "zhěng lǐ", "pyPlain": "zhengli", "en": "to arrange; to tidy up"},
  h4_87_1: {"cn": "吵", "py": "chǎo", "pyPlain": "chao", "en": "to quarrel; to make a noise"},
  h4_87_2: {"cn": "丰富", "py": "fēng fù", "pyPlain": "fengfu", "en": "to enrich; rich"},
  h4_87_3: {"cn": "原谅", "py": "yuán liàng", "pyPlain": "yuanliang", "en": "to excuse; to forgive"},
  h4_87_4: {"cn": "肚子", "py": "dù zi", "pyPlain": "duzi", "en": "belly; abdomen"},
  h4_87_5: {"cn": "平时", "py": "píng shí", "pyPlain": "pingshi", "en": "ordinarily; in normal times"},
  h4_87_6: {"cn": "辣", "py": "là", "pyPlain": "la", "en": "old variant of 辣"},
  h4_87_7: {"cn": "作者", "py": "zuò zhě", "pyPlain": "zuozhe", "en": "author; writer"},
  h4_87_8: {"cn": "质量", "py": "zhì liàng", "pyPlain": "zhiliang", "en": "quality; (physics) mass"},
  h4_87_9: {"cn": "愉快", "py": "yú kuài", "pyPlain": "yukuai", "en": "cheerful; cheerily"},
  h4_87_10: {"cn": "寄", "py": "jì", "pyPlain": "ji", "en": "to send; to mail"},
  h4_87_11: {"cn": "准确", "py": "zhǔn què", "pyPlain": "zhunque", "en": "accurate; exact; precise"},
  h4_88_0: {"cn": "详细", "py": "xiáng xì", "pyPlain": "xiangxi", "en": "detailed; in detail"},
  h4_88_1: {"cn": "禁止", "py": "jìn zhǐ", "pyPlain": "jinzhi", "en": "to prohibit; to forbid"},
  h4_88_2: {"cn": "圆", "py": "yuán", "pyPlain": "yuan", "en": "circle; round"},
  h4_88_3: {"cn": "冷静", "py": "lěng jìng", "pyPlain": "lengjing", "en": "calm; cool-headed; dispassionate; (of a place) deserted;…"},
  h4_88_4: {"cn": "购物", "py": "gòu wù", "pyPlain": "gouwu", "en": "shopping"},
  h4_88_5: {"cn": "数量", "py": "shù liàng", "pyPlain": "shuliang", "en": "amount; quantity"},
  h4_88_6: {"cn": "勇敢", "py": "yǒng gǎn", "pyPlain": "yonggan", "en": "brave; courageous"},
  h4_88_7: {"cn": "巧克力", "py": "qiǎo kè lì", "pyPlain": "qiaokeli", "en": "chocolate (loanword)"},
  h4_88_8: {"cn": "富", "py": "Fù", "pyPlain": "fu", "en": "surname Fu"},
  h4_88_9: {"cn": "骄傲", "py": "jiāo ào", "pyPlain": "jiaoao", "en": "pride; arrogance"},
  h4_88_10: {"cn": "性格", "py": "xìng gé", "pyPlain": "xingge", "en": "nature; disposition"},
  h4_88_11: {"cn": "降低", "py": "jiàng dī", "pyPlain": "jiangdi", "en": "to reduce; to lower; to bring down"},
  h4_89_0: {"cn": "果然", "py": "guǒ rán", "pyPlain": "guoran", "en": "really; sure enough"},
  h4_89_1: {"cn": "随着", "py": "suí zhe", "pyPlain": "suizhe", "en": "along with; in the wake of"},
  h4_89_2: {"cn": "只好", "py": "zhǐ hǎo", "pyPlain": "zhihao", "en": "to have no other option but to ...; to have to; to be…"},
  h4_89_3: {"cn": "密码", "py": "mì mǎ", "pyPlain": "mima", "en": "cipher; secret code; password; PIN"},
  h4_89_4: {"cn": "亚洲", "py": "Yà zhōu", "pyPlain": "yazhou", "en": "Asia (abbr. for 亚细亚洲)"},
  h4_89_5: {"cn": "道歉", "py": "dào qiàn", "pyPlain": "daoqian", "en": "to apologize"},
  h4_89_6: {"cn": "趟", "py": "tāng", "pyPlain": "tang", "en": "old variant of 趟"},
  h4_89_7: {"cn": "软", "py": "ruǎn", "pyPlain": "ruan", "en": "soft; flexible"},
  h4_89_8: {"cn": "访问", "py": "fǎng wèn", "pyPlain": "fangwen", "en": "to visit; to call on"},
  h4_89_9: {"cn": "森林", "py": "sēn lín", "pyPlain": "senlin", "en": "forest"},
  h4_89_10: {"cn": "友好", "py": "Yǒu hǎo", "pyPlain": "youhao", "en": "Youhao district of Yichun city 市, Heilongjiang"},
  h4_89_11: {"cn": "尝", "py": "cháng", "pyPlain": "chang", "en": "to taste; to try (food); to experience"},
  h4_90_0: {"cn": "亿", "py": "yì", "pyPlain": "yi", "en": "100 million"},
  h4_90_1: {"cn": "对话", "py": "duì huà", "pyPlain": "duihua", "en": "to talk (with sb); dialogue; conversation"},
  h4_90_2: {"cn": "收拾", "py": "shōu shi", "pyPlain": "shoushi", "en": "to put in order; to tidy up"},
  h4_90_3: {"cn": "广播", "py": "guǎng bō", "pyPlain": "guangbo", "en": "broadcast; broadcasting"},
  h4_90_4: {"cn": "逐渐", "py": "zhú jiàn", "pyPlain": "zhujian", "en": "gradually"},
  h4_90_5: {"cn": "钥匙", "py": "yào shi", "pyPlain": "yaoshi", "en": "key"},
  h4_90_6: {"cn": "酸", "py": "suān", "pyPlain": "suan", "en": "sour; tart"},
  h4_90_7: {"cn": "污染", "py": "wū rǎn", "pyPlain": "wuran", "en": "to pollute; to contaminate (lit. and fig.)"},
  h4_90_8: {"cn": "温度", "py": "wēn dù", "pyPlain": "wendu", "en": "temperature"},
  h4_90_9: {"cn": "孤单", "py": "gū dān", "pyPlain": "gudan", "en": "lone; lonely"},
  h4_90_10: {"cn": "饮料", "py": "yǐn liào", "pyPlain": "yinliao", "en": "drink; beverage"},
  h4_90_11: {"cn": "宽", "py": "Kuān", "pyPlain": "kuan", "en": "surname Kuan"},
  h4_91_0: {"cn": "例如", "py": "lì rú", "pyPlain": "liru", "en": "for example; for instance; such as"},
  h4_91_1: {"cn": "祝贺", "py": "zhù hè", "pyPlain": "zhuhe", "en": "to congratulate; congratulations"},
  h4_91_2: {"cn": "批评", "py": "pī píng", "pyPlain": "piping", "en": "to criticize; criticism"},
  h4_91_3: {"cn": "重视", "py": "zhòng shì", "pyPlain": "zhongshi", "en": "to attach importance to sth; to value"},
  h4_91_4: {"cn": "增长", "py": "zēng zhǎng", "pyPlain": "zengzhang", "en": "to grow; to increase"},
  h4_91_5: {"cn": "相反", "py": "xiāng fǎn", "pyPlain": "xiangfan", "en": "opposite; contrary"},
  h4_91_6: {"cn": "抬", "py": "tái", "pyPlain": "tai", "en": "to lift; to raise"},
  h4_91_7: {"cn": "主意", "py": "zhǔ yi", "pyPlain": "zhuyi", "en": "plan; idea"},
  h4_91_8: {"cn": "扩大", "py": "kuò dà", "pyPlain": "kuoda", "en": "to expand; to enlarge"},
  h4_91_9: {"cn": "奖金", "py": "jiǎng jīn", "pyPlain": "jiangjin", "en": "premium; award money"},
  h4_91_10: {"cn": "盐", "py": "yán", "pyPlain": "yan", "en": "salt"},
  h4_91_11: {"cn": "难受", "py": "nán shòu", "pyPlain": "nanshou", "en": "to feel unwell; to suffer pain"},
  h4_92_0: {"cn": "民族", "py": "mín zú", "pyPlain": "minzu", "en": "nationality; ethnic group"},
  h4_92_1: {"cn": "航班", "py": "háng bān", "pyPlain": "hangban", "en": "(scheduled) flight; (scheduled) sailing"},
  h4_92_2: {"cn": "偶尔", "py": "ǒu ěr", "pyPlain": "ouer", "en": "occasionally; once in a while"},
  h4_92_3: {"cn": "约会", "py": "yuē huì", "pyPlain": "yuehui", "en": "appointment; engagement"},
  h4_92_4: {"cn": "受不了", "py": "shòu bù liǎo", "pyPlain": "shoubuliao", "en": "unbearable; unable to endure"},
  h4_92_5: {"cn": "厚", "py": "hòu", "pyPlain": "hou", "en": "thick; deep or profound"},
  h4_92_6: {"cn": "护士", "py": "hù shi", "pyPlain": "hushi", "en": "nurse"},
  h4_92_7: {"cn": "参观", "py": "cān guān", "pyPlain": "canguan", "en": "to look around; to tour"},
  h4_92_8: {"cn": "顺便", "py": "shùn biàn", "pyPlain": "shunbian", "en": "conveniently; in passing"},
  h4_92_9: {"cn": "友谊", "py": "yǒu yì", "pyPlain": "youyi", "en": "companionship; fellowship"},
  h4_92_10: {"cn": "笨", "py": "bèn", "pyPlain": "ben", "en": "stupid; foolish"},
  h4_92_11: {"cn": "沙发", "py": "shā fā", "pyPlain": "shafa", "en": "sofa (loanword); (Internet slang) the first reply or…"},
  h4_93_0: {"cn": "耐心", "py": "nài xīn", "pyPlain": "naixin", "en": "to be patient; patience"},
  h4_93_1: {"cn": "开玩笑", "py": "kāi wán xiào", "pyPlain": "kaiwanxiao", "en": "to play a joke; to make fun of"},
  h4_93_2: {"cn": "反映", "py": "fǎn yìng", "pyPlain": "fanying", "en": "to mirror; to reflect"},
  h4_93_3: {"cn": "植物", "py": "zhí wù", "pyPlain": "zhiwu", "en": "plant; vegetation"},
  h4_93_4: {"cn": "笔记本", "py": "bǐ jì běn", "pyPlain": "bijiben", "en": "notebook (stationery); notebook (computing)"},
  h4_93_5: {"cn": "对面", "py": "duì miàn", "pyPlain": "duimian", "en": "(sitting) opposite; across (the street)"},
  h4_93_6: {"cn": "信用卡", "py": "xìn yòng kǎ", "pyPlain": "xinyongka", "en": "credit card"},
  h4_93_7: {"cn": "减肥", "py": "jiǎn féi", "pyPlain": "jianfei", "en": "to lose weight"},
  h4_93_8: {"cn": "其次", "py": "qí cì", "pyPlain": "qici", "en": "next; secondly"},
  h4_93_9: {"cn": "敲", "py": "qiāo", "pyPlain": "qiao", "en": "to hit; to strike"},
  h4_93_10: {"cn": "脾气", "py": "pí qi", "pyPlain": "piqi", "en": "character; temperament"},
  h4_93_11: {"cn": "翻译", "py": "fān yì", "pyPlain": "fanyi", "en": "to translate; to interpret"},
  h4_94_0: {"cn": "烦恼", "py": "fán nǎo", "pyPlain": "fannao", "en": "to be worried; to be distressed"},
  h4_94_1: {"cn": "特点", "py": "tè diǎn", "pyPlain": "tedian", "en": "characteristic (feature); trait"},
  h4_94_2: {"cn": "往往", "py": "wǎng wǎng", "pyPlain": "wangwang", "en": "usually; in many cases"},
  h4_94_3: {"cn": "风景", "py": "fēng jǐng", "pyPlain": "fengjing", "en": "scenery; landscape"},
  h4_94_4: {"cn": "笑话", "py": "xiào hua", "pyPlain": "xiaohua", "en": "joke; jest; to laugh at; to mock"},
  h4_94_5: {"cn": "海洋", "py": "hǎi yáng", "pyPlain": "haiyang", "en": "ocean"},
  h4_94_6: {"cn": "窗户", "py": "chuāng hu", "pyPlain": "chuanghu", "en": "window"},
  h4_94_7: {"cn": "不但", "py": "bù dàn", "pyPlain": "budan", "en": "not only (... but also ...)"},
  h4_94_8: {"cn": "代替", "py": "dài tì", "pyPlain": "daiti", "en": "to replace; to take the place of"},
  h4_94_9: {"cn": "家具", "py": "jiā jù", "pyPlain": "jiaju", "en": "furniture"},
  h4_94_10: {"cn": "棵", "py": "kē", "pyPlain": "ke", "en": "classifier for trees, cabbages, plants etc"},
  h4_94_11: {"cn": "商量", "py": "shāng liang", "pyPlain": "shangliang", "en": "to consult; to talk over"},
  h4_95_0: {"cn": "狮子", "py": "Shī zǐ", "pyPlain": "shizi", "en": "Leo (star sign); Shihtzu township in Pingtung County…"},
  h4_95_1: {"cn": "稍微", "py": "shāo wēi", "pyPlain": "shaowei", "en": "a little bit"},
  h4_95_2: {"cn": "汗", "py": "hán", "pyPlain": "han", "en": "see 汗, 汗国"},
  h4_95_3: {"cn": "缺少", "py": "quē shǎo", "pyPlain": "queshao", "en": "lack; shortage of"},
  h4_95_4: {"cn": "阅读", "py": "yuè dú", "pyPlain": "yuedu", "en": "to read; reading"},
  h4_95_5: {"cn": "穷", "py": "qióng", "pyPlain": "qiong", "en": "poor; destitute"},
  h4_95_6: {"cn": "打扮", "py": "dǎ ban", "pyPlain": "daban", "en": "to decorate; to dress"},
  h4_95_7: {"cn": "座位", "py": "zuò wèi", "pyPlain": "zuowei", "en": "seat"},
  h4_95_8: {"cn": "首都", "py": "shǒu dū", "pyPlain": "shoudu", "en": "capital (city)"},
  h4_95_9: {"cn": "吃惊", "py": "chī jīng", "pyPlain": "chijing", "en": "to be startled; to be shocked"},
  h4_95_10: {"cn": "忽然", "py": "hū rán", "pyPlain": "huran", "en": "suddenly; all of a sudden"},
  h4_95_11: {"cn": "羡慕", "py": "xiàn mù", "pyPlain": "xianmu", "en": "to envy; to admire"},
  h4_96_0: {"cn": "报名", "py": "bào míng", "pyPlain": "baoming", "en": "to sign up; to enter one's name"},
  h4_96_1: {"cn": "脏", "py": "zàng", "pyPlain": "zang", "en": "viscera; (anatomy) organ"},
  h4_96_2: {"cn": "极其", "py": "jí qí", "pyPlain": "jiqi", "en": "extremely"},
  h4_96_3: {"cn": "日记", "py": "rì jì", "pyPlain": "riji", "en": "diary"},
  h4_96_4: {"cn": "同情", "py": "tóng qíng", "pyPlain": "tongqing", "en": "to sympathize with; sympathy"},
  h4_96_5: {"cn": "逛", "py": "guàng", "pyPlain": "guang", "en": "to stroll; to visit"},
  h4_96_6: {"cn": "总结", "py": "zǒng jié", "pyPlain": "zongjie", "en": "to sum up; to conclude"},
  h4_96_7: {"cn": "打扰", "py": "dǎ rǎo", "pyPlain": "darao", "en": "to disturb; to bother"},
  h4_96_8: {"cn": "幽默", "py": "yōu mò", "pyPlain": "youmo", "en": "(loanword) humor; humorous"},
  h4_96_9: {"cn": "误会", "py": "wù huì", "pyPlain": "wuhui", "en": "to misunderstand; to mistake"},
  h4_96_10: {"cn": "抱歉", "py": "bào qiàn", "pyPlain": "baoqian", "en": "to be sorry; to feel apologetic"},
  h4_96_11: {"cn": "师傅", "py": "shī fu", "pyPlain": "shifu", "en": "master; qualified worker"},
  h4_97_0: {"cn": "朵", "py": "duǒ", "pyPlain": "duo", "en": "flower; earlobe"},
  h4_97_1: {"cn": "镜子", "py": "jìng zi", "pyPlain": "jingzi", "en": "mirror"},
  h4_97_2: {"cn": "合格", "py": "hé gé", "pyPlain": "hege", "en": "to meet the standard required; qualified"},
  h4_97_3: {"cn": "亲戚", "py": "qīn qi", "pyPlain": "qinqi", "en": "a relative (i.e. family relation)"},
  h4_97_4: {"cn": "力气", "py": "lì qi", "pyPlain": "liqi", "en": "strength"},
  h4_97_5: {"cn": "缺点", "py": "quē diǎn", "pyPlain": "quedian", "en": "weak point; fault"},
  h4_97_6: {"cn": "抽烟", "py": "chōu yān", "pyPlain": "chouyan", "en": "to smoke (a cigarette, tobacco)"},
  h4_97_7: {"cn": "起飞", "py": "qǐ fēi", "pyPlain": "qifei", "en": "(of an aircraft) to take off"},
  h4_97_8: {"cn": "网球", "py": "wǎng qiú", "pyPlain": "wangqiu", "en": "tennis; tennis ball"},
  h4_97_9: {"cn": "老虎", "py": "lǎo hǔ", "pyPlain": "laohu", "en": "tiger"},
  h4_97_10: {"cn": "乘坐", "py": "chéng zuò", "pyPlain": "chengzuo", "en": "to ride (in a vehicle)"},
  h4_97_11: {"cn": "诚实", "py": "chéng shí", "pyPlain": "chengshi", "en": "honest"},
  h4_98_0: {"cn": "集合", "py": "jí hé", "pyPlain": "jihe", "en": "to gather; to assemble; (math.) set"},
  h4_98_1: {"cn": "孙子", "py": "Sūn zǐ", "pyPlain": "sunzi", "en": "Sun Tzu, also known as Sun Wu 孙武 (c. 500 BC, dates of…"},
  h4_98_2: {"cn": "优点", "py": "yōu diǎn", "pyPlain": "youdian", "en": "merit; benefit"},
  h4_98_3: {"cn": "猴子", "py": "hóu zi", "pyPlain": "houzi", "en": "monkey"},
  h4_98_4: {"cn": "来不及", "py": "lái bu jí", "pyPlain": "laibuji", "en": "there's not enough time (to do sth); it's too late (to…"},
  h4_98_5: {"cn": "普遍", "py": "pǔ biàn", "pyPlain": "pubian", "en": "universal; general"},
  h4_98_6: {"cn": "入口", "py": "rù kǒu", "pyPlain": "rukou", "en": "entrance; to import"},
  h4_98_7: {"cn": "加班", "py": "jiā bān", "pyPlain": "jiaban", "en": "to work overtime"},
  h4_98_8: {"cn": "热闹", "py": "rè nao", "pyPlain": "renao", "en": "bustling with noise and excitement; lively"},
  h4_98_9: {"cn": "散步", "py": "sàn bù", "pyPlain": "sanbu", "en": "to take a walk; to go for a walk"},
  h4_98_10: {"cn": "顺序", "py": "shùn xù", "pyPlain": "shunxu", "en": "sequence; order"},
  h4_98_11: {"cn": "懒", "py": "lǎn", "pyPlain": "lan", "en": "variant of 懒"},
  h4_99_0: {"cn": "大夫", "py": "dà fū", "pyPlain": "dafu", "en": "senior official (in imperial China)"},
  h4_99_1: {"cn": "准时", "py": "zhǔn shí", "pyPlain": "zhunshi", "en": "on time; punctual"},
  h4_99_2: {"cn": "盒子", "py": "hé zi", "pyPlain": "hezi", "en": "box; case"},
  h4_99_3: {"cn": "得意", "py": "dé yì", "pyPlain": "deyi", "en": "proud of oneself; pleased with oneself"},
  h4_99_4: {"cn": "礼貌", "py": "lǐ mào", "pyPlain": "limao", "en": "courtesy; politeness; manners; courteous; polite"},
  h4_99_5: {"cn": "推迟", "py": "tuī chí", "pyPlain": "tuichi", "en": "to postpone; to put off"},
  h4_99_6: {"cn": "饼干", "py": "bǐng gān", "pyPlain": "binggan", "en": "biscuit; cracker; cookie"},
  h4_99_7: {"cn": "中文", "py": "Zhōng wén", "pyPlain": "zhongwen", "en": "Chinese language"},
  h4_99_8: {"cn": "性别", "py": "xìng bié", "pyPlain": "xingbie", "en": "gender; sex"},
  h4_99_9: {"cn": "袜子", "py": "wà zi", "pyPlain": "wazi", "en": "socks; stockings"},
  h4_99_10: {"cn": "气候", "py": "qì hòu", "pyPlain": "qihou", "en": "(meteorology) climate; (fig.) climate; prevailing…"},
  h4_99_11: {"cn": "毛巾", "py": "máo jīn", "pyPlain": "maojin", "en": "towel"},
  h4_100_0: {"cn": "鼓掌", "py": "gǔ zhǎng", "pyPlain": "guzhang", "en": "to applaud; to clap"},
  h4_100_1: {"cn": "瓶子", "py": "píng zi", "pyPlain": "pingzi", "en": "bottle"},
  h4_100_2: {"cn": "传真", "py": "chuán zhēn", "pyPlain": "chuanzhen", "en": "fax; facsimile"},
  h4_100_3: {"cn": "害羞", "py": "hài xiū", "pyPlain": "haixiu", "en": "shy; embarrassed"},
  h4_100_4: {"cn": "握手", "py": "wò shǒu", "pyPlain": "woshou", "en": "to shake hands"},
  h4_100_5: {"cn": "来得及", "py": "lái de jí", "pyPlain": "laideji", "en": "to have enough time; can do it in time; can still make it"},
  h4_100_6: {"cn": "咳嗽", "py": "ké sou", "pyPlain": "kesou", "en": "to cough"},
  h4_100_7: {"cn": "研究生", "py": "yán jiū shēng", "pyPlain": "yanjiusheng", "en": "graduate student; postgraduate student"},
  h4_100_8: {"cn": "出差", "py": "chū chāi", "pyPlain": "chuchai", "en": "to go on an official or business trip"},
  h4_100_9: {"cn": "按时", "py": "àn shí", "pyPlain": "anshi", "en": "on time; before deadline"},
  h4_100_10: {"cn": "流泪", "py": "liú lèi", "pyPlain": "liulei", "en": "to shed tears"},
  h4_100_11: {"cn": "咸", "py": "Xián", "pyPlain": "xian", "en": "surname Xian"},
  h4_101_0: {"cn": "加油站", "py": "jiā yóu zhàn", "pyPlain": "jiayouzhan", "en": "gas station"},
  h4_101_1: {"cn": "节约", "py": "jié yuē", "pyPlain": "jieyue", "en": "to economize; to conserve (resources)"},
  h4_101_2: {"cn": "招聘", "py": "zhāo pìn", "pyPlain": "zhaopin", "en": "to invite applications for a job; to recruit"},
  h4_101_3: {"cn": "活泼", "py": "huó po", "pyPlain": "huopo", "en": "lively; vivacious"},
  h4_101_4: {"cn": "干燥", "py": "gān zào", "pyPlain": "ganzao", "en": "to dry (of weather, paint, cement etc); desiccation"},
  h4_101_5: {"cn": "签证", "py": "qiān zhèng", "pyPlain": "qianzheng", "en": "visa; to issue a visa"},
  h4_101_6: {"cn": "暖和", "py": "nuǎn huo", "pyPlain": "nuanhuo", "en": "warm; nice and warm"},
  h4_101_7: {"cn": "打印", "py": "dǎ yìn", "pyPlain": "dayin", "en": "to affix a seal; to stamp"},
  h4_101_8: {"cn": "农村", "py": "nóng cūn", "pyPlain": "nongcun", "en": "rural area; village"},
  h4_101_9: {"cn": "排列", "py": "pái liè", "pyPlain": "pailie", "en": "to arrange in order; (math.) permutation"},
  h4_101_10: {"cn": "窄", "py": "zhǎi", "pyPlain": "zhai", "en": "narrow; narrow-minded"},
  h4_101_11: {"cn": "积累", "py": "jī lěi", "pyPlain": "jilei", "en": "to accumulate; accumulation"},
  h4_102_0: {"cn": "整齐", "py": "zhěng qí", "pyPlain": "zhengqi", "en": "orderly; neat"},
  h4_102_1: {"cn": "表格", "py": "biǎo gé", "pyPlain": "biaoge", "en": "form; table"},
  h4_102_2: {"cn": "表扬", "py": "biǎo yáng", "pyPlain": "biaoyang", "en": "to praise; to commend"},
  h4_102_3: {"cn": "硕士", "py": "shuò shì", "pyPlain": "shuoshi", "en": "master's degree; person who has a master's degree"},
  h4_102_4: {"cn": "牙膏", "py": "yá gāo", "pyPlain": "yagao", "en": "toothpaste"},
  h4_102_5: {"cn": "长城", "py": "Cháng chéng", "pyPlain": "changcheng", "en": "the Great Wall"},
  h4_102_6: {"cn": "做生意", "py": "zuò shēng yì", "pyPlain": "zuoshengyi", "en": "to do business"},
  h4_102_7: {"cn": "请客", "py": "qǐng kè", "pyPlain": "qingke", "en": "to give a dinner party; to entertain guests"},
  h4_102_8: {"cn": "请假", "py": "qǐng jià", "pyPlain": "qingjia", "en": "to request leave of absence"},
  h4_102_9: {"cn": "乒乓球", "py": "pīng pāng qiú", "pyPlain": "pingpangqiu", "en": "table tennis; ping-pong"},
  h4_102_10: {"cn": "导游", "py": "dǎo yóu", "pyPlain": "daoyou", "en": "tour guide; guidebook"},
  h4_102_11: {"cn": "叶子", "py": "yè zi", "pyPlain": "yezi", "en": "leaf; (slang) marijuana"},
  h4_103_0: {"cn": "打折", "py": "dǎ zhé", "pyPlain": "dazhe", "en": "to give a discount"},
  h4_103_1: {"cn": "洗衣机", "py": "xǐ yī jī", "pyPlain": "xiyiji", "en": "washing machine; washer"},
  h4_103_2: {"cn": "堵车", "py": "dǔ chē", "pyPlain": "duche", "en": "traffic jam; (of traffic) to get congested"},
  h4_103_3: {"cn": "西红柿", "py": "xī hóng shì", "pyPlain": "xihongshi", "en": "tomato"},
  h4_103_4: {"cn": "个子", "py": "gè zi", "pyPlain": "gezi", "en": "height; stature"},
  h4_103_5: {"cn": "大使馆", "py": "dà shǐ guǎn", "pyPlain": "dashiguan", "en": "embassy"},
  h4_103_6: {"cn": "饺子", "py": "jiǎo zi", "pyPlain": "jiaozi", "en": "dumpling; pot-sticker"},
  h4_103_7: {"cn": "垃圾桶", "py": "lā jī tǒng", "pyPlain": "lajitong", "en": "rubbish bin; trash can"},
  h4_103_8: {"cn": "塑料袋", "py": "sù liào dài", "pyPlain": "suliaodai", "en": "plastic bag"},
  h4_103_9: {"cn": "养成", "py": "yǎng chéng", "pyPlain": "yangcheng", "en": "to cultivate; to raise"},
  h4_103_10: {"cn": "打针", "py": "dǎ zhēn", "pyPlain": "dazhen", "en": "to give or have an injection"},
  h4_103_11: {"cn": "理发", "py": "lǐ fà", "pyPlain": "lifa", "en": "to get a haircut; to have one's hair done; to cut (sb's)…"},
  h4_104_0: {"cn": "语法", "py": "yǔ fǎ", "pyPlain": "yufa", "en": "grammar"},
  h4_104_1: {"cn": "干杯", "py": "gān bēi", "pyPlain": "ganbei", "en": "to drink a toast; Cheers! (proposing a toast)"},
  h4_104_2: {"cn": "复印", "py": "fù yìn", "pyPlain": "fuyin", "en": "to photocopy; to duplicate a document"},
  h4_104_3: {"cn": "留学", "py": "liú xué", "pyPlain": "liuxue", "en": "to study abroad"},
  h4_104_4: {"cn": "湿润", "py": "shī rùn", "pyPlain": "shirun", "en": "moist"},
  h4_104_5: {"cn": "羽毛球", "py": "yǔ máo qiú", "pyPlain": "yumaoqiu", "en": "shuttlecock; badminton"},
  h4_104_6: {"cn": "流利", "py": "liú lì", "pyPlain": "liuli", "en": "fluent"},
  h4_104_7: {"cn": "词典", "py": "cí diǎn", "pyPlain": "cidian", "en": "dictionary; also written 辞典"},
  h4_104_8: {"cn": "凉快", "py": "liáng kuai", "pyPlain": "liangkuai", "en": "nice and cold; pleasantly cool"},
  h4_104_9: {"cn": "售货员", "py": "shòu huò yuán", "pyPlain": "shouhuoyuan", "en": "salesperson"},
  h4_104_10: {"cn": "长江", "py": "Cháng Jiāng", "pyPlain": "changjiang", "en": "Yangtze River, or Chang Jiang"},
  h4_104_11: {"cn": "马虎", "py": "mǎ hu", "pyPlain": "mahu", "en": "careless; sloppy"},
  h4_105_0: {"cn": "寒假", "py": "hán jià", "pyPlain": "hanjia", "en": "winter vacation"},
  h4_105_1: {"cn": "人民币", "py": "rén mín bì", "pyPlain": "renminbi", "en": "Renminbi (RMB); Chinese Yuan (CNY)"},
  h4_105_2: {"cn": "粗心", "py": "cū xīn", "pyPlain": "cuxin", "en": "careless; thoughtless"},
  h4_105_3: {"cn": "预习", "py": "yù xí", "pyPlain": "yuxi", "en": "to prepare a lesson"},
  h4_105_4: {"cn": "京剧", "py": "Jīng jù", "pyPlain": "jingju", "en": "Beijing opera"},
  h4_105_5: {"cn": "分之", "py": "fēn zhī", "pyPlain": "fenzhi", "en": "(indicating a fraction)"},
  h4_105_6: {"cn": "填空", "py": "tián kòng", "pyPlain": "tiankong", "en": "to fill a job vacancy; to fill in a blank (e.g. on…"},
  h4_105_7: {"cn": "放暑假", "py": "fàng shǔ jià", "pyPlain": "fangshujia", "en": "to be on summer vacation"}
});

window.UNITS.push(
  { id: "u56", title: "HSK 4 \u00b7 Set 1", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_56_0", "h4_56_1", "h4_56_2", "h4_56_3", "h4_56_4", "h4_56_5", "h4_56_6", "h4_56_7", "h4_56_8", "h4_56_9", "h4_56_10", "h4_56_11"],
    hanzi: ["过", "与", "当", "之"] },
  { id: "u57", title: "HSK 4 \u00b7 Set 2", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_57_0", "h4_57_1", "h4_57_2", "h4_57_3", "h4_57_4", "h4_57_5", "h4_57_6", "h4_57_7", "h4_57_8", "h4_57_9", "h4_57_10", "h4_57_11"],
    hanzi: ["所", "情", "况", "最"] },
  { id: "u58", title: "HSK 4 \u00b7 Set 3", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_58_0", "h4_58_1", "h4_58_2", "h4_58_3", "h4_58_4", "h4_58_5", "h4_58_6", "h4_58_7", "h4_58_8", "h4_58_9", "h4_58_10", "h4_58_11"],
    hanzi: ["切", "由", "任", "何"] },
  { id: "u59", title: "HSK 4 \u00b7 Set 4", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_59_0", "h4_59_1", "h4_59_2", "h4_59_3", "h4_59_4", "h4_59_5", "h4_59_6", "h4_59_7", "h4_59_8", "h4_59_9", "h4_59_10", "h4_59_11"],
    hanzi: ["消", "只", "要", "干"] },
  { id: "u60", title: "HSK 4 \u00b7 Set 5", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_60_0", "h4_60_1", "h4_60_2", "h4_60_3", "h4_60_4", "h4_60_5", "h4_60_6", "h4_60_7", "h4_60_8", "h4_60_9", "h4_60_10", "h4_60_11"],
    hanzi: ["力", "保", "正", "支"] },
  { id: "u61", title: "HSK 4 \u00b7 Set 6", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_61_0", "h4_61_1", "h4_61_2", "h4_61_3", "h4_61_4", "h4_61_5", "h4_61_6", "h4_61_7", "h4_61_8", "h4_61_9", "h4_61_10", "h4_61_11"],
    hanzi: ["许", "活", "动", "虑"] },
  { id: "u62", title: "HSK 4 \u00b7 Set 7", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_62_0", "h4_62_1", "h4_62_2", "h4_62_3", "h4_62_4", "h4_62_5", "h4_62_6", "h4_62_7", "h4_62_8", "h4_62_9", "h4_62_10", "h4_62_11"],
    hanzi: ["台", "获", "留", "生"] },
  { id: "u63", title: "HSK 4 \u00b7 Set 8", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_63_0", "h4_63_1", "h4_63_2", "h4_63_3", "h4_63_4", "h4_63_5", "h4_63_6", "h4_63_7", "h4_63_8", "h4_63_9", "h4_63_10", "h4_63_11"],
    hanzi: ["底", "坚", "持", "座"] },
  { id: "u64", title: "HSK 4 \u00b7 Set 9", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_64_0", "h4_64_1", "h4_64_2", "h4_64_3", "h4_64_4", "h4_64_5", "h4_64_6", "h4_64_7", "h4_64_8", "h4_64_9", "h4_64_10", "h4_64_11"],
    hanzi: ["父", "亲", "并", "且"] },
  { id: "u65", title: "HSK 4 \u00b7 Set 10", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_65_0", "h4_65_1", "h4_65_2", "h4_65_3", "h4_65_4", "h4_65_5", "h4_65_6", "h4_65_7", "h4_65_8", "h4_65_9", "h4_65_10", "h4_65_11"],
    hanzi: ["至", "少", "释", "负"] },
  { id: "u66", title: "HSK 4 \u00b7 Set 11", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_66_0", "h4_66_1", "h4_66_2", "h4_66_3", "h4_66_4", "h4_66_5", "h4_66_6", "h4_66_7", "h4_66_8", "h4_66_9", "h4_66_10", "h4_66_11"],
    hanzi: ["试", "弄", "赢", "满"] },
  { id: "u67", title: "HSK 4 \u00b7 Set 12", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_67_0", "h4_67_1", "h4_67_2", "h4_67_3", "h4_67_4", "h4_67_5", "h4_67_6", "h4_67_7", "h4_67_8", "h4_67_9", "h4_67_10", "h4_67_11"],
    hanzi: ["即", "使", "尽", "管"] },
  { id: "u68", title: "HSK 4 \u00b7 Set 13", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_68_0", "h4_68_1", "h4_68_2", "h4_68_3", "h4_68_4", "h4_68_5", "h4_68_6", "h4_68_7", "h4_68_8", "h4_68_9", "h4_68_10", "h4_68_11"],
    hanzi: ["地", "址", "无", "论"] },
  { id: "u69", title: "HSK 4 \u00b7 Set 14", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_69_0", "h4_69_1", "h4_69_2", "h4_69_3", "h4_69_4", "h4_69_5", "h4_69_6", "h4_69_7", "h4_69_8", "h4_69_9", "h4_69_10", "h4_69_11"],
    hanzi: ["困", "难", "专", "业"] },
  { id: "u70", title: "HSK 4 \u00b7 Set 15", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_70_0", "h4_70_1", "h4_70_2", "h4_70_3", "h4_70_4", "h4_70_5", "h4_70_6", "h4_70_7", "h4_70_8", "h4_70_9", "h4_70_10", "h4_70_11"],
    hanzi: ["市", "场", "教", "取"] },
  { id: "u71", title: "HSK 4 \u00b7 Set 16", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_71_0", "h4_71_1", "h4_71_2", "h4_71_3", "h4_71_4", "h4_71_5", "h4_71_6", "h4_71_7", "h4_71_8", "h4_71_9", "h4_71_10", "h4_71_11"],
    hanzi: ["内", "容", "通", "观"] },
  { id: "u72", title: "HSK 4 \u00b7 Set 17", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_72_0", "h4_72_1", "h4_72_2", "h4_72_3", "h4_72_4", "h4_72_5", "h4_72_6", "h4_72_7", "h4_72_8", "h4_72_9", "h4_72_10", "h4_72_11"],
    hanzi: ["标", "准", "职", "精"] },
  { id: "u73", title: "HSK 4 \u00b7 Set 18", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_73_0", "h4_73_1", "h4_73_2", "h4_73_3", "h4_73_4", "h4_73_5", "h4_73_6", "h4_73_7", "h4_73_8", "h4_73_9", "h4_73_10", "h4_73_11"],
    hanzi: ["竟", "重", "倍", "醒"] },
  { id: "u74", title: "HSK 4 \u00b7 Set 19", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_74_0", "h4_74_1", "h4_74_2", "h4_74_3", "h4_74_4", "h4_74_5", "h4_74_6", "h4_74_7", "h4_74_8", "h4_74_9", "h4_74_10", "h4_74_11"],
    hanzi: ["著", "拒", "绝", "帅"] },
  { id: "u75", title: "HSK 4 \u00b7 Set 20", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_75_0", "h4_75_1", "h4_75_2", "h4_75_3", "h4_75_4", "h4_75_5", "h4_75_6", "h4_75_7", "h4_75_8", "h4_75_9", "h4_75_10", "h4_75_11"],
    hanzi: ["失", "败", "纪", "制"] },
  { id: "u76", title: "HSK 4 \u00b7 Set 21", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_76_0", "h4_76_1", "h4_76_2", "h4_76_3", "h4_76_4", "h4_76_5", "h4_76_6", "h4_76_7", "h4_76_8", "h4_76_9", "h4_76_10", "h4_76_11"],
    hanzi: ["既", "停", "止", "提"] },
  { id: "u77", title: "HSK 4 \u00b7 Set 22", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_77_0", "h4_77_1", "h4_77_2", "h4_77_3", "h4_77_4", "h4_77_5", "h4_77_6", "h4_77_7", "h4_77_8", "h4_77_9", "h4_77_10", "h4_77_11"],
    hanzi: ["优", "秀", "亮", "篇"] },
  { id: "u78", title: "HSK 4 \u00b7 Set 23", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_78_0", "h4_78_1", "h4_78_2", "h4_78_3", "h4_78_4", "h4_78_5", "h4_78_6", "h4_78_7", "h4_78_8", "h4_78_9", "h4_78_10", "h4_78_11"],
    hanzi: ["毕", "怀", "疑", "修"] },
  { id: "u79", title: "HSK 4 \u00b7 Set 24", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_79_0", "h4_79_1", "h4_79_2", "h4_79_3", "h4_79_4", "h4_79_5", "h4_79_6", "h4_79_7", "h4_79_8", "h4_79_9", "h4_79_10", "h4_79_11"],
    hanzi: ["躺", "答", "案", "皮"] },
  { id: "u80", title: "HSK 4 \u00b7 Set 25", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_80_0", "h4_80_1", "h4_80_2", "h4_80_3", "h4_80_4", "h4_80_5", "h4_80_6", "h4_80_7", "h4_80_8", "h4_80_9", "h4_80_10", "h4_80_11"],
    hanzi: ["成", "熟", "聊", "文"] },
  { id: "u81", title: "HSK 4 \u00b7 Set 26", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_81_0", "h4_81_1", "h4_81_2", "h4_81_3", "h4_81_4", "h4_81_5", "h4_81_6", "h4_81_7", "h4_81_8", "h4_81_9", "h4_81_10", "h4_81_11"],
    hanzi: ["空", "气", "材", "料"] },
  { id: "u82", title: "HSK 4 \u00b7 Set 27", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_82_0", "h4_82_1", "h4_82_2", "h4_82_3", "h4_82_4", "h4_82_5", "h4_82_6", "h4_82_7", "h4_82_8", "h4_82_9", "h4_82_10", "h4_82_11"],
    hanzi: ["基", "础", "适", "应"] },
  { id: "u83", title: "HSK 4 \u00b7 Set 28", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_83_0", "h4_83_1", "h4_83_2", "h4_83_3", "h4_83_4", "h4_83_5", "h4_83_6", "h4_83_7", "h4_83_8", "h4_83_9", "h4_83_10", "h4_83_11"],
    hanzi: ["响", "收", "入", "恐"] },
  { id: "u84", title: "HSK 4 \u00b7 Set 29", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_84_0", "h4_84_1", "h4_84_2", "h4_84_3", "h4_84_4", "h4_84_5", "h4_84_6", "h4_84_7", "h4_84_8", "h4_84_9", "h4_84_10", "h4_84_11"],
    hanzi: ["尤", "其", "页", "扔"] },
  { id: "u85", title: "HSK 4 \u00b7 Set 30", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_85_0", "h4_85_1", "h4_85_2", "h4_85_3", "h4_85_4", "h4_85_5", "h4_85_6", "h4_85_7", "h4_85_8", "h4_85_9", "h4_85_10", "h4_85_11"],
    hanzi: ["硬", "限", "判", "断"] },
  { id: "u86", title: "HSK 4 \u00b7 Set 31", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_86_0", "h4_86_1", "h4_86_2", "h4_86_3", "h4_86_4", "h4_86_5", "h4_86_6", "h4_86_7", "h4_86_8", "h4_86_9", "h4_86_10", "h4_86_11"],
    hanzi: ["暗", "将", "说", "鼓"] },
  { id: "u87", title: "HSK 4 \u00b7 Set 32", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_87_0", "h4_87_1", "h4_87_2", "h4_87_3", "h4_87_4", "h4_87_5", "h4_87_6", "h4_87_7", "h4_87_8", "h4_87_9", "h4_87_10", "h4_87_11"],
    hanzi: ["整", "吵", "丰", "富"] },
  { id: "u88", title: "HSK 4 \u00b7 Set 33", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_88_0", "h4_88_1", "h4_88_2", "h4_88_3", "h4_88_4", "h4_88_5", "h4_88_6", "h4_88_7", "h4_88_8", "h4_88_9", "h4_88_10", "h4_88_11"],
    hanzi: ["详", "细", "禁", "圆"] },
  { id: "u89", title: "HSK 4 \u00b7 Set 34", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_89_0", "h4_89_1", "h4_89_2", "h4_89_3", "h4_89_4", "h4_89_5", "h4_89_6", "h4_89_7", "h4_89_8", "h4_89_9", "h4_89_10", "h4_89_11"],
    hanzi: ["随", "着", "密", "码"] },
  { id: "u90", title: "HSK 4 \u00b7 Set 35", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_90_0", "h4_90_1", "h4_90_2", "h4_90_3", "h4_90_4", "h4_90_5", "h4_90_6", "h4_90_7", "h4_90_8", "h4_90_9", "h4_90_10", "h4_90_11"],
    hanzi: ["亿", "对", "拾", "广"] },
  { id: "u91", title: "HSK 4 \u00b7 Set 36", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_91_0", "h4_91_1", "h4_91_2", "h4_91_3", "h4_91_4", "h4_91_5", "h4_91_6", "h4_91_7", "h4_91_8", "h4_91_9", "h4_91_10", "h4_91_11"],
    hanzi: ["例", "如", "贺", "批"] },
  { id: "u92", title: "HSK 4 \u00b7 Set 37", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_92_0", "h4_92_1", "h4_92_2", "h4_92_3", "h4_92_4", "h4_92_5", "h4_92_6", "h4_92_7", "h4_92_8", "h4_92_9", "h4_92_10", "h4_92_11"],
    hanzi: ["民", "族", "航", "班"] },
  { id: "u93", title: "HSK 4 \u00b7 Set 38", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_93_0", "h4_93_1", "h4_93_2", "h4_93_3", "h4_93_4", "h4_93_5", "h4_93_6", "h4_93_7", "h4_93_8", "h4_93_9", "h4_93_10", "h4_93_11"],
    hanzi: ["耐", "笑", "反", "映"] },
  { id: "u94", title: "HSK 4 \u00b7 Set 39", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_94_0", "h4_94_1", "h4_94_2", "h4_94_3", "h4_94_4", "h4_94_5", "h4_94_6", "h4_94_7", "h4_94_8", "h4_94_9", "h4_94_10", "h4_94_11"],
    hanzi: ["烦", "恼", "特", "往"] },
  { id: "u95", title: "HSK 4 \u00b7 Set 40", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_95_0", "h4_95_1", "h4_95_2", "h4_95_3", "h4_95_4", "h4_95_5", "h4_95_6", "h4_95_7", "h4_95_8", "h4_95_9", "h4_95_10", "h4_95_11"],
    hanzi: ["狮", "稍", "微", "汗"] },
  { id: "u96", title: "HSK 4 \u00b7 Set 41", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_96_0", "h4_96_1", "h4_96_2", "h4_96_3", "h4_96_4", "h4_96_5", "h4_96_6", "h4_96_7", "h4_96_8", "h4_96_9", "h4_96_10", "h4_96_11"],
    hanzi: ["报", "脏", "日", "同"] },
  { id: "u97", title: "HSK 4 \u00b7 Set 42", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_97_0", "h4_97_1", "h4_97_2", "h4_97_3", "h4_97_4", "h4_97_5", "h4_97_6", "h4_97_7", "h4_97_8", "h4_97_9", "h4_97_10", "h4_97_11"],
    hanzi: ["朵", "镜", "合", "格"] },
  { id: "u98", title: "HSK 4 \u00b7 Set 43", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_98_0", "h4_98_1", "h4_98_2", "h4_98_3", "h4_98_4", "h4_98_5", "h4_98_6", "h4_98_7", "h4_98_8", "h4_98_9", "h4_98_10", "h4_98_11"],
    hanzi: ["集", "孙", "猴", "及"] },
  { id: "u99", title: "HSK 4 \u00b7 Set 44", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_99_0", "h4_99_1", "h4_99_2", "h4_99_3", "h4_99_4", "h4_99_5", "h4_99_6", "h4_99_7", "h4_99_8", "h4_99_9", "h4_99_10", "h4_99_11"],
    hanzi: ["夫", "盒", "礼", "貌"] },
  { id: "u100", title: "HSK 4 \u00b7 Set 45", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_100_0", "h4_100_1", "h4_100_2", "h4_100_3", "h4_100_4", "h4_100_5", "h4_100_6", "h4_100_7", "h4_100_8", "h4_100_9", "h4_100_10", "h4_100_11"],
    hanzi: ["掌", "瓶", "传", "羞"] },
  { id: "u101", title: "HSK 4 \u00b7 Set 46", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_101_0", "h4_101_1", "h4_101_2", "h4_101_3", "h4_101_4", "h4_101_5", "h4_101_6", "h4_101_7", "h4_101_8", "h4_101_9", "h4_101_10", "h4_101_11"],
    hanzi: ["加", "油", "站", "约"] },
  { id: "u102", title: "HSK 4 \u00b7 Set 47", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_102_0", "h4_102_1", "h4_102_2", "h4_102_3", "h4_102_4", "h4_102_5", "h4_102_6", "h4_102_7", "h4_102_8", "h4_102_9", "h4_102_10", "h4_102_11"],
    hanzi: ["齐", "扬", "硕", "士"] },
  { id: "u103", title: "HSK 4 \u00b7 Set 48", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_103_0", "h4_103_1", "h4_103_2", "h4_103_3", "h4_103_4", "h4_103_5", "h4_103_6", "h4_103_7", "h4_103_8", "h4_103_9", "h4_103_10", "h4_103_11"],
    hanzi: ["折", "洗", "衣", "堵"] },
  { id: "u104", title: "HSK 4 \u00b7 Set 49", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_104_0", "h4_104_1", "h4_104_2", "h4_104_3", "h4_104_4", "h4_104_5", "h4_104_6", "h4_104_7", "h4_104_8", "h4_104_9", "h4_104_10", "h4_104_11"],
    hanzi: ["语", "法", "杯", "印"] },
  { id: "u105", title: "HSK 4 \u00b7 Set 50", icon: "\ud83d\udcd9", hsk: 4, auto: true,
    words: ["h4_105_0", "h4_105_1", "h4_105_2", "h4_105_3", "h4_105_4", "h4_105_5", "h4_105_6", "h4_105_7"],
    hanzi: ["寒", "假", "币", "粗"] }
);
