// Mandarin Journey — course content, HSK 2 (Units 16–30)
// Loaded after content-hsk1.js: extends WORDS and UNITS.

Object.assign(window.WORDS, {
  // U16 Feelings
  juede:     { cn: '觉得', py: 'juéde',     pyPlain: 'juede',     en: 'to think / feel',   emoji: '🧠' },
  kuaile:    { cn: '快乐', py: 'kuàilè',    pyPlain: 'kuaile',    en: 'happy',             emoji: '🥳' },
  lei:       { cn: '累',   py: 'lèi',       pyPlain: 'lei',       en: 'tired',             emoji: '🥱' },
  mang:      { cn: '忙',   py: 'máng',      pyPlain: 'mang',      en: 'busy',              emoji: '🏃' },
  shengbing: { cn: '生病', py: 'shēngbìng', pyPlain: 'shengbing', en: 'to get sick',       emoji: '🤒' },
  shenti:    { cn: '身体', py: 'shēntǐ',    pyPlain: 'shenti',    en: 'body / health',     emoji: '🫀' },
  xiuxi:     { cn: '休息', py: 'xiūxi',     pyPlain: 'xiuxi',     en: 'to rest',           emoji: '🛋️' },
  danshi:    { cn: '但是', py: 'dànshì',    pyPlain: 'danshi',    en: 'but',               emoji: '↔️' },
  yinwei:    { cn: '因为', py: 'yīnwèi',    pyPlain: 'yinwei',    en: 'because',           emoji: '🔍' },
  suoyi:     { cn: '所以', py: 'suǒyǐ',     pyPlain: 'suoyi',     en: 'so / therefore',    emoji: '➡️' },
  // U17 Done!
  yijing:   { cn: '已经', py: 'yǐjīng',   pyPlain: 'yijing',   en: 'already',        emoji: '✅' },
  hai2:     { cn: '还',   py: 'hái',      pyPlain: 'hai',      en: 'still / yet',    emoji: '⏳' },
  jiu4:     { cn: '就',   py: 'jiù',      pyPlain: 'jiu',      en: 'then / right away', emoji: '⚡' },
  dao4:     { cn: '到',   py: 'dào',      pyPlain: 'dao',      en: 'to arrive',      emoji: '🎯' },
  wan:      { cn: '完',   py: 'wán',      pyPlain: 'wan',      en: 'to finish',      emoji: '🏁' },
  cong2:    { cn: '从',   py: 'cóng',     pyPlain: 'cong',     en: 'from',           emoji: '🛫' },
  kaishi:   { cn: '开始', py: 'kāishǐ',   pyPlain: 'kaishi',   en: 'to start',       emoji: '▶️' },
  qichuang: { cn: '起床', py: 'qǐchuáng', pyPlain: 'qichuang', en: 'to get up (from bed)', emoji: '🛌' },
  // U18 Directions
  li2:      { cn: '离',   py: 'lí',       pyPlain: 'li',       en: 'away from (distance)', emoji: '📏' },
  yuan3:    { cn: '远',   py: 'yuǎn',     pyPlain: 'yuan',     en: 'far',           emoji: '🔭' },
  jin4:     { cn: '近',   py: 'jìn',      pyPlain: 'jin',      en: 'near',          emoji: '🤏' },
  qianmian: { cn: '前面', py: 'qiánmiàn', pyPlain: 'qianmian', en: 'in front',      emoji: '⬆️' },
  houmian:  { cn: '后面', py: 'hòumiàn',  pyPlain: 'houmian',  en: 'behind',        emoji: '⬇️' },
  pangbian: { cn: '旁边', py: 'pángbiān', pyPlain: 'pangbian', en: 'beside / next to', emoji: '↔️' },
  zuobian:  { cn: '左边', py: 'zuǒbian',  pyPlain: 'zuobian',  en: 'left side',     emoji: '⬅️' },
  youbian:  { cn: '右边', py: 'yòubian',  pyPlain: 'youbian',  en: 'right side',    emoji: '➡️' },
  wai4:     { cn: '外',   py: 'wài',      pyPlain: 'wai',      en: 'outside',       emoji: '🚪' },
  men2:     { cn: '门',   py: 'mén',      pyPlain: 'men',      en: 'door / gate',   emoji: '🚪' },
  // U19 Travel
  zou3:    { cn: '走',   py: 'zǒu',     pyPlain: 'zou',     en: 'to walk / go',  emoji: '🚶' },
  paobu:   { cn: '跑步', py: 'pǎobù',   pyPlain: 'paobu',   en: 'to run / jog',  emoji: '🏃' },
  lu4:     { cn: '路',   py: 'lù',      pyPlain: 'lu',      en: 'road / way',    emoji: '🛣️' },
  lvyou:   { cn: '旅游', py: 'lǚyóu',   pyPlain: 'lvyou',   en: 'to travel',     emoji: '🧳' },
  jichang: { cn: '机场', py: 'jīchǎng', pyPlain: 'jichang', en: 'airport',       emoji: '🛫' },
  piao4:   { cn: '票',   py: 'piào',    pyPlain: 'piao',    en: 'ticket',        emoji: '🎫' },
  binguan: { cn: '宾馆', py: 'bīnguǎn', pyPlain: 'binguan', en: 'hotel',         emoji: '🏨' },
  wanr:    { cn: '玩',   py: 'wán',     pyPlain: 'wan',     en: 'to play / have fun', emoji: '🎉' },
  youyong: { cn: '游泳', py: 'yóuyǒng', pyPlain: 'youyong', en: 'to swim',       emoji: '🏊' },
  gonggongqiche: { cn: '公共汽车', py: 'gōnggòng qìchē', pyPlain: 'gonggongqiche', en: 'bus', emoji: '🚌' },
  // U20 Money II
  gui4:   { cn: '贵',   py: 'guì',    pyPlain: 'gui',    en: 'expensive',       emoji: '💎' },
  pianyi: { cn: '便宜', py: 'piányi', pyPlain: 'pianyi', en: 'cheap',           emoji: '🏷️' },
  mai4:   { cn: '卖',   py: 'mài',    pyPlain: 'mai',    en: 'to sell',         emoji: '🤝' },
  bai3:   { cn: '百',   py: 'bǎi',    pyPlain: 'bai',    en: 'hundred',         emoji: '💯' },
  qian1:  { cn: '千',   py: 'qiān',   pyPlain: 'qian',   en: 'thousand',        emoji: '🔢' },
  liang3: { cn: '两',   py: 'liǎng',  pyPlain: 'liang',  en: 'two (of something)', emoji: '✌️' },
  ling2:  { cn: '零',   py: 'líng',   pyPlain: 'ling',   en: 'zero',            emoji: '0️⃣' },
  jian4:  { cn: '件',   py: 'jiàn',   pyPlain: 'jian',   en: 'measure word (clothes)', emoji: '👔' },
  zhang1: { cn: '张',   py: 'zhāng',  pyPlain: 'zhang',  en: 'measure word (flat things)', emoji: '🗞️' },
  ci4:    { cn: '次',   py: 'cì',     pyPlain: 'ci',     en: 'time (occurrence)', emoji: '🔂' },
  // U21 Food II
  yangrou:   { cn: '羊肉',   py: 'yángròu',   pyPlain: 'yangrou',   en: 'lamb / mutton', emoji: '🐑' },
  yu2:       { cn: '鱼',     py: 'yú',        pyPlain: 'yu',        en: 'fish',          emoji: '🐟' },
  jidan:     { cn: '鸡蛋',   py: 'jīdàn',     pyPlain: 'jidan',     en: 'egg',           emoji: '🥚' },
  miantiao:  { cn: '面条',   py: 'miàntiáo',  pyPlain: 'miantiao',  en: 'noodles',       emoji: '🍜' },
  niunai:    { cn: '牛奶',   py: 'niúnǎi',    pyPlain: 'niunai',    en: 'milk',          emoji: '🥛' },
  kafei:     { cn: '咖啡',   py: 'kāfēi',     pyPlain: 'kafei',     en: 'coffee',        emoji: '☕' },
  xigua:     { cn: '西瓜',   py: 'xīguā',     pyPlain: 'xigua',     en: 'watermelon',    emoji: '🍉' },
  haochi:    { cn: '好吃',   py: 'hǎochī',    pyPlain: 'haochi',    en: 'delicious',     emoji: '😋' },
  fuwuyuan:  { cn: '服务员', py: 'fúwùyuán',  pyPlain: 'fuwuyuan',  en: 'waiter / server', emoji: '🧑‍🍳' },
  yidianr:   { cn: '一点儿', py: 'yìdiǎnr',   pyPlain: 'yidianr',   en: 'a little bit',  emoji: '🤏' },
  // U22 Family II
  gege:    { cn: '哥哥', py: 'gēge',    pyPlain: 'gege',    en: 'older brother',   emoji: '👦' },
  jiejie:  { cn: '姐姐', py: 'jiějie',  pyPlain: 'jiejie',  en: 'older sister',    emoji: '👧' },
  didi:    { cn: '弟弟', py: 'dìdi',    pyPlain: 'didi',    en: 'younger brother', emoji: '🧒' },
  meimei:  { cn: '妹妹', py: 'mèimei',  pyPlain: 'meimei',  en: 'younger sister',  emoji: '👶' },
  zhangfu: { cn: '丈夫', py: 'zhàngfu', pyPlain: 'zhangfu', en: 'husband',         emoji: '🤵' },
  qizi:    { cn: '妻子', py: 'qīzi',    pyPlain: 'qizi',    en: 'wife',            emoji: '👰' },
  haizi:   { cn: '孩子', py: 'háizi',   pyPlain: 'haizi',   en: 'child',           emoji: '🧒' },
  nan2:    { cn: '男',   py: 'nán',     pyPlain: 'nan',     en: 'male',            emoji: '♂️' },
  nv3:     { cn: '女',   py: 'nǚ',      pyPlain: 'nv',      en: 'female',          emoji: '♀️' },
  dajia:   { cn: '大家', py: 'dàjiā',   pyPlain: 'dajia',   en: 'everyone',        emoji: '👨‍👩‍👧‍👦' },
  bi3:     { cn: '比',   py: 'bǐ',      pyPlain: 'bi',      en: 'than (compare)',  emoji: '⚖️' },
  // U23 Work & study
  shangban: { cn: '上班', py: 'shàngbān', pyPlain: 'shangban', en: 'to go to work',  emoji: '🏢' },
  shangke:  { cn: '上课', py: 'shàngkè',  pyPlain: 'shangke',  en: 'to attend class', emoji: '🏫' },
  kaoshi:   { cn: '考试', py: 'kǎoshì',   pyPlain: 'kaoshi',   en: 'exam / test',    emoji: '📝' },
  wenti:    { cn: '问题', py: 'wèntí',    pyPlain: 'wenti',    en: 'question / problem', emoji: '❓' },
  wen4:     { cn: '问',   py: 'wèn',      pyPlain: 'wen',      en: 'to ask',         emoji: '🙋' },
  dong3:    { cn: '懂',   py: 'dǒng',     pyPlain: 'dong',     en: 'to understand',  emoji: '💡' },
  bangzhu:  { cn: '帮助', py: 'bāngzhù',  pyPlain: 'bangzhu',  en: 'to help',        emoji: '🤝' },
  zhunbei:  { cn: '准备', py: 'zhǔnbèi',  pyPlain: 'zhunbei',  en: 'to prepare',     emoji: '🎒' },
  jiaoshi:  { cn: '教室', py: 'jiàoshì',  pyPlain: 'jiaoshi',  en: 'classroom',      emoji: '🪑' },
  keyi:     { cn: '可以', py: 'kěyǐ',     pyPlain: 'keyi',     en: 'may / can (permission)', emoji: '👌' },
  // U24 Time II
  xiaoshi:  { cn: '小时', py: 'xiǎoshí',  pyPlain: 'xiaoshi',  en: 'hour',          emoji: '🕐' },
  shijian:  { cn: '时间', py: 'shíjiān',  pyPlain: 'shijian',  en: 'time',          emoji: '⌛' },
  mei3:     { cn: '每',   py: 'měi',      pyPlain: 'mei',      en: 'every / each',  emoji: '🔁' },
  rang4:    { cn: '让',   py: 'ràng',     pyPlain: 'rang',     en: 'to let / make (someone)', emoji: '🫱' },
  deng3:    { cn: '等',   py: 'děng',     pyPlain: 'deng',     en: 'to wait',       emoji: '🧍' },
  chang2:   { cn: '长',   py: 'cháng',    pyPlain: 'chang',    en: 'long',          emoji: '📏' },
  zaoshang: { cn: '早上', py: 'zǎoshang', pyPlain: 'zaoshang', en: 'early morning', emoji: '🌄' },
  qunian:   { cn: '去年', py: 'qùnián',   pyPlain: 'qunian',   en: 'last year',     emoji: '↩️' },
  shengri:  { cn: '生日', py: 'shēngrì',  pyPlain: 'shengri',  en: 'birthday',      emoji: '🎂' },
  // U25 Telling & knowing
  keneng:   { cn: '可能', py: 'kěnéng',   pyPlain: 'keneng',   en: 'maybe / possible', emoji: '🎲' },
  bie2:     { cn: '别',   py: 'bié',      pyPlain: 'bie',      en: "don't (do it)", emoji: '🚫' },
  zai4:     { cn: '再',   py: 'zài',      pyPlain: 'zai',      en: 'again',         emoji: '🔄' },
  zhengzai: { cn: '正在', py: 'zhèngzài', pyPlain: 'zhengzai', en: 'in the middle of (-ing)', emoji: '⏯️' },
  gei3:     { cn: '给',   py: 'gěi',      pyPlain: 'gei',      en: 'to give / for', emoji: '🎁' },
  gaosu:    { cn: '告诉', py: 'gàosu',    pyPlain: 'gaosu',    en: 'to tell',       emoji: '📣' },
  shuohua:  { cn: '说话', py: 'shuōhuà',  pyPlain: 'shuohua',  en: 'to talk',       emoji: '💬' },
  shiqing:  { cn: '事情', py: 'shìqing',  pyPlain: 'shiqing',  en: 'matter / affair', emoji: '📋' },
  zhidao:   { cn: '知道', py: 'zhīdào',   pyPlain: 'zhidao',   en: 'to know (a fact)', emoji: '💡' },
  // U26 Sports & hobbies
  lanqiu:  { cn: '篮球', py: 'lánqiú',  pyPlain: 'lanqiu',  en: 'basketball',  emoji: '🏀' },
  zuqiu:   { cn: '足球', py: 'zúqiú',   pyPlain: 'zuqiu',   en: 'soccer',      emoji: '⚽' },
  ti1:     { cn: '踢',   py: 'tī',      pyPlain: 'ti',      en: 'to kick',     emoji: '🦵' },
  tiaowu:  { cn: '跳舞', py: 'tiàowǔ',  pyPlain: 'tiaowu',  en: 'to dance',    emoji: '💃' },
  changge: { cn: '唱歌', py: 'chànggē', pyPlain: 'changge', en: 'to sing',     emoji: '🎤' },
  yundong: { cn: '运动', py: 'yùndòng', pyPlain: 'yundong', en: 'sports / exercise', emoji: '🏋️' },
  yiqi:    { cn: '一起', py: 'yìqǐ',    pyPlain: 'yiqi',    en: 'together',    emoji: '👯' },
  dui4:    { cn: '对',   py: 'duì',     pyPlain: 'dui',     en: 'correct / right', emoji: '✔️' },
  // U27 Colors & looks
  hong2:     { cn: '红',   py: 'hóng',      pyPlain: 'hong',      en: 'red',          emoji: '🔴' },
  bai2:      { cn: '白',   py: 'bái',       pyPlain: 'bai',       en: 'white',        emoji: '⚪' },
  hei1:      { cn: '黑',   py: 'hēi',       pyPlain: 'hei',       en: 'black',        emoji: '⚫' },
  yanse:     { cn: '颜色', py: 'yánsè',     pyPlain: 'yanse',     en: 'color',        emoji: '🎨' },
  xin1:      { cn: '新',   py: 'xīn',       pyPlain: 'xin',       en: 'new',          emoji: '✨' },
  gao1:      { cn: '高',   py: 'gāo',       pyPlain: 'gao',       en: 'tall / high',  emoji: '🦒' },
  piaoliang: { cn: '漂亮', py: 'piàoliang', pyPlain: 'piaoliang', en: 'pretty',       emoji: '🌸' },
  yanjing:   { cn: '眼睛', py: 'yǎnjing',   pyPlain: 'yanjing',   en: 'eyes',         emoji: '👀' },
  xiao4:     { cn: '笑',   py: 'xiào',      pyPlain: 'xiao',      en: 'to smile / laugh', emoji: '😄' },
  chuan1:    { cn: '穿',   py: 'chuān',     pyPlain: 'chuan',     en: 'to wear',      emoji: '👗' },
  // U28 How & why
  weishenme: { cn: '为什么', py: 'wèishénme', pyPlain: 'weishenme', en: 'why',        emoji: '🤔' },
  nin2:      { cn: '您',     py: 'nín',       pyPlain: 'nin',       en: 'you (polite)', emoji: '🙇' },
  ta3:       { cn: '它',     py: 'tā',        pyPlain: 'ta',        en: 'it (animal/thing)', emoji: '🐾' },
  ba5:       { cn: '吧',     py: 'ba',        pyPlain: 'ba',        en: "let's… (suggestion)", emoji: '🤙' },
  man4:      { cn: '慢',     py: 'màn',       pyPlain: 'man',       en: 'slow',       emoji: '🐢' },
  kuai4:     { cn: '快',     py: 'kuài',      pyPlain: 'kuai',      en: 'fast',       emoji: '🐇' },
  cuo4:      { cn: '错',     py: 'cuò',       pyPlain: 'cuo',       en: 'wrong',      emoji: '❌' },
  yao4:      { cn: '药',     py: 'yào',       pyPlain: 'yao',       en: 'medicine',   emoji: '💊' },
  zhen1:     { cn: '真',     py: 'zhēn',      pyPlain: 'zhen',      en: 'really / truly', emoji: '💯' },
  // U29 Around the house
  fangjian: { cn: '房间', py: 'fángjiān', pyPlain: 'fangjian', en: 'room',       emoji: '🚪' },
  shouji:   { cn: '手机', py: 'shǒujī',   pyPlain: 'shouji',   en: 'mobile phone', emoji: '📱' },
  shoubiao: { cn: '手表', py: 'shǒubiǎo', pyPlain: 'shoubiao', en: 'wristwatch', emoji: '⌚' },
  baozhi:   { cn: '报纸', py: 'bàozhǐ',   pyPlain: 'baozhi',   en: 'newspaper',  emoji: '📰' },
  chuang2:  { cn: '床',   py: 'chuáng',   pyPlain: 'chuang',   en: 'bed',        emoji: '🛏️' },
  zhao3:    { cn: '找',   py: 'zhǎo',     pyPlain: 'zhao',     en: 'to look for', emoji: '🔎' },
  song4:    { cn: '送',   py: 'sòng',     pyPlain: 'song',     en: 'to give (gift) / deliver', emoji: '💐' },
  xi3:      { cn: '洗',   py: 'xǐ',       pyPlain: 'xi',       en: 'to wash',    emoji: '🧼' },
  // U30 Big Finale
  xiwang:   { cn: '希望', py: 'xīwàng',   pyPlain: 'xiwang',   en: 'to hope',    emoji: '🌟' },
  yisi:     { cn: '意思', py: 'yìsi',     pyPlain: 'yisi',     en: 'meaning',    emoji: '💭' },
  yixia:    { cn: '一下', py: 'yíxià',    pyPlain: 'yixia',    en: 'a moment / briefly', emoji: '⏸️' },
  xing4:    { cn: '姓',   py: 'xìng',     pyPlain: 'xing',     en: 'surname',    emoji: '🪪' },
  diyi:     { cn: '第一', py: 'dì-yī',    pyPlain: 'diyi',     en: 'first',      emoji: '🥇' },
  feichang: { cn: '非常', py: 'fēicháng', pyPlain: 'feichang', en: 'extremely',  emoji: '🔥' },
  zui4:     { cn: '最',   py: 'zuì',      pyPlain: 'zui',      en: 'the most',   emoji: '🏆' },
});

window.UNITS.push(
  {
    id: 'u16', title: 'Feelings', icon: '😊', hsk: 2,
    words: ['juede', 'kuaile', 'lei', 'mang', 'shengbing', 'shenti', 'xiuxi', 'danshi', 'yinwei', 'suoyi'],
    hanzi: ['忙', '累', '休', '息'],
    grammar: {
      name: '因为…所以… (because… so…)',
      intro: 'Chinese loves pairs: <b>因为</b> A, <b>所以</b> B = "because A, so B" — and you say BOTH halves. Contrast with <b>但是</b> = "but". Share opinions with <b>觉得</b>: 我觉得… = "I think…"',
      examples: [
        { cn: '因为我生病了，所以在家休息。', py: 'Yīnwèi wǒ shēngbìng le, suǒyǐ zài jiā xiūxi.', en: "Because I'm sick, I'm resting at home." },
        { cn: '他很忙，但是很快乐。', py: 'Tā hěn máng, dànshì hěn kuàilè.', en: "He's busy, but very happy." },
      ],
      fillBlanks: [
        { before: '', after: '我生病了，所以不去学校。', answer: '因为', choices: ['因为', '但是', '所以'], en: "Because I'm sick, I'm not going to school." },
        { before: '我很累，', after: '很快乐。', answer: '但是', choices: ['但是', '因为', '所以'], en: "I'm tired, but very happy." },
        { before: '你觉得怎么', after: '？', answer: '样', choices: ['样', '吗', '少'], en: 'What do you think?' },
      ],
      tiles: [
        { parts: ['我', '今天', '很', '累'], en: "I'm very tired today." },
        { parts: ['他', '很', '忙', '但是', '很', '快乐'], en: "He's busy but very happy." },
      ],
    },
    sentences: [
      { cn: '我今天很累。', py: 'Wǒ jīntiān hěn lèi.', en: "I'm very tired today." },
      { cn: '因为我生病了，所以在家休息。', py: 'Yīnwèi wǒ shēngbìng le, suǒyǐ zài jiā xiūxi.', en: "Because I'm sick, I'm resting at home." },
      { cn: '他很忙，但是很快乐。', py: 'Tā hěn máng, dànshì hěn kuàilè.', en: "He's busy, but very happy." },
      { cn: '你觉得怎么样？', py: 'Nǐ juéde zěnmeyàng?', en: 'What do you think?' },
    ],
  },
  {
    id: 'u17', title: 'Done!', icon: '✅', hsk: 2,
    words: ['yijing', 'hai2', 'jiu4', 'dao4', 'wan', 'cong2', 'kaishi', 'qichuang'],
    hanzi: ['已', '到', '完', '起'],
    grammar: {
      name: '了 — it happened!',
      intro: 'Add <b>了 le</b> after a verb to say it\'s done: 我吃了 = "I ate". With <b>已经</b> ("already") it\'s even clearer: 我已经吃了. <b>到…了</b> = arrived, <b>开始了</b> = it started!',
      examples: [
        { cn: '我已经吃了。', py: 'Wǒ yǐjīng chī le.', en: "I've already eaten." },
        { cn: '电影开始了。', py: 'Diànyǐng kāishǐ le.', en: 'The movie has started.' },
      ],
      fillBlanks: [
        { before: '我已经吃', after: '。', answer: '了', choices: ['了', '吗', '的'], en: "I've already eaten." },
        { before: '他', after: '家了。', answer: '到', choices: ['到', '从', '还'], en: 'He has arrived home.' },
        { before: '电影开始', after: '。', answer: '了', choices: ['了', '呢', '吗'], en: 'The movie has started.' },
      ],
      tiles: [
        { parts: ['我', '已经', '吃', '了'], en: "I've already eaten." },
        { parts: ['电影', '开始', '了'], en: 'The movie has started.' },
      ],
    },
    sentences: [
      { cn: '我已经吃了。', py: 'Wǒ yǐjīng chī le.', en: "I've already eaten." },
      { cn: '他到家了。', py: 'Tā dào jiā le.', en: 'He has arrived home.' },
      { cn: '电影开始了。', py: 'Diànyǐng kāishǐ le.', en: 'The movie has started.' },
      { cn: '我七点起床。', py: 'Wǒ qī diǎn qǐchuáng.', en: 'I get up at seven.' },
    ],
  },
  {
    id: 'u18', title: 'Directions', icon: '🧭', hsk: 2,
    words: ['li2', 'yuan3', 'jin4', 'qianmian', 'houmian', 'pangbian', 'zuobian', 'youbian', 'wai4', 'men2'],
    hanzi: ['远', '近', '门', '边'],
    grammar: {
      name: 'A 离 B 很远 — how far apart',
      intro: 'Measure distance with <b>离</b>: A 离 B 很远/很近 = "A is far from / close to B". Position words come after the place: 学校<b>旁边</b> = next to the school, 门<b>外</b> = outside the door.',
      examples: [
        { cn: '学校离我家很近。', py: 'Xuéxiào lí wǒ jiā hěn jìn.', en: 'The school is very close to my home.' },
        { cn: '商店在饭店旁边。', py: 'Shāngdiàn zài fàndiàn pángbiān.', en: 'The shop is next to the restaurant.' },
      ],
      fillBlanks: [
        { before: '学校', after: '我家很近。', answer: '离', choices: ['离', '从', '到'], en: 'The school is very close to my home.' },
        { before: '医院在前', after: '。', answer: '面', choices: ['面', '边', '里'], en: 'The hospital is up ahead.' },
        { before: '商店在饭店', after: '边。', answer: '旁', choices: ['旁', '左', '右'], en: 'The shop is next to the restaurant.' },
      ],
      tiles: [
        { parts: ['学校', '离', '我家', '很', '近'], en: 'The school is very close to my home.' },
        { parts: ['猫', '在', '门', '外'], en: 'The cat is outside the door.' },
      ],
    },
    sentences: [
      { cn: '学校离我家很近。', py: 'Xuéxiào lí wǒ jiā hěn jìn.', en: 'The school is very close to my home.' },
      { cn: '医院在前面。', py: 'Yīyuàn zài qiánmiàn.', en: 'The hospital is up ahead.' },
      { cn: '商店在饭店旁边。', py: 'Shāngdiàn zài fàndiàn pángbiān.', en: 'The shop is next to the restaurant.' },
      { cn: '猫在门外。', py: 'Māo zài mén wài.', en: 'The cat is outside the door.' },
    ],
  },
  {
    id: 'u19', title: 'Travel', icon: '🧳', hsk: 2,
    words: ['zou3', 'paobu', 'lu4', 'lvyou', 'jichang', 'piao4', 'binguan', 'wanr', 'youyong', 'gonggongqiche'],
    hanzi: ['走', '路', '票', '玩'],
    grammar: {
      name: '怎么走? — asking the way',
      intro: 'Lost? Ask <b>去…怎么走？</b> = "to get to …, how do I go?" 去机场怎么走? Remember 怎么 from Unit 14 — it asks "how" for any verb: 怎么去, 怎么走, 怎么说.',
      examples: [
        { cn: '去机场怎么走？', py: 'Qù jīchǎng zěnme zǒu?', en: 'How do I get to the airport?' },
        { cn: '我们去中国旅游。', py: 'Wǒmen qù Zhōngguó lǚyóu.', en: "We're traveling to China." },
      ],
      fillBlanks: [
        { before: '去机场怎么', after: '？', answer: '走', choices: ['走', '来', '坐'], en: 'How do I get to the airport?' },
        { before: '我们去中国旅', after: '。', answer: '游', choices: ['游', '玩', '走'], en: "We're traveling to China." },
        { before: '他会游', after: '。', answer: '泳', choices: ['泳', '水', '路'], en: 'He can swim.' },
      ],
      tiles: [
        { parts: ['去', '机场', '怎么', '走'], en: 'How do I get to the airport?' },
        { parts: ['我们', '去', '中国', '旅游'], en: "We're traveling to China." },
      ],
    },
    sentences: [
      { cn: '去机场怎么走？', py: 'Qù jīchǎng zěnme zǒu?', en: 'How do I get to the airport?' },
      { cn: '我们去中国旅游。', py: 'Wǒmen qù Zhōngguó lǚyóu.', en: "We're traveling to China." },
      { cn: '我喜欢跑步。', py: 'Wǒ xǐhuan pǎobù.', en: 'I like jogging.' },
      { cn: '他会游泳。', py: 'Tā huì yóuyǒng.', en: 'He can swim.' },
    ],
  },
  {
    id: 'u20', title: 'Money Talk', icon: '💰', hsk: 2,
    words: ['gui4', 'pianyi', 'mai4', 'bai3', 'qian1', 'liang3', 'ling2', 'jian4', 'zhang1', 'ci4'],
    hanzi: ['贵', '卖', '两', '百'],
    grammar: {
      name: 'Measure words & 两',
      intro: 'Different things, different measure words: <b>件</b> for clothes (一件衣服), <b>张</b> for flat things (两张票), <b>次</b> for times (三次). And when counting "two of something", use <b>两</b>, not 二: 两个人!',
      examples: [
        { cn: '我买了两张票。', py: 'Wǒ mǎi le liǎng zhāng piào.', en: 'I bought two tickets.' },
        { cn: '这件衣服太贵了！', py: 'Zhè jiàn yīfu tài guì le!', en: 'This piece of clothing is too expensive!' },
      ],
      fillBlanks: [
        { before: '这', after: '衣服太贵了！', answer: '件', choices: ['件', '张', '次'], en: 'This piece of clothing is too expensive!' },
        { before: '我买了', after: '张票。', answer: '两', choices: ['两', '二', '几'], en: 'I bought two tickets.' },
        { before: '我去了三', after: '北京。', answer: '次', choices: ['次', '件', '张'], en: 'I went to Beijing three times.' },
      ],
      tiles: [
        { parts: ['这', '件', '衣服', '太', '贵', '了'], en: 'This piece of clothing is too expensive!' },
        { parts: ['我', '买', '了', '两', '张', '票'], en: 'I bought two tickets.' },
      ],
    },
    sentences: [
      { cn: '这件衣服太贵了！', py: 'Zhè jiàn yīfu tài guì le!', en: 'This piece of clothing is too expensive!' },
      { cn: '那个很便宜。', py: 'Nàge hěn piányi.', en: 'That one is very cheap.' },
      { cn: '我买了两张票。', py: 'Wǒ mǎi le liǎng zhāng piào.', en: 'I bought two tickets.' },
      { cn: '一百块钱。', py: 'Yìbǎi kuài qián.', en: 'One hundred kuai.' },
    ],
  },
  {
    id: 'u21', title: 'At the Restaurant', icon: '🥟', hsk: 2,
    words: ['yangrou', 'yu2', 'jidan', 'miantiao', 'niunai', 'kafei', 'xigua', 'haochi', 'fuwuyuan', 'yidianr'],
    hanzi: ['鱼', '肉', '蛋', '奶'],
    grammar: {
      name: '一点儿 — just a little',
      intro: 'Soften requests with <b>一点儿</b> = "a little bit": 我想吃一点儿面条. Praise food with <b>好吃</b> ("good to eat") = delicious — and drinks are 好喝! Call the waiter: 服务员!',
      examples: [
        { cn: '我想吃一点儿面条。', py: 'Wǒ xiǎng chī yìdiǎnr miàntiáo.', en: "I'd like to eat a little noodles." },
        { cn: '羊肉很好吃。', py: 'Yángròu hěn hǎochī.', en: 'The lamb is delicious.' },
      ],
      fillBlanks: [
        { before: '我想吃一点', after: '面条。', answer: '儿', choices: ['儿', '子', '个'], en: "I'd like a little noodles." },
        { before: '羊肉很好', after: '。', answer: '吃', choices: ['吃', '喝', '看'], en: 'The lamb is delicious.' },
        { before: '我要一杯咖', after: '。', answer: '啡', choices: ['啡', '茶', '奶'], en: "I'd like a cup of coffee." },
      ],
      tiles: [
        { parts: ['羊肉', '很', '好吃'], en: 'The lamb is delicious.' },
        { parts: ['我', '要', '一', '杯', '咖啡'], en: "I'd like a cup of coffee." },
      ],
    },
    sentences: [
      { cn: '我想吃一点儿面条。', py: 'Wǒ xiǎng chī yìdiǎnr miàntiáo.', en: "I'd like to eat a little noodles." },
      { cn: '羊肉很好吃。', py: 'Yángròu hěn hǎochī.', en: 'The lamb is delicious.' },
      { cn: '服务员，我要一杯咖啡。', py: 'Fúwùyuán, wǒ yào yì bēi kāfēi.', en: "Waiter, I'd like a cup of coffee." },
      { cn: '西瓜是水果。', py: 'Xīguā shì shuǐguǒ.', en: 'A watermelon is a fruit.' },
    ],
  },
  {
    id: 'u22', title: 'Big Family', icon: '👨‍👩‍👧‍👦', hsk: 2,
    words: ['gege', 'jiejie', 'didi', 'meimei', 'zhangfu', 'qizi', 'haizi', 'nan2', 'nv3', 'dajia', 'bi3'],
    hanzi: ['哥', '姐', '弟', '妹'],
    grammar: {
      name: '比 — comparing things',
      intro: 'Compare with <b>比</b>: A 比 B + adjective = "A is more … than B". 哥哥比我大 = "older brother is bigger (older) than me". No "more" word needed — 比 does it all.',
      examples: [
        { cn: '哥哥比我大。', py: 'Gēge bǐ wǒ dà.', en: 'My older brother is older than me.' },
        { cn: '他们有两个孩子。', py: 'Tāmen yǒu liǎng gè háizi.', en: 'They have two children.' },
      ],
      fillBlanks: [
        { before: '哥哥', after: '我大。', answer: '比', choices: ['比', '是', '离'], en: 'My older brother is older than me.' },
        { before: '妹妹比我', after: '。', answer: '小', choices: ['小', '大', '多'], en: 'My younger sister is younger than me.' },
        { before: '他们有两个', after: '。', answer: '孩子', choices: ['孩子', '丈夫', '大家'], en: 'They have two children.' },
      ],
      tiles: [
        { parts: ['哥哥', '比', '我', '大'], en: 'My older brother is older than me.' },
        { parts: ['他们', '有', '两', '个', '孩子'], en: 'They have two children.' },
      ],
    },
    sentences: [
      { cn: '哥哥比我大。', py: 'Gēge bǐ wǒ dà.', en: 'My older brother is older than me.' },
      { cn: '她是我妹妹。', py: 'Tā shì wǒ mèimei.', en: 'She is my younger sister.' },
      { cn: '他们有两个孩子。', py: 'Tāmen yǒu liǎng gè háizi.', en: 'They have two children.' },
      { cn: '大家好！', py: 'Dàjiā hǎo!', en: 'Hello, everyone!' },
    ],
  },
  {
    id: 'u23', title: 'Work & Study', icon: '📚', hsk: 2,
    words: ['shangban', 'shangke', 'kaoshi', 'wenti', 'wen4', 'dong3', 'bangzhu', 'zhunbei', 'jiaoshi', 'keyi'],
    hanzi: ['问', '课', '考', '懂'],
    grammar: {
      name: '可以 — may I?',
      intro: 'Third "can" word! <b>可以</b> = allowed to: 我可以问你吗? = "May I ask you?" (会 = learned skill, 能 = physically able, 可以 = permitted.) Check understanding with <b>懂了吗？</b>',
      examples: [
        { cn: '我可以问你吗？', py: 'Wǒ kěyǐ wèn nǐ ma?', en: 'May I ask you (something)?' },
        { cn: '你懂了吗？', py: 'Nǐ dǒng le ma?', en: 'Do you understand?' },
      ],
      fillBlanks: [
        { before: '我', after: '以问你吗？', answer: '可', choices: ['可', '会', '能'], en: 'May I ask you (something)?' },
        { before: '明天有考', after: '。', answer: '试', choices: ['试', '题', '课'], en: 'There is an exam tomorrow.' },
        { before: '你', after: '了吗？', answer: '懂', choices: ['懂', '问', '帮'], en: 'Do you understand?' },
      ],
      tiles: [
        { parts: ['我', '可以', '问', '你', '吗'], en: 'May I ask you (something)?' },
        { parts: ['明天', '有', '考试'], en: 'There is an exam tomorrow.' },
      ],
    },
    sentences: [
      { cn: '我有一个问题。', py: 'Wǒ yǒu yí gè wèntí.', en: 'I have a question.' },
      { cn: '明天有考试。', py: 'Míngtiān yǒu kǎoshì.', en: 'There is an exam tomorrow.' },
      { cn: '你懂了吗？', py: 'Nǐ dǒng le ma?', en: 'Do you understand?' },
      { cn: '我可以问你吗？', py: 'Wǒ kěyǐ wèn nǐ ma?', en: 'May I ask you (something)?' },
    ],
  },
  {
    id: 'u24', title: 'Time Flies', icon: '⏰', hsk: 2,
    words: ['xiaoshi', 'shijian', 'mei3', 'rang4', 'deng3', 'chang2', 'zaoshang', 'qunian', 'shengri'],
    hanzi: ['时', '间', '每', '等'],
    grammar: {
      name: '每 — every single one',
      intro: '<b>每天</b> = every day, <b>每年</b> = every year — great for habits like this app! Duration comes AFTER the verb: 我等了<b>两个小时</b> = "I waited two hours".',
      examples: [
        { cn: '每天早上我喝咖啡。', py: 'Měi tiān zǎoshang wǒ hē kāfēi.', en: 'Every morning I drink coffee.' },
        { cn: '我等了两个小时。', py: 'Wǒ děng le liǎng gè xiǎoshí.', en: 'I waited for two hours.' },
      ],
      fillBlanks: [
        { before: '', after: '天早上我跑步。', answer: '每', choices: ['每', '几', '昨'], en: 'Every morning I jog.' },
        { before: '我等了两个小', after: '。', answer: '时', choices: ['时', '点', '天'], en: 'I waited for two hours.' },
        { before: '今天是我的生', after: '。', answer: '日', choices: ['日', '月', '年'], en: 'Today is my birthday.' },
      ],
      tiles: [
        { parts: ['每天', '我', '跑步'], en: 'I jog every day.' },
        { parts: ['今天', '是', '我的', '生日'], en: 'Today is my birthday.' },
      ],
    },
    sentences: [
      { cn: '我等了两个小时。', py: 'Wǒ děng le liǎng gè xiǎoshí.', en: 'I waited for two hours.' },
      { cn: '每天早上我喝咖啡。', py: 'Měi tiān zǎoshang wǒ hē kāfēi.', en: 'Every morning I drink coffee.' },
      { cn: '今天是我的生日。', py: 'Jīntiān shì wǒ de shēngrì.', en: 'Today is my birthday.' },
      { cn: '你有时间吗？', py: 'Nǐ yǒu shíjiān ma?', en: 'Do you have time?' },
    ],
  },
  {
    id: 'u25', title: 'Say It', icon: '💬', hsk: 2,
    words: ['keneng', 'bie2', 'zai4', 'zhengzai', 'gei3', 'gaosu', 'shuohua', 'shiqing', 'zhidao'],
    hanzi: ['给', '别', '知', '事'],
    grammar: {
      name: '正在 — happening right now',
      intro: '<b>正在</b> + verb = "in the middle of doing": 他正在睡觉 = "he\'s sleeping (right now)". Stop someone with <b>别</b>: 别说话! = "don\'t talk!" And <b>给</b> points actions at people: 我给你打电话 = "I\'ll call you".',
      examples: [
        { cn: '他正在睡觉。', py: 'Tā zhèngzài shuìjiào.', en: 'He is sleeping (right now).' },
        { cn: '我给你打电话。', py: 'Wǒ gěi nǐ dǎ diànhuà.', en: "I'll give you a call." },
      ],
      fillBlanks: [
        { before: '他', after: '在睡觉。', answer: '正', choices: ['正', '已', '还'], en: 'He is sleeping right now.' },
        { before: '', after: '说话！', answer: '别', choices: ['别', '再', '给'], en: "Don't talk!" },
        { before: '我', after: '你打电话。', answer: '给', choices: ['给', '别', '让'], en: "I'll give you a call." },
      ],
      tiles: [
        { parts: ['他', '正在', '睡觉'], en: 'He is sleeping right now.' },
        { parts: ['请', '再', '说', '一', '次'], en: 'Please say it again.' },
      ],
    },
    sentences: [
      { cn: '他正在睡觉，别说话。', py: 'Tā zhèngzài shuìjiào, bié shuōhuà.', en: "He's sleeping — don't talk." },
      { cn: '请再说一次。', py: 'Qǐng zài shuō yí cì.', en: 'Please say it again.' },
      { cn: '我给你打电话。', py: 'Wǒ gěi nǐ dǎ diànhuà.', en: "I'll give you a call." },
      { cn: '你知道这件事情吗？', py: 'Nǐ zhīdào zhè jiàn shìqing ma?', en: 'Do you know about this matter?' },
    ],
  },
  {
    id: 'u26', title: 'Sports & Fun', icon: '⚽', hsk: 2,
    words: ['lanqiu', 'zuqiu', 'ti1', 'tiaowu', 'changge', 'yundong', 'yiqi', 'dui4'],
    hanzi: ['球', '踢', '唱', '跳'],
    grammar: {
      name: '一起 — doing it together',
      intro: '<b>一起</b> = together, and it goes before the verb: 我们一起打篮球 = "we together play basketball". Note the verb pairs: <b>打</b>篮球 (hit-sports) but <b>踢</b>足球 (kick-sports)!',
      examples: [
        { cn: '我们一起打篮球。', py: 'Wǒmen yìqǐ dǎ lánqiú.', en: 'We play basketball together.' },
        { cn: '他喜欢踢足球。', py: 'Tā xǐhuan tī zúqiú.', en: 'He likes playing soccer.' },
      ],
      fillBlanks: [
        { before: '我们', after: '打篮球。', answer: '一起', choices: ['一起', '一点儿', '每天'], en: 'We play basketball together.' },
        { before: '他喜欢', after: '足球。', answer: '踢', choices: ['踢', '打', '跳'], en: 'He likes playing soccer.' },
        { before: '她喜欢跳', after: '。', answer: '舞', choices: ['舞', '歌', '球'], en: 'She likes dancing.' },
      ],
      tiles: [
        { parts: ['我们', '一起', '打', '篮球'], en: 'We play basketball together.' },
        { parts: ['他', '喜欢', '踢', '足球'], en: 'He likes playing soccer.' },
      ],
    },
    sentences: [
      { cn: '我们一起打篮球。', py: 'Wǒmen yìqǐ dǎ lánqiú.', en: 'We play basketball together.' },
      { cn: '他喜欢踢足球。', py: 'Tā xǐhuan tī zúqiú.', en: 'He likes playing soccer.' },
      { cn: '她唱歌很好听。', py: 'Tā chànggē hěn hǎotīng.', en: 'Her singing sounds lovely.' },
      { cn: '你喜欢什么运动？', py: 'Nǐ xǐhuan shénme yùndòng?', en: 'What sports do you like?' },
    ],
  },
  {
    id: 'u27', title: 'Colors & Looks', icon: '🎨', hsk: 2,
    words: ['hong2', 'bai2', 'hei1', 'yanse', 'xin1', 'gao1', 'piaoliang', 'yanjing', 'xiao4', 'chuan1'],
    hanzi: ['红', '白', '黑', '高'],
    grammar: {
      name: 'Describing with 的',
      intro: 'Attach descriptions to nouns with <b>的</b>: 红色<b>的</b>衣服 = "red clothes", 新<b>的</b>手机 = "a new phone", 我最喜欢<b>的</b>书 = "my favorite book". Description first, thing last!',
      examples: [
        { cn: '她穿红衣服很漂亮。', py: 'Tā chuān hóng yīfu hěn piàoliang.', en: 'She looks pretty in red clothes.' },
        { cn: '你喜欢什么颜色？', py: 'Nǐ xǐhuan shénme yánsè?', en: 'What color do you like?' },
      ],
      fillBlanks: [
        { before: '我喜欢红色', after: '衣服。', answer: '的', choices: ['的', '了', '吗'], en: 'I like red clothes.' },
        { before: '他很', after: '。', answer: '高', choices: ['高', '新', '白'], en: 'He is tall.' },
        { before: '她穿', after: '衣服。', answer: '红', choices: ['红', '黑', '白'], en: 'She wears red clothes.' },
      ],
      tiles: [
        { parts: ['你', '喜欢', '什么', '颜色'], en: 'What color do you like?' },
        { parts: ['她', '穿', '红', '衣服'], en: 'She wears red clothes.' },
      ],
    },
    sentences: [
      { cn: '她穿红衣服很漂亮。', py: 'Tā chuān hóng yīfu hěn piàoliang.', en: 'She looks pretty in red clothes.' },
      { cn: '你喜欢什么颜色？', py: 'Nǐ xǐhuan shénme yánsè?', en: 'What color do you like?' },
      { cn: '他很高。', py: 'Tā hěn gāo.', en: 'He is tall.' },
      { cn: '我的猫是黑色的。', py: 'Wǒ de māo shì hēisè de.', en: 'My cat is black.' },
    ],
  },
  {
    id: 'u28', title: 'How & Why', icon: '❓', hsk: 2,
    words: ['weishenme', 'nin2', 'ta3', 'ba5', 'man4', 'kuai4', 'cuo4', 'yao4', 'zhen1'],
    hanzi: ['您', '它', '快', '慢'],
    grammar: {
      name: '吧 — come on, let\'s!',
      intro: 'End a sentence with <b>吧</b> to suggest: 我们走<b>吧</b>! = "let\'s go!" Ask reasons with <b>为什么</b> = "why" — answer with 因为. And use <b>您</b> instead of 你 to be extra polite.',
      examples: [
        { cn: '我们走吧！', py: 'Wǒmen zǒu ba!', en: "Let's go!" },
        { cn: '你为什么不吃药？', py: 'Nǐ wèishénme bù chī yào?', en: "Why don't you take your medicine?" },
      ],
      fillBlanks: [
        { before: '我们走', after: '！', answer: '吧', choices: ['吧', '吗', '呢'], en: "Let's go!" },
        { before: '你', after: '什么不吃药？', answer: '为', choices: ['为', '别', '做'], en: "Why don't you take your medicine?" },
        { before: '我写', after: '了。', answer: '错', choices: ['错', '对', '快'], en: 'I wrote it wrong.' },
      ],
      tiles: [
        { parts: ['我们', '一起', '去', '吧'], en: "Let's go together!" },
        { parts: ['你', '为什么', '不', '来'], en: "Why aren't you coming?" },
      ],
    },
    sentences: [
      { cn: '我们走吧！', py: 'Wǒmen zǒu ba!', en: "Let's go!" },
      { cn: '你为什么不吃药？', py: 'Nǐ wèishénme bù chī yào?', en: "Why don't you take your medicine?" },
      { cn: '您好，王先生！', py: 'Nín hǎo, Wáng xiānsheng!', en: 'Hello, Mr. Wang!' },
      { cn: '慢一点儿！', py: 'Màn yìdiǎnr!', en: 'A bit slower, please!' },
    ],
  },
  {
    id: 'u29', title: 'Around the House', icon: '🏠', hsk: 2,
    words: ['fangjian', 'shouji', 'shoubiao', 'baozhi', 'chuang2', 'zhao3', 'song4', 'xi3'],
    hanzi: ['房', '床', '手', '表'],
    grammar: {
      name: '送给 — giving things to people',
      intro: 'Give things with verb + <b>给</b>: 爸爸<b>送给</b>我一个手表 = "Dad gave me a watch". Look for lost things with <b>找</b>: 我在找我的手机 = "I\'m looking for my phone" (在 = right now).',
      examples: [
        { cn: '爸爸送给我一个手表。', py: 'Bàba sòng gěi wǒ yí gè shǒubiǎo.', en: 'Dad gave me a watch.' },
        { cn: '我在找我的手机。', py: 'Wǒ zài zhǎo wǒ de shǒujī.', en: "I'm looking for my phone." },
      ],
      fillBlanks: [
        { before: '爸爸送', after: '我一个手表。', answer: '给', choices: ['给', '到', '让'], en: 'Dad gave me a watch.' },
        { before: '我在', after: '我的手机。', answer: '找', choices: ['找', '洗', '送'], en: "I'm looking for my phone." },
        { before: '他在房间', after: '看报纸。', answer: '里', choices: ['里', '外', '边'], en: "He's reading the newspaper in the room." },
      ],
      tiles: [
        { parts: ['爸爸', '送给', '我', '一个', '手表'], en: 'Dad gave me a watch.' },
        { parts: ['我', '在', '找', '我的', '手机'], en: "I'm looking for my phone." },
      ],
    },
    sentences: [
      { cn: '我在找我的手机。', py: 'Wǒ zài zhǎo wǒ de shǒujī.', en: "I'm looking for my phone." },
      { cn: '爸爸送给我一个手表。', py: 'Bàba sòng gěi wǒ yí gè shǒubiǎo.', en: 'Dad gave me a watch.' },
      { cn: '他在房间里看报纸。', py: 'Tā zài fángjiān li kàn bàozhǐ.', en: "He's reading the newspaper in the room." },
      { cn: '我要洗衣服。', py: 'Wǒ yào xǐ yīfu.', en: 'I need to wash clothes.' },
    ],
  },
  {
    id: 'u30', title: 'Big Finale', icon: '🏆', hsk: 2,
    words: ['xiwang', 'yisi', 'yixia', 'xing4', 'diyi', 'feichang', 'zui4'],
    hanzi: ['希', '望', '意', '思'],
    grammar: {
      name: '等一下! & 最 — wrapping up',
      intro: 'Soften any verb with <b>一下</b>: 等一下 = "wait a sec", 看一下 = "take a look". Say superlatives with <b>最</b>: 我最喜欢的书 = "my favorite (most-liked) book". 你是第一! You made it to the end — 非常好!',
      examples: [
        { cn: '请等一下。', py: 'Qǐng děng yíxià.', en: 'Please wait a moment.' },
        { cn: '这是我最喜欢的书。', py: 'Zhè shì wǒ zuì xǐhuan de shū.', en: 'This is my favorite book.' },
      ],
      fillBlanks: [
        { before: '请等一', after: '。', answer: '下', choices: ['下', '次', '点'], en: 'Please wait a moment.' },
        { before: '我', after: '喜欢北京。', answer: '非常', choices: ['非常', '最', '可能'], en: 'I like Beijing very much.' },
        { before: '这是我', after: '喜欢的电影。', answer: '最', choices: ['最', '真', '别'], en: 'This is my favorite movie.' },
      ],
      tiles: [
        { parts: ['请', '等', '一下'], en: 'Please wait a moment.' },
        { parts: ['我', '非常', '喜欢', '中国'], en: 'I like China very much.' },
      ],
    },
    sentences: [
      { cn: '请等一下。', py: 'Qǐng děng yíxià.', en: 'Please wait a moment.' },
      { cn: '您贵姓？', py: 'Nín guì xìng?', en: 'What is your (honorable) surname?' },
      { cn: '我非常喜欢中国。', py: 'Wǒ fēicháng xǐhuan Zhōngguó.', en: 'I like China very much.' },
      { cn: '这是我最喜欢的书。', py: 'Zhè shì wǒ zuì xǐhuan de shū.', en: 'This is my favorite book.' },
    ],
  }
);
